src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/utils.js
Displays a message "(nouns) are currently unavailable. Please try again later." when JSON files are not found. This change was already made on the production website.
=> Add error message when JSON files are not foud

README.md
Updated README: https://github.com/stanford-crfm/helm/tree/update_readme#readme
=> Update README with log and paper link

.readthedocs.yaml, mkdocs.yml
ReadTheDocs build is currently broken; this should fix it. Also fix YAML indentation (use 2 spaces instead of 4).
Fixes #1164
=> Fix ReadTheDocs YAML configuration

scripts/cache/fix_anthropic_cache.py
In `fix_anthropic_cache.py`, we're adding correct log probs to each entry in the Anthropic cache, which requires calls to Anthropic's `topk_logprobs` endpoint. This PR adds a retry when the log probs request fails.
=> Retry failed logprobs request in `fix_anthropic_cache.py`

docs/perturbations.md, src/helm/benchmark/augmentations/contraction_expansion_perturbation.py, src/helm/benchmark/augmentations/contrast_sets_perturbation.py, src/helm/benchmark/augmentations/filler_words_perturbation.py, src/helm/benchmark/augmentations/lowercase_perturbation.py, src/helm/benchmark/augmentations/misspelling_perturbation.py, src/helm/benchmark/augmentations/person_name_perturbation.py, src/helm/benchmark/augmentations/synonym_perturbation.py, src/helm/benchmark/augmentations/typos_perturbation.py
=> Add documentation for perturbations

src/helm/benchmark/static/schema.yaml, src/helm/proxy/models.py
Resolves #1200 
The wider context window is handled by `WIDER_CONTEXT_WINDOW_TAG`.
=> Added `openai/text-davinci-003`

docs/mkdocs_macros.py, src/helm/benchmark/run_expander.py
=> Add documentation for run expanders

docs/docstrings.css, docs/schemas.md, mkdocs.yml, src/helm/benchmark/adapter.py, src/helm/benchmark/augmentations/perturbation_description.py, src/helm/benchmark/metrics/metric.py, src/helm/benchmark/scenarios/scenario.py, src/helm/common/request.py
=> Add documentation for dataclass schemas

src/helm/benchmark/metrics/tokens_metric.py
=> Add perturbation and trial to PerInstanceStats from TokensMetric

requirements-freeze.txt, requirements.txt
Addresses vulnerabilities found by Dependabot.
=> Upgrade dependencies for Dependabot

pre-commit.sh
=> Skip installing pytorch with CUDA on Mac OS

src/helm/benchmark/metrics/metric.py
=> Add perturbation to PerInstanceStats for language_modeling

src/helm/benchmark/runner.py
=> Skip run groups and metric groups that do not exist in schema

src/helm/proxy/clients/chat_gpt_client.py
Otherwise, it tries to log in whenever we initialize `ChatGPTClient`.
=> Only initialize the Chatbot client when users want to make a request

src/helm/benchmark/static/benchmarking.css, src/helm/benchmark/static/benchmarking.js
=> Add sorting for table frontends

src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/json-urls.js
=> Use instances.json and predictions.json in frontend

src/helm/benchmark/adapter.py, src/helm/benchmark/presentation/run_display.py, src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/runner.py, src/helm/benchmark/static/json-urls.js
Also add a new JSON `requests.json` file for displaying requests.
=> Write derived run display JSON in helm-summarize instead of helm-run

src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/json-urls.js
=> Use display_requests.json instead of scenario_state_slim.json in frontend

src/helm/proxy/clients/auto_client.py
=> Use separate memoization dict for tokenization clients

src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/presentation/table.py, src/helm/benchmark/static/benchmarking.js
- Win rates now ignore strongly contaminated cells.
- We now have the option of doing median aggregation.
=> Win rate improvements

src/helm/benchmark/static/schema.yaml
Resolves https://github.com/stanford-crfm/helm/issues/1270
=> Mark Aleph Alpha models as todo

src/helm/benchmark/presentation/run_specs_chat_gpt.conf, src/helm/benchmark/run_expander.py
I made some changes to the conf file after running more experiments with ChatGPT (see comments in the conf file). I will share the results I have so far soon.
=> Updated `run_specs_chat_gpt.conf`

src/helm/benchmark/presentation/run_display.py
=> Fix mean key not found in stat

src/helm/benchmark/static/benchmarking.css, src/helm/benchmark/static/benchmarking.js
- Highlight the current column used for sorting
- Sort by the first sortable column by default
Addresses #832
=> Table sort column highlighting and default

src/helm/benchmark/static/benchmarking.js
Reduces instance and prediction rendering time by ~30% (2.1 seconds to 1.5 seconds). The main optimizations are:
- Reduce the number of `append` calls by using `text` or `html` instead
- Render instances and predictions together, rather than one after another, so that the display reflow is only triggered once instead of twice.
Addresses #1283
=> Optimize instance and prediction frontend rendering

src/helm/benchmark/static/benchmarking.css, src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/index.html
Reduces rendering time by 50%.
Addresses #1283
Fixes #1292
=> Port renderScenarioInstances and renderPredictions to Handlebars

src/helm/benchmark/static/benchmarking.js
This makes the frontend support the new format in #1280
=> Fix frontend to reflect input and output refactor

src/helm/benchmark/scenarios/lex_glue_scenario.py, src/helm/benchmark/scenarios/lextreme_scenario.py
Fixes issues such as `AttributeError: 'LEXTREMEScenario' object has no attribute 'definition_path'`
=> Call super from scenario subclasses

src/helm/benchmark/presentation/run_specs_bigcode.conf, src/helm/benchmark/run_expander.py, src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/santacoder_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/huggingface_tokenizer.py, src/helm/proxy/clients/test_huggingface_tokenizer.py, src/helm/proxy/models.py, src/helm/proxy/test_models.py
- Added support for [SantaCoder](https://huggingface.co/bigcode/santacoder) in `HuggingFaceClient` for now. Will move to `TogetherClient` when it's available (https://github.com/stanford-crfm/helm/issues/1311).
- Added `run_specs_bigcode.conf`.  We will add more scenarios to this list (e.g., biomedical tasks, MathQA, etc.).
=> `SantaCoder` for BigCode

docs/tutorial.md
=> Fix tutorial

src/helm/benchmark/scenarios/lextreme_scenario.py
Fixed the issue with the NER quotes
=> Fix legal scenarios

src/helm/benchmark/presentation/run_specs.conf
Resolves https://github.com/stanford-crfm/helm/issues/1335
=> Removed MMLU comment from conf file

src/helm/benchmark/__init__.py, src/helm/benchmark/presentation/run_specs.conf, src/helm/benchmark/presentation/run_specs_biomedical.conf, src/helm/benchmark/run_expander.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/covid_dialog_scenario.py, src/helm/benchmark/scenarios/me_q_sum_scenario.py, src/helm/benchmark/scenarios/med_dialog_scenario.py, src/helm/benchmark/scenarios/med_mcqa_scenario.py, src/helm/benchmark/scenarios/med_paragraph_simplification_scenario.py, src/helm/benchmark/scenarios/med_qa_scenario.py
Added biomedical scenarios to HELM:
- COVID Dialogue
- MeQSum
- MedDialog
- MedMCQA
- MedParagraphSimplification
- MedQA
- PubMedQA
Defined a suite of biomedical tasks at `run_specs_biomedical.conf`, which includes the scenarios above and some MMLU and BIG-bench tasks. Also, added MedQA to `run_specs.conf`. Resolves https://github.com/stanford-crfm/helm/issues/1318.
I ran with OpenAI's `text-davinci-003` model on a small subset of instances. Below are the descriptions of the scenarios with example instances + model predictions.
COVID Dialogue is a medical dialogue dataset of conversations between doctors and patients on their COVID-19 concerns.
MeQSum is a corpus of 1,000 summarized consumer health questions.
The MedDialog dataset (English) contains conversations between doctors and …
=> HELM BioMed

MANIFEST.in, src/helm/proxy/clients/yalm_tokenizer/yalm_tokenizer.py
=> Package vocab file for YaLMTokenizer

src/helm/benchmark/static/schema.yaml, src/helm/proxy/models.py
=> Add Cohere Command models

docs/tutorial.md, src/helm/benchmark/presentation/create_plots.py, src/helm/benchmark/static/benchmarking.css, src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/index.html, src/helm/benchmark/static/json-urls.js, src/helm/benchmark/static/plot-captions.js
Adding some simple functionality for showing our plots on the web as PNGs.
=> web plots prototype

src/helm/benchmark/static/schema.yaml, src/helm/proxy/models.py
=> Add AI21 Jurassic-2 models

scripts/fact_completion/create_benchmark.py, scripts/fact_completion/fetch_triples_and_aliases.py, scripts/fact_completion/filter_triples.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/runner.py, src/helm/benchmark/scenarios/copyright_scenario.py, src/helm/common/general.py
Reduces the amount of log spam in non-interactive mode.
Fixes #1351
=> Disable tqdm in non-interactive mode

docs/huggingface_models.md, mkdocs.yml, src/helm/benchmark/run.py, src/helm/benchmark/window_services/huggingface_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/huggingface_model_registry.py, src/helm/proxy/clients/huggingface_tokenizer.py
Allow running `AutoModelForCausalLM` models from Hugging Face Model Hub using the `--register-huggingface-models` flag.
Addresses #1103
=> Hugging Face Model Hub integration

src/helm/benchmark/window_services/wider_ai21_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/models.py
=> Increase AI21 Jurassic-2 Large and Grande sequence length

src/helm/benchmark/__init__.py, src/helm/benchmark/metrics/summarization_metrics.py, src/helm/benchmark/presentation/run_specs.conf, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/legal_summarization_scenario.py, src/helm/benchmark/scenarios/summarization_scenario.py, src/helm/benchmark/static/schema.yaml
This is a new PR for the legal summarization scenarios
=> Add legal summarization scenarios

src/helm/benchmark/run.py, src/helm/benchmark/window_services/ai21_window_service.py, src/helm/benchmark/window_services/local_window_service.py, src/helm/benchmark/window_services/remote_window_service.py, src/helm/benchmark/window_services/tokenizer_service.py, src/helm/benchmark/window_services/window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/common/tokenization_request.py, src/helm/proxy/clients/remote_model_registry.py, src/helm/proxy/server.py, src/helm/proxy/services/remote_service.py, src/helm/proxy/services/server_service.py, src/helm/proxy/services/service.py
This PR is for improving the functionality of the remote-service. The server has complete model information, and the client first retrieves the supported model information from the server. This way, as long as the server supports the model, the client can perform evaluations on it.
=> Expand the functionality of remote-service to support client testing of any model.

src/helm/benchmark/adaptation/adapters/multiple_choice_joint_adapter.py, src/helm/benchmark/run_expander.py, src/helm/benchmark/run_specs.py, src/helm/proxy/models.py
This PR will replace #1470: adds a RunExpander to increase temperature by a small amount for models which encounter bugs with temperature set exactly to zero. These models can be tagged with `BUGGY_TEMP_0_TAG`.
=> Add RunExpander to increase temperature

pre-commit.sh, scripts/vhelm_run.py, src/helm/benchmark/__init__.py, src/helm/benchmark/metrics/images/detection_metrics.py, src/helm/benchmark/metrics/images/detectors/base_detector.py, src/helm/benchmark/metrics/images/detectors/vitdet.py, src/helm/benchmark/metrics/images/fractal_dimension_metric.py, src/helm/benchmark/presentation/run_specs_vhelm.conf, src/helm/benchmark/presentation/run_specs_vhelm_debug.conf, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/detection_scenario.py, src/helm/benchmark/static/schema.yaml
- Detection Scenario
- Detection Metric using ViTDet
1. Clone this repo and check out the `detection` branch: `git checkout detection`.
2. Create a new Conda environment: `conda create -n vhelm python=3.8`
3. Activate the Conda environment: `conda activate vhelm`
4. Install dependencies: `./pre-commit.sh`
The boilerplate code is in this branch (`detection`). Just need to handle the TODOs. I included examples of Scenarios and Metrics in the comments as well. Feel free to directly push changes to this branch/PR.
Run `conda activate vhelm` and `helm-run --suite vhelm_debug -n 1 --conf-path src/helm/benchmark/presentation/run_specs_vhelm_debug.conf --max-eval-instances 10 --local --exit-on-error  --models-to-run huggingface/stable-diffusion-v1-4` on a machine with a GPU.
Results will be …
=> Detection setup for vhelm

src/helm/proxy/clients/cogview2_client.py
To fix the error "AssertionError: You should truncate long input before filling."
=> fix cogview2

src/helm/benchmark/static/schema.yaml
This is breaking the web frontend.
=> Fix duplicated mapping key in YAML

src/helm/benchmark/run_specs.py
This function decorator can be used in the user's custom modules to register custom run spec functions.
Addresses #1487
=> Add run_spec_function() decorator

docs/benchmark.md, docs/huggingface_models.md, docs/quick_start.md, docs/tutorial.md, scripts/helm-run-all.sh, src/helm/benchmark/executor.py, src/helm/benchmark/metrics/tokens/test_openai_token_cost_estimator.py, src/helm/benchmark/presentation/run_specs_biomedical.conf, src/helm/benchmark/presentation/run_specs_interactive_qa.conf, src/helm/benchmark/run.py, src/helm/proxy/cli.py, src/helm/proxy/services/remote_service.py
=> Use local mode by default

src/helm/common/hierarchical_logger.py
=> Revert hierarchical_logger

src/helm/benchmark/presentation/schema.py, src/helm/benchmark/static/schema.yaml, src/helm/proxy/clients/huggingface_model_registry.py, src/helm/proxy/models.py
...so we can stop doing duplicate work putting descriptions for each model we add in two places.  Also adds some comments clarifying the relationship between creator and hosting, which we need to clean up at some point.
=> remove redundant model fields

src/helm/benchmark/window_services/anthropic_window_service.py, src/helm/benchmark/window_services/megatron_window_service.py, src/helm/benchmark/window_services/palmyra_window_service.py, src/helm/benchmark/window_services/test_palmyra_window_service.py
i believe this fixes #1558 and #1531.
=> Updated the limits for Megatron, Anthropic and Palmyra

src/helm/proxy/retry.py
=> Don't wrap exception in retry

src/helm/proxy/clients/anthropic_client.py
=> Added lock to Anthropic client

scripts/deepfloyd.py, scripts/vhelm_run.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/deep_floyd_client.py, src/helm/proxy/models.py
https://huggingface.co/DeepFloyd/IF-I-XL-v1.0
=> Support DeepFloyd IF image generation models

src/helm/proxy/clients/together_client.py
Use async requests for Together models `mpt-7b`, `redpajama-incite-base-3b-v1`, `vicuna-13b`.
=> Async requests for Together

src/helm/proxy/clients/critique_client.py
If `fields["image"]` is specified then it will be added as an image. It should be the url to an image.
=> Add support for images in Scale

src/helm/proxy/clients/palmyra_client.py
Not sure the timeout will actually do something, I think it does but we need to test this
=> Set timeout to 5 minutes for Palmyra

src/helm/benchmark/__init__.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/vicuna_scenario.py
The question dataset used by the Vicuna team to evaluate instruction-following models.
https://lmsys.org/blog/2023-03-30-vicuna/
To run GPT-4 on the scenario, use: `venv/bin/helm-run -r vicuna:model=openai/gpt-4-0314 -m <max_eval_instances> -t <num_trials> --suite <suite_id>`
Some example `scenario_states`:
**Example 1:**
**Prompt**: "How can you determine if a restaurant is popular among locals or mainly attracts tourists, and why might this information be useful?\n"
**GPT-4 Response**: "Determining if a restaurant is popular among locals or mainly attracts tourists can be done through several methods:\n\n1. Online reviews: Check websites like TripAdvisor, Yelp, or Google Maps for customer reviews. Look for reviews written by locals or people mentioning they are locals. A higher …
=> Vicuna scenario

src/helm/benchmark/run_specs.py
Currently we append `PROMPT_ANSWER_START = "The answer is"` to every prompt for the claude model to reduce generation length. Although this might be ideal for traditional classification/generation scenarios, we do not want this restriction for instruction following scenarios.
=> Stop using claude's PROMPT_ANSWER_START for instruction following scenarios

src/helm/benchmark/presentation/run_specs.conf, src/helm/benchmark/run_expander.py, src/helm/proxy/models.py
When determining if a model is an "instruction-following" one, some models are on the borderline. Would be great if @yifanmai or someone else can check my tagging decisions!
=> Update run_specs.conf to deprioritize Lextreme and add instruction following scenarios

src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/index.html
Remove mentions of HELM and add abstract of HEIM.
=> Update HEIM front page

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
mpt-7b is not a production Together model.
=> Move mpt-7b from Together to Hugging Face

docs/mkdocs_macros.py, docs/models.md, mkdocs.yml
Fix #1615 .
I also added the model access and a warning message if the model is still in `todo`.
=> Fix models not displaying

scripts/efficiency/generate_instances.py, setup.cfg, src/helm/benchmark/static/schema.yaml, src/helm/common/general.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/test_auto_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py, src/helm/proxy/services/server_service.py, src/helm/proxy/services/service.py
Also add infrastructure for unit testing models on GitHub Actions using GitHub Actions Secrets. Addresses #1700
=> Add Databricks Koala on Together

src/helm/proxy/clients/test_together_client.py
Add Tests for TogetherClient
* Add test for `convert_to_raw_request`
* Add test to assert exception on missing api key
Resolves #1547
=> Add Tests for TogetherClient

src/helm/proxy/models.py
This is OpenAI's currently [recommended embedding model](https://openai.com/blog/new-and-improved-embedding-model).
Fixes #1645
=> Add text-embedding-ada-002 model

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/wider_openai_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/models.py
Adds `openai/gpt-4-0613`, `openai/gpt-4-32k-0613`, `openai/gpt-3.5-turbo-16k-0613`
=> Add OpenAI 0613 model snapshots

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/gptneox_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
Adds `together/redpajama-incite-instruct-3b-v1`, `stabilityai/stablelm-base-alpha-3b`, `stabilityai/stablelm-base-alpha-7b`.
Also adds the window service for these models and for Dolly.
=> Add StableLM and RedPajama Instruct on Together

src/helm/benchmark/slurm_runner.py
This allows us to use `export HELM_SLURM_NODE_NAMES=sphinx5,sphinx6` to use sphinx nodes for Hugging Face models.
=> Use Sphinx for Hugging Face models in SlurmRunner

src/helm/benchmark/presentation/run_specs_lite.conf
This removes some scenarios from `run_specs.conf`, but preserves the priority of each run entry.
=> Create run_specs_lite.conf for HELM-lite

src/helm/benchmark/window_services/llama_window_service.py, src/helm/proxy/clients/together_client.py
=> Bugfixes for Llama 2

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/test_together_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
Also changes model name from `together/llama-7b` to `meta/llama-7b`.
=> Add all sizes of LLaMA on Together

src/helm/benchmark/presentation/run_specs_lite.conf
Removing everything that needs logprobs from HELM lite.
=> Remove multiple choice separate adapter runs from HELM lite

docs/requirements.txt
mkdocstrings v0.19.0 is now outdated.
=> Fix the mkdocs build

docs/tutorial.md, src/helm/benchmark/static/index.html
Plots are currently not working, so we remove them from the frontend and documentation to avoid user confusion.
Addresses #1441
=> Disable plots

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/huggingface_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
=> Add Alpaca, Falcon, MPT, and Vicuna on Together

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/static/schema.yaml
This lists the new CLEVA scenarios and metrics. Most of the fields need to be field in later.
=> Add scaffolding for CLEVA schema

src/helm/proxy/clients/http_model_client.py
Proposed fix for #1813
The corresponding PR in neurips comp is:
https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge/pull/20
=> Enable decode method for neruips/local model

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/presentation/test_summarize.py, src/helm/benchmark/static/schema.yaml
=> Fix error in schema and add regression test

.github/workflows/test.yml
* Update Github Actions CI to not run python tests when there are only changes to the frontend code in `src/helm-frontend/**`
=> Skip python tests on frontend changes

setup.cfg, src/helm/proxy/clients/lit_gpt_client.py
Provide manual instructions for installing lit-gpt from GitHub because PyPI does not allow installing dependencies directly from GitHub.
=> Tell users to install lit-gpt manually

requirements.txt, setup.cfg, src/helm/benchmark/augmentations/cleva_perturbation.py, src/helm/benchmark/augmentations/person_name_perturbation.py, src/helm/benchmark/run_specs.py
=> Upgrade mypy

src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/index.html
Adds GA tracking script, and tracks individual page views.
=> Added google analytics

.pre-commit-config.yaml, requirements.txt, src/helm/common/images_utils.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/vision_language/idefics_client.py
- Fix unused imports and other minor issues (from #1892)
- Fix incorrect type name `PIL.Pillow`, which should be `PIL.Pillow.Pillow` (from #1871)
- Fix type error in `multimodal_prompt` and make error handling more robust (from #1871)
- Pin version of `types-Pillow`, because mypy auto-installs `types-Pillow` version 10, which is incompatible with version 9.
=> Fix pre-commit breakages

src/helm/benchmark/run_specs.py, src/helm/benchmark/static/schema.yaml, src/helm/proxy/models.py
Claude 2 does not need max tokens to be increased, unlike the previous Claude models in HELM.
=> Add Anthropic Claude 2

install-dev.sh
Fixes #1904 by forcing the upgrade of pip in install_dev.sh
=> Force upgrade of pip in install_dev.sh

requirements.txt
=> Bump bert-score dependency

src/helm/benchmark/scenarios/summarization_scenario.py
Use the public URL instead of the authenticated URL.
=> Fix URL for summarization dataset

src/helm/benchmark/adaptation/adapters/in_context_learning_adapter.py
The existing return line is performing the same function using list comprehensions.
=> Remove some dead code.

README.md
Fixes README formatting which currently looks garbled on project page.
=> Markdown format for directory structure ASCII art in README.md

src/helm/proxy/clients/auto_client.py
=> Add tokenizer caching

src/helm/benchmark/presentation/run_specs_vhelm.conf, src/helm/benchmark/scenarios/vision_language/viz_wiz_scenario.py, src/helm/benchmark/vlm_run_specs.py
31,000 visual questions created by blind people
Paper: https://arxiv.org/abs/1802.08218
Website: https://vizwiz.org/tasks-and-datasets/vqa/
Resolves https://github.com/stanford-crfm/helm/issues/1950
=> VizWiz Scenario

src/helm/common/general.py
I suspect that if threading isn't enough for parallelism, we are going to need a code structure change to support it. I verified all references to parallel_map pass 3 arguments.
=> Remove unused "multiprocess" argument from parallel_map.

src/helm/benchmark/static/schema.yaml
=> Add huggingface/gpt2 to the schema

src/helm/benchmark/metrics/code_metrics.py, src/helm/benchmark/metrics/ranking_metrics.py, src/helm/benchmark/metrics/summarization_metrics.py, src/helm/benchmark/presentation/contamination.py, src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/cleva_scenario.py, src/helm/benchmark/scenarios/code_scenario.py, src/helm/benchmark/scenarios/entity_matching_scenario.py, src/helm/benchmark/scenarios/numeracy_scenario.py, src/helm/benchmark/scenarios/scenario.py, src/helm/common/general.py
Introduced a few helper functions in general to simplify type asserts.
While this isn't very high value, it did reveal a couple oddities I plan to track down in future PRs.
=> Remove some "# type: ignore" statements.

demo.py, docs/tutorial.md, src/helm/benchmark/adaptation/adapters/binary_ranking_adapter.py, src/helm/benchmark/adaptation/adapters/language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/multimodal/in_context_learning_multimodal_adapter.py, src/helm/benchmark/adaptation/adapters/multimodal/test_in_context_learning_multimodal_adapter.py, src/helm/benchmark/adaptation/adapters/multiple_choice_separate_adapter.py, src/helm/benchmark/adaptation/adapters/test_generation_adapter.py, src/helm/benchmark/adaptation/adapters/test_language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/test_multiple_choice_joint_adapter.py, src/helm/benchmark/metrics/test_classification_metrics.py, src/helm/benchmark/metrics/tokens/test_ai21_token_cost_estimator.py, src/helm/benchmark/metrics/tokens/test_openai_token_cost_estimator.py, src/helm/benchmark/model_deployment_registry.py, src/helm/benchmark/presentation/run_specs.conf, src/helm/benchmark/run_expander.py, src/helm/benchmark/run_specs.py, src/helm/common/request.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/test_auto_client.py, src/helm/proxy/clients/test_client.py, src/helm/proxy/clients/test_huggingface_client.py, src/helm/proxy/clients/test_together_client.py, src/helm/proxy/services/test_remote_service.py, src/helm/proxy/services/test_service.py, src/helm/proxy/token_counters/test_ai21_token_counter.py, src/helm/proxy/token_counters/test_openai_token_counter.py
Alternative proposal where we always set _both_ `model` and `model_deployment` in `AdapterSpec` and `Request`.
=> Alternative model deployment proposal

src/helm/benchmark/presentation/summarize.py
Fixes a bug that assigned every run to the latest suite in `runs_to_run_suites.json`.
=> Fix runs_to_run_suites.json

src/helm/benchmark/static/schema.yaml
=> Add detailed to labels

src/helm/benchmark/slurm_jobs.py, src/helm/benchmark/slurm_runner.py
- Add retrying for idempotent Slurm actions (fetching info and cancelling jobs)
- Persist the final cancelled state of all jobs after cancelling all jobs
=> Small Slurm improvements

src/helm/proxy/tokenizers/test_huggingface_tokenizer.py
Demonstrates the pre-existing bug in #1421.
=> Add a test demonstrating the "Already borrowed" bug

src/helm-frontend/README.md
- Replaces NPM instructions with yarn
- Removes discussion of deprecated environment variable approach to releases/suites
=> Update front-end docs

src/helm/proxy/clients/together_client.py
Together AI currently does not support asynchronous requests.
=> Disable async requests for Together

src/helm/benchmark/metrics/basic_metrics.py, src/helm/benchmark/metrics/classification_metrics.py, src/helm/benchmark/metrics/evaluate_reference_metrics.py, src/helm/benchmark/metrics/summarization_metrics.py, src/helm/benchmark/metrics/test_evaluate_reference_metrics.py
All the same code is being called in all the same places, this PR is just extracting it from BasicMetric.
=> Move all code for compute_reference_metrics out of BasicMetric.

src/helm/benchmark/metrics/decodingtrust_fairness_metrics.py, src/helm/benchmark/metrics/decodingtrust_ood_knowledge_metrics.py
=> Update decodingtrust to use new import location normalize_text.

src/helm/benchmark/metrics/decodingtrust_fairness_metrics.py, src/helm/benchmark/metrics/decodingtrust_ood_knowledge_metrics.py, src/helm/benchmark/metrics/decodingtrust_privacy_metrics.py, src/helm/benchmark/metrics/decodingtrust_stereotype_bias_metrics.py
In PR #2171 evaluate_instances was split out of Metric.
=> Update DecodingTrust metrics to EvaluateInstancesMetric.

src/helm/proxy/clients/gcs_client.py, src/helm/proxy/clients/google_translate_client.py, src/helm/proxy/clients/vertexai_client.py
The default Gemini safety filter is too sensitive and causes it to fail 10 out of 28 runs in the Lite config.
Example of failing request:
```
helm.benchmark.executor.ExecutorError: Content has no parts. Request: Request(model_deployment='google/gemini-pro', model='google/gemini-pro', embedding=False, prompt='Here are some input-output examples. Read the examples carefully to figure out the mapping. The output of the last example is not given, and your job is to figure out what it is.\n\nA mark is generic if it is the common name for the product. A mark is descriptive if it describes a purpose, nature, or attribute of the product. A mark is suggestive if it suggests or implies a quality or characteristic of the product. A mark is arbitrary if it is a real English word that has no relation …
```
=> Disable Gemini safety filter

src/helm/proxy/clients/openai_client.py
In the next PR I plan to split make_request into 3 parts. This is making that split cleaner.
=> Refactor openai_client to reduce nesting and duplication.

docs/schemas.md
`ScenarioState` contains the schema for `scenario_state.json`, and should be included.
=> Add ScenarioState to schemas doc

src/helm/benchmark/adaptation/adapters/adapter.py, src/helm/benchmark/adaptation/adapters/in_context_learning_adapter.py, src/helm/benchmark/adaptation/adapters/language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/test_generation_adapter.py, src/helm/benchmark/adaptation/adapters/test_language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/test_multiple_choice_joint_adapter.py, src/helm/benchmark/runner.py
`Adapter.adapt()` should return only a `List[RequestState]` rather than a `ScenarioState`.
=> Change output type of Adapter.adapt()

setup.cfg
Update various Python dependency versions.
=> Update setup.cfg to address security alerts

scripts/data_overlap/requirements-freeze.txt, scripts/data_overlap/requirements.txt
Upgrade dependency versions to fix Dependabot alerts.
=> Fix security vulnerabilities for data_overlap

helm-frontend/yarn.lock
Auto-generated with [yarn-audit-fix](https://www.npmjs.com/package/yarn-audit-fix) by running `npm_config_yes=true npx yarn-audit-fix`
=> Update yarn.lock to address security alerts

helm-frontend/src/components/ReleaseDropdown.tsx, helm-frontend/src/services/getReleaseSummary.ts, helm-frontend/src/types/ReleaseSummary.ts
Adds release date to release dropdown.
Fixes #2043
=> Add release date to release dropdown

.github/workflows/update-requirements.yml
Upgrade requests, Jinja2,  certifi and aiohttp.
=> Upgrade Python dependencies for Dependabot alerts

src/helm/benchmark/metrics/machine_translation_metrics.py
PR #2171 created this base, in between machine_translation being removed in #2009 and re-added in #2283
=> Update machine_translation_metrics to new inheritance base.

src/helm/proxy/static/index.js
=> Remove top_logprobs from proxy server

src/helm/benchmark/presentation/test_run_entry.py
Reverts #2304.
Fixes #2303.
CLEVA is working again.
=> Add CLEVA to test_read_all_run_specs()

helm-frontend/src/routes/Leaderboard.tsx
Previously, we showed `core_scenarios` by default, but this breaks on sub-sites that do not have `core_scenarios` e.g. HELM-Instruct.
=> Show the first group table by default on the leaderboard

.github/workflows/build-frontend.yml, .github/workflows/frontend.yml, .github/workflows/python-publish.yml, .github/workflows/test.yml, .github/workflows/update-requirements.yml
I have updated all actions to their latest stable version except `actions/deploy-pages@v3` as it is unclear if `v4` is stable for now.
=> Update github action versions

src/helm/common/request.py, src/helm/proxy/clients/http_model_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/image_generation/cogview2_client.py, src/helm/proxy/clients/image_generation/dalle2_client.py, src/helm/proxy/clients/image_generation/dalle3_client.py, src/helm/proxy/clients/image_generation/dalle_mini_client.py, src/helm/proxy/clients/image_generation/huggingface_diffusers_client.py, src/helm/proxy/clients/image_generation/lexica_client.py, src/helm/proxy/clients/image_generation/mindalle_client.py, src/helm/proxy/clients/image_generation/nudity_check_client.py, src/helm/proxy/clients/image_generation/together_image_generation_client.py, src/helm/proxy/clients/mistral_client.py, src/helm/proxy/clients/moderation_api_client.py, src/helm/proxy/clients/openai_client.py, src/helm/proxy/clients/palmyra_client.py, src/helm/proxy/clients/perspective_api_client.py, src/helm/proxy/clients/vertexai_client.py, src/helm/proxy/clients/vision_language/huggingface_vlm_client.py, src/helm/proxy/clients/vision_language/idefics_client.py, src/helm/proxy/tokenizers/ai21_tokenizer.py, src/helm/proxy/tokenizers/http_model_tokenizer.py
Also fix a type error in `perspective_api_client`.
=> Add more type annotations to clients

src/helm/benchmark/model_deployment_registry.py, src/helm/benchmark/run_spec_factory.py, src/helm/proxy/server.py
=> Infer default model_deployment in crfm-models server

.github/workflows/test.yml, .github/workflows/update-requirements.yml
This is recommended rather than trying to manage the pip cache ourselves.
=> Cache using actions/setup-python

src/helm/benchmark/metrics/vision_language/image_metrics.py, src/helm/benchmark/scenarios/vision_language/image2structure/image2structure_scenario.py, src/helm/benchmark/scenarios/vision_language/image2structure/webpage/jekyll_server.py
- Log fixes
- Disable some warnings
- Remove limit to 40 instances used while debugging
=> Image2structure cleanup to run webpage and Latex

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Model name is `mistralai/mixtral-8x7b-instruct-v0.1`
Requested by @q-hwang
=> Add Mixtral 8x7b Instruct model on Together

src/helm/config/model_metadata.yaml
The access for API models is limited, not closed.
=> Fix model metadata for Mistral models

src/helm/benchmark/annotation/image2structure/image_compiler_annotator.py, src/helm/benchmark/metrics/vision_language/image_metrics.py
This is the first step to displaying annotations in the frontend
=> Make image2struct annotation a MediaObject

setup.cfg, src/helm/benchmark/presentation/run_specs_vhelm.conf, src/helm/benchmark/presentation/run_specs_vhelm_lite.conf, src/helm/benchmark/run_spec_factory.py, src/helm/benchmark/scenarios/vision_language/mmmu_scenario.py, src/helm/benchmark/scenarios/vision_language/vqa_scenario.py, src/helm/benchmark/static/schema_vlm.yaml, src/helm/clients/vision_language/open_flamingo_client.py, src/helm/clients/vision_language/qwen_vlm_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
Qwen VL needs special truncation after generation since it includes the prompt in the output.
=> Support Alibaba Cloud's open-source VLMs: Qwen VL + Qwen VL Chat VLMs

setup.cfg, src/helm/benchmark/annotation/image2structure/image_compiler_annotator.py, src/helm/benchmark/annotation/image2structure/latex_compiler_annotator.py, src/helm/benchmark/annotation/image2structure/webpage_compiler_annotator.py, src/helm/benchmark/metrics/metric_service.py, src/helm/benchmark/metrics/vision_language/image_metrics.py, src/helm/benchmark/scenarios/vision_language/image2structure/image2structure_scenario.py, src/helm/benchmark/scenarios/vision_language/image2structure/latex_scenario.py, src/helm/benchmark/scenarios/vision_language/image2structure/utils_latex.py, src/helm/benchmark/scenarios/vision_language/image2structure/webpage/driver.py, src/helm/benchmark/scenarios/vision_language/image2structure/webpage/utils.py, src/helm/benchmark/scenarios/vision_language/image2structure/webpage_scenario.py, src/helm/proxy/services/remote_service.py, src/helm/proxy/services/server_service.py, src/helm/proxy/services/service.py
- Text annotation
- Cache is now handled in a clean way using the `MetricSpec`
- Image2struct metrics are now parallelized
=> Added text annotation to image2struct metrics

helm-frontend/src/components/NavDropdown.tsx, helm-frontend/src/components/ReleaseDropdown.tsx
Fetch release index from URL rather than `public/` directory. We can read this in as a window variable too if that is desired let me know.
=> Update release_index.json URL

helm-frontend/src/components/HEIMLanding.tsx, helm-frontend/src/routes/Home.tsx
=> Port HEIM landing page to React

src/helm/benchmark/annotation/image2structure/lilypond_compiler_annotator.py, src/helm/benchmark/metrics/vision_language/image_metrics.py, src/helm/benchmark/run_specs/vlm_run_specs.py
Also, made text-based metrics optional as we don't have the ground truth for all tasks.
=> LilyPond Annotator + Metric

docs/credentials.md
=> Documentation: Credentials

helm-frontend/public/config.js, helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/components/Predictions.tsx, helm-frontend/src/components/Request/Request.tsx, helm-frontend/src/services/getRunsToRunSuites.ts
Fixes a bunch of issues that cause image2struct and VHELM to not render properly.
=> Support VHELM and image2struct in React app

demo.py
The models in the demo files have deleted. This pull request updates the demo file to use working models. This addresses user complaints that the demo file is not working. This also addresses the recent high error rate on the crfm-models server due to people running the demo files.
=> Update model names in demo.py

src/helm/clients/simple_client.py, src/helm/clients/test_simple_client.py
SimpleClient is not that simple. This pull request simplifies it further and makes it conform to best practices, so that it can be used for tutorials. It also fixes some stylistic issues and functional bugs (e.g. incorrect `request_time`). This also adds a unit test, which will be required for future clients submitted to HELM.
=> Simplify SimpleClient

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
- Add versioned Gemini models `gemini-1.0-pro-001` and `gemini-1.0-pro-vision-001`
- Update Gemini Pro model names to include "Pro"
- Added `text-bison@002` and `code-bison@002`
=> Update Google models

src/helm/benchmark/run_specs/classic_run_specs.py
=> Set include_generative_harms_metrics=True for RealToxicityPrompts

src/helm/benchmark/scenarios/vicuna_scenario.py
The current URL returns 404 Not Found.
Fixes #2201
=> Fix download URL for VicunaScenario

src/helm/benchmark/run_spec_factory.py
Fixes #2537 
Thanks @mmonfort for catching this!
=> BugFix: GoogleRunExpander applied to every run

docs/reproducing_leaderboards.md, docs/run_entries.md, docs/run_entries_configuration_files.md
=> Documentation: Run Entries

src/helm/config/tokenizer_configs.yaml
=> Fix Llama 3 prefix and end of text tokens

helm-frontend/src/components/LeaderboardTables.tsx, helm-frontend/src/components/NavDropdown.tsx, helm-frontend/src/components/RowValue.tsx
=> Fix z-index in new front-end components

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Also update Qwen1.5 descriptions and release dates for all sizes.
=> Add Qwen1.5 110B Chat

src/helm/benchmark/huggingface_registration.py
Fix typechecking failures caused by #2609
=> Fix typing for Optimum Intel

src/helm/clients/huggingface_client.py, src/helm/clients/test_client.py, src/helm/clients/test_huggingface_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml, src/helm/tokenizers/auto_tokenizer.py, src/helm/tokenizers/huggingface_tokenizer.py, src/helm/tokenizers/test_huggingface_tokenizer.py
- Add [SEA-LION 7B](https://huggingface.co/aisingapore/sea-lion-7b/tree/main)
- Add [SEA-LION 7B Instruct](https://huggingface.co/aisingapore/sea-lion-7b-instruct/tree/main)
=> Add AI Singapore SEA-LION 7B and SEA-LION 7B Instruct

src/helm/benchmark/metrics/gpt4v_originality_critique_metrics.py, src/helm/proxy/critique/model_critique_client.py
This PR is to fix the GPT-4V auto-evaluator out of option range issue on the Mementos scenario.
=> Fix GPT4V Evaluator Out of Option Range Issue

src/helm/clients/together_client.py
According to a thread on the Together discord, the `stop` parameter is set to the default model stop tokens by default, but if the `stop` parameter is overridden, then the user should manually include the default model stop tokens in the `stop` override.
This fixes a problem where models like `meta/llama-3-8b-chat` would not terminate after a single assistant turn e.g. `What is 1 + 1?` with `stop` set to `[]` results in the output:
```
The answer to 1 + 1 is 2.assistant
That's correct! 1 + 1 = 2. Would you like to try another math problem?assistant
Yes, I'd love to! Go ahead and give me a problem.assistant
Here's one:
2 x 3 = ?
What's your answer?assistant
Easy one!
2 x 3 = 6
Is that correct?assistant
```
=> Add default stop sequence to TogetherClient

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
=> Add Typhoon v1.5 models

src/helm/benchmark/annotation/air_bench_annotator.py, src/helm/benchmark/scenarios/air_bench_scenario.py
Switch from the beta URL to the production URL
=> Update dataset URLs for AIRBench2024

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
=> Add Sailor models

helm-frontend/public/config.js, helm-frontend/src/components/LeaderboardTables.tsx, helm-frontend/src/components/MiniLeaderboardTables.tsx, helm-frontend/src/types/HeaderValue.ts
Helps with AIR bench issues
Will close #2711
=> Fix for lowerIsBetter sorting

src/helm/benchmark/annotation/live_qa_annotator.py, src/helm/benchmark/annotation/medication_qa_annotator.py
=> Skip LiveQA and MedicationQA annotators if generated output is empty

src/helm/benchmark/scenarios/decodingtrust_stereotype_bias_scenario.py
=> Fix lint error

docs/Importing_custom_modules.md, docs/importing_custom_modules.md
=> Documentation: Importing Custom Modules

src/helm/benchmark/static/schema_air_bench.yaml
The judge prompts have been changed so that a score of 1 indicates safe rather than unsafe responses, and a score of 0 indicates unsafe rather than safe responses.
=> Set lower_is_better to false for AIR-Bench scores

setup.cfg, src/helm/clients/ai21_client.py, src/helm/config/model_deployments.yaml, src/helm/config/tokenizer_configs.yaml, src/helm/tokenizers/ai21_tokenizer.py, src/helm/tokenizers/test_ai21_tokenizer.py
=> Add local tokenizer for AI21

src/helm/benchmark/metrics/vision_language/image_metrics.py, src/helm/clients/anthropic_client.py, src/helm/clients/openai_client.py, src/helm/clients/vision_language/open_flamingo_client.py, src/helm/common/images_utils.py, src/helm/common/request.py
- Add validation for multimedia objects text and image types.
=> [Issues  #2439] Refactor the validation out of clients and add it to the request.py

src/helm/clients/huggingface_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
Also allow `torch_dtype` to be set to `"auto"` for `HuggingFaceClient`.
=> Add Phi-3 models

src/helm/benchmark/scenarios/vision_language/mementos_scenario.py
The ownership of mementos dataset has been changed from shenmishajing to RussWang96. Therefore, its dataset name have to be updated.
=> Update the dataset name of mementos

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
- Add descriptions for model metadata
- Use `TogetherChatClient` instead of `TogetherClient`
=> Fix bugs with Llama 3.1

demo.py
- Replace outdated models with current models
- Remove `model_deployment` since it is now auto-inferred
=> Update models in demo.py

helm-frontend/src/routes/Runs.tsx
=> Fix bug causing Predictions page to repeatedly download schema.json

.github/workflows/test.yml, .github/workflows/update-requirements.yml, install-dev.sh
Addresses #2855.
This temporarily fixes GitHub Actions; see issue for explanation.
=> Temporarily set pip version to 24.1.2

src/helm/benchmark/run.py
- Validate that all models passed to `--models-to-run` exist
- Validate that `--models-to-run` is set if the `models=` run expander expands to multiple models
=> Add validation for --models-to-run

src/helm/benchmark/scenarios/test_ewok_scenario.py
This is a scenario test and should be marked appropriately.
=> Add scenarios mark to test_ewok_scenario

src/helm/clients/nvidia_nim_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
Uses the NVIDIA NIM inference service.
=> Add Nemotron-4 Instruct

src/helm/benchmark/static/schema_safety.yaml
I have unified the metrics in the safety benchmarks and therefore need to update this schema for the new metrics
=> Update safety schema for unified safety metrics

src/helm/benchmark/annotation/call_center_annotator.py
Changing annotator for now due to cost issues
=> Use GPT-4o mini for call center annotator

helm-frontend/src/components/NavBar/NavBar.tsx
=> Link to CRFM website from logo

setup.cfg
Addresses #2926. See issue for details.
=> Pin nltk dependency to <3.8.2

src/helm/benchmark/scenarios/harm_bench_scenario.py
At some point the wrong URL was copied in here (currently it's the raw HTML rather than the raw file). I have fixed it now.
=> Fix HarmBench scenario download URL

src/helm/benchmark/annotation/call_center_annotator.py
Present the reference summary before or after the generated summary depending on the parity of the instance ID.
=> Shuffle pairs in pairwise comparison in call_center_annotator

.github/workflows/update-requirements.yml
Addresses #2855. See issue description for explanation.
=> Pin pip version in update requirements GitHub Action workflow

src/helm/benchmark/static/schema_safety.yaml
Clarify metric description, and remove efficiency & general information
=> Update safety schema

src/helm/benchmark/presentation/test_summarize.py
Clarifies the semantics of win rates under various conditions such as missing values.
=> Add test for computing win rates

src/helm/benchmark/run_specs/finance_run_specs.py, src/helm/benchmark/scenarios/raft_scenario.py
Add a slight modification to the instruction prompt for BANKING77 for instruction-following models.
=> Fix prompt for BANKING77

helm-frontend/src/routes/Run.tsx, helm-frontend/src/services/getRunSpecByName.ts
=> Fetch single run spec rather than all run specs on predictions page

docs/code.md
This is based on what I observe in the code today.
=> Update documentation for how to add scenarios and metrics. 

README.md, docs/index.md, helm-frontend/src/components/VHELMLanding.tsx
Also add a leaderboard button to the VHELM frontend.
=> Add link to VHELM paper

src/helm/benchmark/metrics/vision_language/image_metrics.py
=> flip LPIPS so that '1' is better

.github/workflows/test_scenarios.yml, src/helm/benchmark/scenarios/test_ewok_scenario.py
- Provide `HF_TOKEN` secret to GHA scenario tests workflow
- Fix incorrect dataset size assert
- Catch authentication-related exceptions raised by Hugging Face Hub client
=> Fix test_ewok_scenario.py breakage

src/helm/benchmark/scenarios/scenario.py
=> Add extra_data field to Instance

setup.cfg, src/helm/benchmark/presentation/run_entries_speech.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/audio_mnist_scenario.py, src/helm/benchmark/scenarios/audio_language/covost2_scenario.py, src/helm/benchmark/static/schema_speech.yaml, src/helm/clients/openai_client.py, src/helm/common/audio_utils.py
Added Covost2Scenario:
Some OpenAI fixes to support local audio files.
=> CoVost-2: Speech Machine Translation

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Added Mistral 2 Large and Llama 3.1 models on Amazon Bedrock
=> Added Mistral 2 Large and Llama 3.1 models on Amazon Bedrock

src/helm/benchmark/metrics/nltk_helper.py
This makes it so that the correct package `punkt_tab` will be installed for the future major version 4 of nltk.
=> Fix minor bug in punkt installation logic

helm-frontend/public/config.js, helm-frontend/src/components/ReleaseDropdown.tsx
=> Add a badge indicating if the release is latest or stale

helm-frontend/src/components/NavDropdown.tsx
=> Change title for HELM leaderboards

helm-frontend/src/components/ReleaseDropdown.tsx
=> Show "preview" badge if current version is not released yet

docs/huggingface_models.md
=> Add documentation for evaluating local Hugging Face models

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/static/schema_safety.yaml
- Remove win rate column from safety tables
- Rename "mean performance" to "mean score"
=> Minor tweaks to summarization for safety

helm-frontend/src/components/Instances.tsx, helm-frontend/src/routes/Run.tsx
This improves the encapsulation of these components.
=> Refactor Instances component out of Run component

docs/adding_new_scenarios.md
Adding more instructions to make the documentation more clear as well as fixing some typos and completing unfinished sentences.
=> Update on adding_new_scenarios.md

src/helm/clients/upstage_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Add the Solar Pro model through the Upstage API.
=> Add Solar Pro model

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
We would like to request the integration of these models into the HELM leaderboard under the ThaiExam benchmark.
=> Add NECTEC

src/helm/benchmark/presentation/run_entries_lite_20240424_legalbench_instructions.conf
This provides additional, more explicit instructions for LegalBench that some models need.
=> Add HELM Lite run entries with extra LegalBench instructions

src/helm/benchmark/annotation/czech_bank_qa_annotator.py, src/helm/benchmark/metrics/czech_bank_qa_metrics.py, src/helm/benchmark/run_specs/experimental_run_specs.py, src/helm/benchmark/scenarios/czech_bank_qa_scenario.py, src/helm/benchmark/scenarios/test_czech_bank_qa_scenario.py, src/helm/benchmark/static/schema_czech_bank.yaml
This is a text-to-SQL task using the CzechBank dataset.
=> Add experimental CzechBankQA scenario

src/helm/benchmark/annotation/omni_math_annotator.py, src/helm/benchmark/run_specs/lite_run_specs.py, src/helm/benchmark/static/schema_lite_v2.yaml
- Fix incorrect package name in `OmniMathAnnotator`
- Fix incorrect metrics for `mmlu_pro`
- Fix incorrect prompts for GPQA (fixes bug in #3200)
- Fix incorrect metric names in schema
=> Fixes to HELM capabilities

helm-frontend/src/components/Landing/HomeLanding.tsx, helm-frontend/src/components/Landing/LiteLanding.tsx
Also synchronize partners list on the main home page and the Lite landing page.
=> Add IBM logo to partners

scripts/encrypt_scenario_states.py
Also make `--scenario` a required parameter.
=> Make encrypt_scenario_states script idempotent

src/helm/benchmark/annotation/live_qa_annotator.py
Fixes #3238, which involved a bad import that wasn't updated with the rest of the files.
=> Fix LiveQA import

helm-frontend/src/components/UserAgreement.tsx, helm-frontend/src/routes/Run.tsx, helm-frontend/src/services/getDisplayPredictionsByName.ts, helm-frontend/src/services/getDisplayRequestsByName.ts, helm-frontend/src/services/getInstances.ts, helm-frontend/src/utils/isScenarioEncrypted.ts
Refactor the code to move all scenario name matching to two central locations. Also add EWoK to the list of encrypted scenarios.
=> Refactor agreement frontend

src/helm/benchmark/annotation/omni_math_annotator.py, src/helm/benchmark/metrics/omni_math_metrics.py
Display every section (Equivalence Judgement, Student Final Answer, Justification) from the Omni-MATH annotator output in the frontend.
=> Return more information in Omni-MATH annotations

setup.cfg, src/helm/clients/audio_language/qwen2_audiolm_client.py
1. Fix wrong audio token number issue
2. Update dependency
=> Fix Qwen2-Audio-Instruct

helm-frontend/src/components/Landing/MedHELMLanding.tsx, helm-frontend/src/routes/Home.tsx, src/helm/benchmark/server.py
Also allow previewing a landing page in `helm-server` using the `--project` argument.
=> Add landing page for MedHELM

src/helm/benchmark/run_specs/enterprise_run_specs.py, src/helm/benchmark/scenarios/financial_phrasebank_scenario.py, src/helm/benchmark/static/schema_enterprise.yaml
A sentiment classification benchmark based on the dataset from Good Debt or Bad Debt - Detecting Semantic Orientations in Economic Texts [(Malo et al., 2013)](https://arxiv.org/abs/1307.5336).
=> Add Financial Phrasebank scenario

src/helm/clients/openai_client.py
Apparently #3319 didn't actually work, so hopefully this fixes things.
=> Handle Azure OpenAI content filter (second try)

src/helm/benchmark/run_specs/oab_exams_specs.py, src/helm/benchmark/scenarios/oab_exams_scenario.py, src/helm/benchmark/scenarios/test_oab_exams_scenario.py
The OAB Exam is a mandatory test for anyone who wants to practice law in Brazil. The exam is composed for an objective test with 80 multiple-choice questions covering all areas of Law and a written phase focused on a specific legal area (e.g., Civil, Criminal, Labor Law), where candidates must draft a legal document and answer four essay questions.
This dataset is composed by the exams that occured between 2010 and 2018.
=> Adding OAB Exams Scenario

src/helm/benchmark/adaptation/adapters/chat_adapter.py, src/helm/benchmark/annotation/wildbench_annotator.py, src/helm/benchmark/scenarios/scenario.py, src/helm/benchmark/scenarios/wildbench_scenario.py
This simplifies the WildBench implementation, which previously was adding a lot of data to `extra_data`.
=> Add messages to instance input and use this in WildBench

src/helm/benchmark/annotation/omni_math_annotator.py, src/helm/benchmark/metrics/omni_math_metrics.py
Fix how multiple annotators are displayed on the frontend.
=> Fix multiple annotators for OmniMATH

src/helm/benchmark/presentation/run_entries_audio.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/air_bench_foundation_scenario.py, src/helm/benchmark/static/schema_audio.yaml
3 subjects in this scenario: `music_instrument_classification`, `music_genera_recognition`, and `music_qa`.
=> Add Air-Bench Foundation audio scenario for the knowledge aspect

src/helm/benchmark/annotation/helpdesk_call_summarization_annotator.py, src/helm/benchmark/metrics/helpdesk_call_summarization_metrics.py, src/helm/benchmark/run_specs/call_center_run_specs.py, src/helm/benchmark/static/schema_call_center.yaml
Change the criteria and use multiple judges.
=> Revise annotator for helpdesk call summarization

docs/requirements.txt
=> Pin mkdocs-autorefs dependency version

src/helm/benchmark/metrics/gpt4_audio_critique_metrics.py, src/helm/benchmark/presentation/run_entries_audio.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/fleurs_fairness_scenario.py, src/helm/benchmark/scenarios/audio_language/librispeech_fairness_scenario.py, src/helm/benchmark/static/schema_audio.yaml
I added two fairness scenarios regarding different gender groups (male, female). 
Didn't find accent/race labels in either datasets, so just used different gender groups for these two tasks for now.
=> Add LibriSpeech and FLEURS gender fairness audio scenarios

src/helm/benchmark/static/schema_capabilities.yaml
=> Add metadata for MMLU-Pro

setup.cfg, src/helm/benchmark/scenarios/seahelm_scenario.py
This is required for the scenario to work. Also add `python-crfsuite` as a dependency for this scenario to resolve:
```
File "/path/to/helm/benchmark/metrics/seahelm_metrics.py", line 6, in <module>
from pythainlp.tokenize import word_tokenize
File "/path/to/pythainlp/__init__.py", line 41, in <module>
from pythainlp.soundex import soundex
File "/path/to/pythainlp/soundex/__init__.py", line 18, in <module>
from pythainlp.soundex.lk82 import lk82
File "/path/to/pythainlp/soundex/lk82.py", line 19, in <module>
from pythainlp.util import remove_tonemark
File "/path/to/pythainlp/util/__init__.py", line 124, in <module>
from pythainlp.util.pronounce import rhyme
File "/path/to/pythainlp/util/pronounce.py", line 12, in <module>
all_thai_words_dict = [
File …
```
=> Set trust_remote_code for TyDiQA

src/helm/benchmark/scenarios/mimic_bhc_scenario.py
Minor issue with function `ensure_directory_exits`, updated to ensure functionality.
=> updated data directory for minor bug resolution

src/helm/benchmark/scenarios/audio_language/air_bench_chat_scenario.py, src/helm/benchmark/scenarios/audio_language/air_bench_foundation_scenario.py, src/helm/benchmark/scenarios/audio_language/voxceleb2_scenario.py, src/helm/clients/audio_language/qwen2_audiolm_client.py
This is for fixing air-bench audio scenario, all previous commits about Qwen2 fixes have been merged.
=> Fix Air-Bench empty audio files

src/helm/benchmark/run_specs/medhelm_run_specs.py, src/helm/benchmark/scenarios/medhallu_scenario.py, src/helm/benchmark/static/schema_medhelm.yaml
Implementation of the Medhallu dataset that evaluates LLM capabilities for medical hallucinations
=> MedHELM-- Medhallu Dataset Implementation

src/helm/benchmark/run_specs/medhelm_run_specs.py, src/helm/benchmark/scenarios/medalign_scenario.py, src/helm/benchmark/scenarios/medalign_scenario_helper.py
Update MedAlign Scenario implementation to match files used in Redivis Data Release
=> Medalign Update

src/helm/benchmark/annotation/chw_care_plan_annotator.py
Update LLM judge for case where there is no ideal gold truth reference answer.
=> update noteextract llm judge

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Also remove deprecated `xai/grok-beta` model.
=> Change Grok 3 Beta access to limited

src/helm/benchmark/run_specs/medhelm_run_specs.py
update PubMedQA prompt to ground model output, as some reasoning model return multiple choice answer along with explanation
fyi @MiguelAFH
=> update PubmedQA Prompt to include grounding output

src/helm/benchmark/scenarios/medbullets_scenario.py, src/helm/benchmark/static/schema_medhelm.yaml, src/helm/config/model_deployments.yaml
This PR adds support to the new Llama4 Maverick and Scout, and GPT-4.1 models from StanfordHealthcare deployment.
=> Stanfordhealthcare Llama4 and GPT-4.1

src/helm/benchmark/static/schema_medhelm.yaml
Updating MedHELM schema to contain the 2 new benchmarks:
* shc_privacy_med
* shc_proxy_med
=> Updated medhelm schema

src/helm/benchmark/run_specs/medhelm_run_specs.py, src/helm/benchmark/scenarios/mtsamples_procedures_scenario.py
Renamed the MTSamples Procedures scenario to match the name in medhelm_run_spec.py
=> Medhelm mtsamples procedures

src/helm/config/model_deployments.yaml
Removed unused comments from model_deployments.yaml
=> Remove comments

src/helm/benchmark/metrics/aci_bench_metrics.py, src/helm/benchmark/metrics/chw_care_plan_metrics.py, src/helm/benchmark/metrics/dischargeme_metrics.py, src/helm/benchmark/metrics/llm_jury_metrics.py, src/helm/benchmark/metrics/med_dialog_metrics.py, src/helm/benchmark/metrics/medalign_metrics.py, src/helm/benchmark/metrics/medi_qa_metrics.py, src/helm/benchmark/metrics/medication_qa_metrics.py, src/helm/benchmark/metrics/mental_health_metrics.py, src/helm/benchmark/metrics/mimic_bhc_metrics.py, src/helm/benchmark/metrics/mimic_rrs_metrics.py, src/helm/benchmark/metrics/mtsamples_procedures_metrics.py, src/helm/benchmark/metrics/mtsamples_replicate_metrics.py, src/helm/benchmark/metrics/starr_patient_instructions_metrics.py
Updated jury code to have a common parent class, and updated the default score to 1 when no judges cannot evaluate the instances.
=> Medhelm jury

src/helm/benchmark/static/schema_medhelm.yaml
Renames the jury score metric from Accuracy to Jury Score
=> Rename jury metrics

src/helm/benchmark/metrics/vision_language/emd_utils.py
=> EMS metric fails when the inputs are identical homogenous images files

src/helm/benchmark/scenarios/truthful_qa_scenario.py
=> Pin download URL for TruthfulQA CSV file

docs/medhelm.md
Updated MedHELM documentation to reflect paper's language.
=> Update MedHELM documentation

helm-frontend/src/components/Landing/LongContextLanding.tsx, src/helm/benchmark/presentation/run_entries_long_context.conf, src/helm/benchmark/run_specs/long_context_run_specs.py, src/helm/benchmark/scenarios/infinite_bench_en_sum_scenario.py, src/helm/benchmark/scenarios/test_infinite_bench_en_sum_scenario.py, src/helm/benchmark/static/schema_long_context.yaml
This follows the naming conventions of the original paper.
=> Rename InfiniteBench Sum to InfiniteBench En.Sum

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
Also fix some minor file formatting issues
=> Add Granite 3.3 8B Instruct

setup.cfg
This is a test PR to see what happens when versions of packages are loosened. 
Using my own fork to test the CI workflow: https://github.com/Erotemic/helm/pull/1
=> Loosen versions

src/helm/benchmark/run_specs/speech_disorder_audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/ultra_suite_asr_classification.py, src/helm/benchmark/scenarios/audio_language/ultra_suite_asr_classification_scenario.py, src/helm/benchmark/scenarios/audio_language/ultra_suite_asr_transcription_scenario.py, src/helm/benchmark/scenarios/audio_language/ultra_suite_classification_scenario.py, src/helm/benchmark/scenarios/audio_language/ultra_suite_disorder_breakdown_scenario.py, src/helm/benchmark/scenarios/audio_language/ultra_suite_disorder_symptoms_scenario.py, src/helm/clients/audio_language/qwen2_5_omni_client.py, src/helm/clients/audio_language/qwen_omni/modeling_qwen2_5_omni.py, src/helm/clients/audio_language/qwen_omni/processing_qwen2_5_omni.py
In this PR, I have revised the implementations of scenarios in SLPHelm. The main modifications are about fixing typos in function names, links, EOS token; correcting the way to download data from HuggingFace; skipping data samples that do not have label.
I also fixed the Qwen-Omni client to make it work with the latest transformer library.
=> SLPHelm: Revise scenario implementation and Qwen-Omni client

src/helm/clients/huggingface_client.py
1. Set argument `add_generation_prompt = True` in `apply_chat_template`
=> Update apply_chat_template in huggingface_client.py

CITATION.bib
The citation was incorrectly removed by #3644.
=> Re-add citation

docs/medhelm.md
This PR is aimed to improve the documentation for viewing and reproducing results from MedHELM.
=> Medhelm download

src/helm/benchmark/presentation/summarize.py
If this flag is set, the schema will be auto-generated using the method in #3828, #3814 and #3813.
=> Add --auto-generate-schema flag to helm-summarize

src/helm/benchmark/presentation/summarize.py
=> Fix logic error for helm-summarize auto-generate-schema

docs/reproducing_leaderboards.md, src/helm/benchmark/presentation/run_entries_safety.conf, src/helm/benchmark/presentation/run_entries_safety_palmyra_x5.conf, src/helm/benchmark/presentation/run_entries_safety_reasoning.conf
Also rearrange some entries, and fix the priorities for the Safety leaderboard.
=> Add reproduction instructions for Capabilities leaderboard

src/helm/benchmark/adaptation/adapter_spec.py, src/helm/benchmark/metrics/evaluate_reference_metrics.py, src/helm/benchmark/presentation/run_display.py, src/helm/benchmark/run_specs/lite_run_specs.py
This is useful for extracting answers for MCQA scenarios.
=> Allow applying regular expression pattern before mapping output

.github/workflows/manage-python-cache.yml, .github/workflows/python-publish.yml, .github/workflows/test.yml, .github/workflows/test_scenarios.yml, .github/workflows/update-requirements.yml, .github/workflows/upgrade-requirements.yml, .readthedocs.yaml, constraints.txt, docs/developer_setup.md, docs/installation.md, pyproject.toml
Python 3.9 reaches end of life in October 2025.
=> Remove Python 3.9 support
