stanford-crfm/helm

src/helm/benchmark/presentation/summarize.py
The aggregate table seems to be the same as the last table (`subject=us_foreign_policy`) in https://crfm.stanford.edu/helm/v1.0/?group=mmlu.
=> Fix aggregate table (for MMLU and RAFT)

src/helm/benchmark/static/schema.yaml, src/helm/proxy/clients/ai21_client.py, src/helm/proxy/models.py
- AI21 added back unscaled logprobs as `raw_logprob`
- Added J1-Grande v2 beta model
Once this change is in, we need to clear all the cached entries for AI21 models and rerun everything.
Resolves #717
=> Use unscaled logprobs for AI21

src/helm/benchmark/adapter.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/test_adapter.py
This allows us to get different train examples across trials for open-ended generation tasks.
=> Shuffle labels that have the same number of `Instance`s that belong to them

src/helm/benchmark/metrics/copyright_metrics.py
The corner case is when the model does not generate anything at all. 
The precise failure mode is that given `s1 = np.array([])` and `s2 = np.array([0, 1])`, `s1 == s2` returns a bool, as opposed to the expected 1-D array. 
Resolves https://github.com/stanford-crfm/helm/issues/1197
=> Fix corner case; fixes #1197

README.md, docs/code.md, docs/index.md, docs/proxy-server.md, docs/requirements.txt, mkdocs.yml
- Add navigation to documentation
- Add index to Read the Docs
- Reuse part of the GitHub README.md for the Read the Docs index
- Link to Read the Docs from the GitHub README.md
- Add more links to README.md
- Minor writing fixes
=> Add index page and navigation to documentation

src/helm/benchmark/static/benchmarking.js
Previously, only the latest trial was displayed.
Fixes #1211
=> Display predictions from all trials

requirements-freeze.txt, requirements.txt, src/helm/benchmark/presentation/run_specs_chat_gpt.conf, src/helm/benchmark/run_expander.py, src/helm/benchmark/static/schema.yaml, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/chat_gpt_client.py, src/helm/proxy/clients/openai_client.py, src/helm/proxy/models.py, src/helm/proxy/retry.py
Uses the https://github.com/acheong08/ChatGPT library to send requests to ChatGPT.
Related #1218
=> Support ChatGPT

src/helm/benchmark/runner.py
Output two additional files. Instead of using `scenario_state_slim.json` and `per_instance_stats_slim.json`, the frontend should use `instances.json` (`List[Instance]`) and `prediction.json` (`List[SlimPrediction]`) instead.
Addresses #1185
Addresses #1236
=> Output instances.json and predictions.json from helm-run

src/helm/benchmark/adapter.py, src/helm/benchmark/runner.py
`scenario_state_slim.json` is no longer needed since we're making the JSON smaller in #1185.
=> Do not output scenario_state_slim.json

src/helm/benchmark/runner.py
This fixes `helm-run --dry-run` breaking with `AssertionError` and `assert request_state.result is not None`
=> Skip instances with no results in prediction.json

src/helm/benchmark/scenarios/bbq_scenario.py
Resolves https://github.com/stanford-crfm/helm/issues/1235
=> Fix BBQ: `AttributeError: 'BBQScenario' object has no attribute 'definition_path'`

src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/static/schema.yaml
Added a "targeted evaluation" for calibration where we display additional metrics for some scenarios.
In terms of infrastructure:
- Added logic to handle the `_detailed` metric groups (e.g., `calibration_detailed`).
- Allowed `RunGroup`s to specify `metric_groups` that override those of subgroups. This allows us to use the detailed version of a metric group without needing to specify scenario groups again.
- Orthogonal: Added a `subgroup_metric_groups_hidden` list that allows us to hide some metric groups (e.g., since we run some ablations without perturbations, we hide Robustness there).
In terms of annotation in `schema.yaml`, I was not sure about the following (cc @AnanyaKumar @rishibommasani)
- Which calibration metrics we want, see `calibration_detailed`
- Which scenarios we want to …
=> Add detailed calibration metrics

src/helm/benchmark/static/schema.yaml, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
- Switched to the [new Together inference endpoint](https://docs.together.xyz/en/api/) (resolves #1230)
- Added GPT-JT (resolves #1208)
=> Added GPT-JT and switched to the new Together inference endpoint

src/helm/benchmark/presentation/present.py, src/helm/benchmark/presentation/summarize.py
This avoids `run_specs.json` getting overwritten repeatedly if `helm-run` is run multiple times with different run specs.
Fixes #1222.
=> Write run_specs.json in helm-summarize instead of helm-run

src/helm/benchmark/static/benchmarking.js
Fixes a bug in #1287 where by default, the sort column values would be sorted in descending order. This respects the sort order of the column instead.
Addresses #832
This change was already made on the live website as a hotfix during the v0.2.0 release, so this is a backport.
=> Respect sort order of default sort column

requirements-freeze.txt, requirements.txt
The current version transitively depends on the `tls-client-for-chatGPT` package, which no longer exists.
=> Upgrade revChatGPT dependency

src/helm/benchmark/presentation/run_display.py
Dataclasses are more readable and maintainable. Partially reverts #1256, which was made for performance reasons. A subsequent PR will reimplement deserialization in a more performant way.
=> Use dataclasses instead of JSON in run_display

src/helm/benchmark/metrics/summarization_metrics.py
This lazily downloads en_core_web_sm when SummarizationMetric is instantiated, rather than eagerly when summarization_metrics is important. This avoid unnecessarily downloading en_core_web_sm when unneeded. This avoids issues when the Python libraries directory is read-only.
=> Only download en_core_web_sm when needed

MANIFEST.in
This is required for `misspelling_perturbation`
=> Include correct_to_misspelling.json in package

pre-commit.sh
This fixes protobuf installation errors.
=> Bump protobuf version in pre-commit.sh to match requirements-freeze.txt

src/helm/proxy/clients/huggingface_client.py
This fixes a bug that causes cache misses in HuggingFaceClient even when the exact same request is sent multiple times.
This is because `raw_request`, which is [used for the cache key](https://github.com/stanford-crfm/helm/blob/53b163c640a55d442cb3684567513e0132618ed5/src/helm/proxy/clients/huggingface_client.py#L157), is mutated by [the method called by the cache](https://github.com/stanford-crfm/helm/blob/53b163c640a55d442cb3684567513e0132618ed5/src/helm/proxy/clients/huggingface_client.py#L33), causing the cache to store the result under a mutated key rather than the original key provided by the caller..
=> Don't mutate key of HuggingFaceClient cache

src/helm/benchmark/__init__.py, src/helm/benchmark/metrics/classification_metrics.py, src/helm/benchmark/metrics/test_classification_metrics.py, src/helm/benchmark/run_specs.py
Right now this only works for the generation adapter. Also F1 to `raft`, `civil_comments` and `imdb`.
Fixes #1313
=> Add classification metrics

src/helm/benchmark/scenarios/the_pile_scenario.py
The url of the publicly hosted the pile dataset was changed. Update it in the scenario definition to avoid errors in scenario loading.
Fixes #1376
=> Update the url of the pile dataset

src/helm/proxy/clients/together_client.py
The Together model name format is now `model-size-framework`, so H3 is `h3-2.7b-h3`.
=> Update Together model name for H3

src/helm/benchmark/run.py, src/helm/benchmark/runner.py
- `--exit-on-error` was broken by #1302
- `--skip-completed-runs` is useful for re-running `helm-run` on the same `run_specs.conf` if some runs fail, without having to create a new `run_specs.conf` with only the failing runs.
=> Fix --exit-on-error not working and add --skip-completed-runs

requirements.txt, setup.py, src/helm/benchmark/presentation/create_plots.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/presentation/test_create_plots.py
Adding all the code that we used to produce the HELM paper plots. 
Created a new entry point at `helm-create-plots` which takes the same arguments as `summarize` (benchmark_output and suite), reads the group `.json` files produces by `summarize`, and saves the plots at `.../runs/{suite}/plots/`.
Resolves #682 .
=> Adding code to reproduce paper plots

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/cohere_window_service.py, src/helm/benchmark/window_services/test_cohere_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/models.py
- Use Command beta instead of Command nightly
- Use sequence length of 2020 for Command models
- Mark Command as a full functionality model
=> Changes to Cohere Command model

src/helm/benchmark/adaptation/adapters/in_context_learning_adapter.py, src/helm/benchmark/metrics/classification_metrics.py, src/helm/benchmark/metrics/test_classification_metrics.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/lex_glue_scenario.py, src/helm/benchmark/scenarios/lextreme_scenario.py, src/helm/benchmark/scenarios/scenario.py, src/helm/benchmark/static/schema.yaml
This is a WIP for adding population level classification metrics for multilabel text classification tasks. Any Feedback is welcome, especially for testing it.
=> Add multilabel classification metrics

src/helm/benchmark/runner.py
Currently, `helm-run` returns exit code 0 when runs fail if `--exit-on-error` is not set.
=> Return non-zero error code when runs fail

docs/huggingface_models.md, src/helm/benchmark/run.py, src/helm/benchmark/window_services/huggingface_window_service.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/huggingface_model_registry.py, src/helm/proxy/clients/test_huggingface_model_registry.py
- Previously, it always used the main revision; now it actually uses the correct revision
- Also changes Hugging Face revision syntax to use @ instead of #; this makes it consistent with [pip VCS syntax](https://pip.pypa.io/en/stable/topics/vcs-support/)
- The HELM model name now includes the @ suffix as well, rather than truncating it
Addresses #1103
=> Fix using revisions with Hugging Face Model Hub

.github/workflows/python-publish.yml
This workflow will upload a Python Package using Twine when a release is created.
Fixes #1349
=> Add GitHub action for publishing Python package

src/helm/proxy/services/server_service.py
This only instantiates PerspectiveAPIClient when toxicity metrics are used, which stops an error form being raised if the user is not using toxicity metrics and the Perspective API key is not provided.
Addresses #1417
=> Lazily instantiate PerspectiveAPIClient

src/helm/benchmark/adaptation/adapters/in_context_learning_adapter.py, src/helm/benchmark/window_services/local_window_service.py
=> Fix corner cases in LocalWindowService truncation and In-context Adapter

src/helm/benchmark/scenarios/lextreme_scenario.py, src/helm/common/object_spec.py
~~Revise `__import__` with importlib. `importlib` should be preferred over `__import__`. You may test the change via the following code:~~ Noticed that the change cannot handle `helm.benchmark.basic_metric` so I reverted the change.
```python
from helm.common.object_spec import ObjectSpec, create_object
obj_spec = ObjectSpec(class_name="helm.benchmark.scenarios.lextreme_scenario.LEXTREMEScenario", args={"subset": "multi_eurlex_level_2"})
scenario = create_object(obj_spec)
```
=> [Bugfix] Fix lextreme

docs/tutorial.md
The tutorial initially said that the `run_specs.json` for all runs (e.g. `benchmark_output/runs/v1/run_specs.json` was created by `helm-run`, but it seems to only be created once running `helm-summarize` for the given suite.
=> clarify: overall helm-summarize creates run_specs.json

scripts/helm-run-all.sh, src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
This PR adds support for OPT 1.3B and 6.7B models when served via Together
=> add opt 1.3b and 6.7b models

.github/workflows/test.yml, src/helm/proxy/services/test_remote_service.py
Instead of hardcoding the relative path to `crfm-proxy-server`, instead rely on it being directly invokable via `PATH`. This fixes the test for cases where `crfm-proxy-server` is not located under `venv/bin` e.g. inside Conda.
=> Use crfm-proxy-server on PATH in test_remote_service

scripts/estimate_cost.py, src/helm/benchmark/__init__.py, src/helm/benchmark/metrics/dry_run_metrics.py, src/helm/benchmark/metrics/estimated_tokens_metric.py, src/helm/benchmark/runner.py
Usage: `python3 scripts/estimate_cost.py <Path to run suite>`
Also, renamed `TokensMetric` to `DryRunMetric` since we only need to compute those metrics during a dry run.
=> Estimate costs for a given run suite

src/helm/benchmark/scenarios/imdb_scenario.py, src/helm/benchmark/scenarios/imdb_scenario_pinned_file_order.py
The previous official HELM runs used the arbitrary file order produced by os.listdir() and did not sort the files, so future runs must use the same file order in order to sample the same instances to reproduce the official HELM runs.
Addresses #1352
=> Pin file order for imdb_scenario

src/helm/benchmark/run.py
This should allow running `helm-summarize` and `helm-server` even if the run fails which would be useful for debugging.
=> Symlinks to latest before benchmarking

src/helm/benchmark/window_services/wider_ai21_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/models.py
AI21 has recommended using a sequence length of 6000 tokens to avoid OOMs.
=> Reduce Jurassic-2 Jumbo sequence length to 6000

src/helm/benchmark/run.py, src/helm/benchmark/runner.py
For #1489
Right now, all information is cached/saved by helm-run after running models on scenarios (i.e. until basically the whole run has finished). This change allows for users to specify flags to generate the instances for that scenario _only_ without evaluating the model and/or to read instances from an existing file rather than redownloading the dataset and regenerating those instances.
This functionality is meant to be used to make it more feasible to run HELM on Codalab.
=> Allow instances to be pre-downloaded and then read from files.

src/helm/benchmark/presentation/summarize.py
Running `helm_summarize` was raising an exception when running `helm-summarize.
```
Traceback (most recent call last):
File "/Users/csris/miniconda3/envs/crfm-helm/bin/helm-summarize", line 8, in <module>
sys.exit(main())
File "/Users/csris/src/github.com/stanford-crfm/helm/src/helm/common/hierarchical_logger.py", line 104, in wrapper
return fn(*args, **kwargs)
File "/Users/csris/src/github.com/stanford-crfm/helm/src/helm/benchmark/presentation/summarize.py", line 1003, in main
symlink_latest()
TypeError: symlink_latest() missing 2 required positional arguments: 'output_path' and 'suite'
```
After this fix, `helm-summarize` will create a `latest` symlink that points at the the `output_path` and `suite` passed in the command-line arguments.
This was introduced by commit …
=> Create a `latest` symlink to the given results

src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/megatron_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/megatron_client.py, src/helm/proxy/models.py
These changes add support for evaluating GPT2 models with a [Megatron-LM server](https://github.com/NVIDIA/Megatron-LM#gpt-text-generation). The client currently assumes that the server is running at `localhost:5000`.
=> Add support GPT2 models decoded via Megatron-LM server

src/helm/benchmark/run_expander.py, src/helm/benchmark/static/schema.yaml, src/helm/benchmark/window_services/starcoder_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/proxy/models.py
=> Rename `large-model` to official name `starcoder`

src/helm/benchmark/executor.py, src/helm/common/request.py, src/helm/proxy/clients/anthropic_client.py, src/helm/proxy/clients/palmyra_client.py, src/helm/proxy/retry.py
Added ErrorFlags to handle errors that are consistent but not fatal.
This is used for Palmyra's content filtering.
For now handles #1520.
=> Addition of Error Flags: retriable and fatal

src/helm/benchmark/adaptation/adapters/language_modeling_adapter.py, src/helm/benchmark/window_services/anthropic_window_service.py, src/helm/benchmark/window_services/palmyra_window_service.py, src/helm/benchmark/window_services/window_service.py
PR to solve #1520 and #1531.
Megatron and Anthropic and Writer have a limit on prompt length + max_tokens that was not handled in HELM
=> Add a prompt length + max_tokens limit and add it to Anthropic and Writer

src/helm/benchmark/scenarios/code_scenario.py
Some versions of Python have a configurable maximum number of digits of integers that can be parsed from strings. This limit also applies to parsing integers in JSON. The default limit is 4300 digits.
Reading APPS instances will fail with the default limit because the APPS dataset contains very large integers.
The `sys.set_int_max_str_digits()` method can be used to increase the limit. This method exists if and only if the version of Python has a default limit.
See: https://docs.python.org/3/library/stdtypes.html#int-max-str-digits
Fixes #1381.
=> Add sys.set_in_max_str_digits() to APPS

docs/huggingface_models.md, requirements-freeze.txt, requirements.txt, src/helm/benchmark/run.py, src/helm/benchmark/slurm_jobs.py, src/helm/benchmark/slurm_runner.py
If the `--use-slurm-runner` flag is set in `helm-run`, each RunSpec will be run in a separate worker Slurm job. Currently only works on the Stanford NLP cluster.
=> Add `--use-slurm-runner` flag to `helm-run`

src/helm/proxy/clients/anthropic_client.py
Just discovered a bug in `antrhopic_client.py`. The catching of the exception was not working. This is a small fix.
=> Fix response undefined in catching error of Anthropic

src/helm/common/request.py, src/helm/proxy/clients/openai_client.py
To answer #1503
`Request` now supports `messages` that override `prompt` for OpenAI chat models.
=> Support for request.messages for chat models in OpenAI

src/helm/common/hierarchical_logger.py, src/helm/proxy/retry.py
Solving #1471
I tried also to handle KeyboardInterrupt but is is not super consistent.
=> Handle retry attempts better: print exception and stack trace

src/helm/benchmark/runner.py, src/helm/benchmark/slurm_runner.py
Previously, if `--skip-completed-runs` was set, `SlurmRunner` would submit a Slurm job for each completed run. The Slurm job would then immediately exit without doing any work because the run was completed.
Now, if `--skip-completed-runs` was set, `SlurmRunner` will skip creating a Slurm job for 
Additionally, `SlurmRunner` will write the list of skipped RunSpec names to `skipped_runs.json`, even if the list is empty. This is for the convenience of downstream status monitoring tools.
=> Make `SlurmRunner` skip creating Slurm jobs for completed runs

src/helm/benchmark/run.py
Previously, `helm-run` would fail with `FileNotFoundError: [Errno 2] No such file or directory: 'proxy_api_key.txt'` if both `--local` and `--server-url` are unset, and `proxy_api_key.txt` does not exist. The intended behavior is to run locally and not require `proxy_api_key.txt`  to exist.
=> Fix `No such file or directory: 'proxy_api_key.txt'` when `--local` is not set

src/helm/benchmark/slurm_jobs.py, src/helm/benchmark/slurm_runner.py
We need to limit the number of concurrent currently-running Slurm jobs:
- This prevents `SlurmRunner` from consuming the user's entire Slurm quota, which blocks the user from running any additional Slurm jobs.
- This gives us a crude way of rate limiting requests to APIs.
=> Add limit on number of concurrent worker Slurm jobs

requirements-freeze.txt, requirements.txt, scripts/scale/create_and_setup_project.py, scripts/scale/finalize_batch.py, scripts/scale/scale_utils.py, setup.cfg, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/critique_client.py
This is a draft PR for Scale AI.
=> Scale AI integration

src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/critique_client.py, src/helm/proxy/clients/mechanical_turk_critique_importer.py, src/helm/proxy/clients/surge_ai_critique_client.py
- Only require a Scale project (rather than a Scale batch) to be specified, which simplifies the user workflow
- Rename special field key for image attachments
- Disable self-labeling
- Move `SurgeAICritiqueClient` its own module
Addresses #1614
=> ScaleCritiqueClient improvements

src/helm/proxy/clients/together_client.py
Fixes for running LLaMA and other models:
- Use async requests for more models
- Use full-precision models instead of half-precision models by adding a suffix
- Display a more useful error message for error responses
=> Together client fixes

src/helm/benchmark/presentation/run_display.py, src/helm/benchmark/presentation/summarize.py
This significantly speeds up `helm-summarize` for the use case where we run `helm-summarize` on a run suite with some existing runs, add some runs using `helm-run`, and then run `helm-summarize` over the suite again. In this case, we skip re-computing the display JSON for the existing runs.
=> Skip completed display JSON

src/helm/benchmark/static/benchmarking.css, src/helm/benchmark/static/benchmarking.js
Set white-space to "pre-wrap" for predictions so that newlines will be preserved.
=> Fix prediction rendering

.github/workflows/test.yml, requirements.txt, setup.cfg
Fixes issue #1616.
This PR does the following:
1) Fix an error that would prevent users from being able to correctly install new releases of crfm-helm
2) Update Github Actions so that install errors are tested for.
3) Update setup.cfg so that `pip install -e .` works again. (It was missing `simple-slurm` and an update to the `tokenizers` version.)
Note on 1): The issue found in #1616 is documented on spaCy's repo [here](https://github.com/explosion/spaCy/issues/12659). In short, they have a temporary workaround to use `typing-extensions<4.6.0`, which is what I use here.
=> Fix install error from latest version of repo

src/helm/benchmark/__init__.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/koala_scenario.py
The test dataset used by the Koala team to evaluate instruction-following models.
https://bair.berkeley.edu/blog/2023/04/03/koala/
To run GPT-4 on the scenario, use: `venv/bin/helm-run -r koala:model=openai/gpt-4-0314 -m <max_eval_instances> -t <num_trials> --suite <suite_id>`
Some example `scenario_states`:
**Example 1:**
**Prompt**: "In order to launch a token for a Defi project, I want to sell some tokens privately to early investors and then add it to a launchpad. let me know what can I do with my smart contract? Should I create a presale contract separate from main contract?"
**GPT-4 Response**: "Yes, it's a good idea to create a separate presale contract for your private sale before launching your token on a launchpad. This allows you to manage the private sale and allocate tokens …
=> Koala scenario

src/helm/proxy/clients/huggingface_client.py
In huggingface, `tokenizer.encode` and `tokenizer.convert_ids_to_tokens` are not inverses -- you have to additionally call `tokenizer.convert_tokens_to_string` to get the original token back. This was causing some problems with [`truncate_sequence`](https://github.com/stanford-crfm/helm/blob/356a6b25b8b4bb46b7fae9f0d1db07345db300a4/src/helm/proxy/clients/client.py#L57) since this function expects the last token(s) to have text that starts with one of the `stop_sequences`.
=> Fix HF token decoding

src/helm/benchmark/slurm_runner.py
Previously, `SlurmRunner` would fail if there were spaces in the run spec name, or in a directory path.
Also set `mail_type` to `FAIL` because `END` is excessively spammy.
=> Escape shell arguments in `SlurmRunner`

src/helm/benchmark/presentation/schema.py, src/helm/benchmark/static/schema.yaml
- Make human eval match all splits
- Remove `copyright_human`, which does not exist in the runs
- Move FID and Inception Score out of fidelity into its own subgroup
- Apply FID and Inception Score to `coco_fid` only and remove it from `coco` and `cub200`
- Make FID and Inception Score match all splits
- Change incorrect `kernel_inception_distance_mean` name to `kernel_inception_distance`
=> Fix schema for human eval and inception

requirements-freeze.txt, setup.cfg, src/helm/proxy/clients/together_client.py
- Alias `redpajama-incite-base-3b-v1` to `togethercomputer/RedPajama-INCITE-Base-3B-v1`
- Fix retrying docstring
- Upgrade retrying to 1.3.4, which is required for `wait_incrementing_*`
=> Fix RedPajama and retries in TogetherClient

src/helm/benchmark/slurm_runner.py
Jobs in terminal states on Slurm get garbage collected after a day, which causes SlurmRunner to crash when if it attempts to fetch the status of a job that was garbage collected.
=> SlurmRunner should not fetch statuses of jobs in terminal states

src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/perspective_api_client.py, src/helm/proxy/clients/toxicity_classifier_client.py, src/helm/proxy/services/server_service.py
- Allows clients to use optional dependencies.
- Significantly speeds up `AutoClient` import time from several seconds to <100ms.
- Significantly speeds up `helm-run` initialization time, which was dominated by `AutoClient` import time.
Addresses #1327
=> Lazily import client modules in AutoClient

src/helm/benchmark/metrics/summarization_critique_metrics.py, src/helm/proxy/clients/scale_critique_client.py
Scale's consensus function requires the value of each option to be "a number".
=> Change option values to integers (indices) when using Scale critique

src/helm/proxy/retry.py
8 retries is too high and causes too long of a wait when there are permanent failures.
=> Reduce number of request retries from 8 to 5

src/helm/common/cache.py
Previously, we needed to manually create the index through `mongosh`. If a new organisation cache was used in HELM without doing so, then the cache would be very slow.
This change creates the index if it does not exist, eliminating the need to manually create the index, and avoiding accidentally using slow caches.
=> Ensure indexes exist on MongoDB collections

scripts/compute_request_limits.py
This script is used to find the limits required by the window service
=> Script to figure out model sequence length limits

src/helm/benchmark/presentation/run_specs.conf
Based on Percy's request, I added the Spider text-to-SQL task, available through BIG-bench. I checked that it runs.
=> add spider (from big-bench)

src/helm/proxy/clients/palmyra_client.py
Currently, `PalmyraClient` is caching failing requests, causing future requests to also fail. This prevents failures from being cached, except for content moderation failures, which should be cached.
=> Fix error caching with PalmyraClient

src/helm/benchmark/metrics/statistic.py
`helm-summarize` crashes on the current run due to NaNs.
=> Handle NaN in Stat.bare_str()

src/helm/benchmark/presentation/summarize.py
This significantly speeds up JSON deserialization, saving about about half an hour when running `helm-summarize` in production.
=> Use cattrs instead of dacite for summarize

src/helm/benchmark/metrics/basic_metrics.py
There may be no request time in some special cases e.g. the API has a content filter that causes a null generation to be returned. If there is no request time, skip computing stats for the request in `compute_efficiency_metrics`.
=> Allow results without request time in `compute_efficiency_metrics`

src/helm/benchmark/static/schema.yaml
Fix markdown in schema description for YaLM
* Remove `From` from link as this prevented markdown parser from converting to HTML link
=> Fix markdown in schema for YaLM

src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/heim/benchmarking.js
This displays the human metrics on the frontend for HEIM.
Correct target branch this time.
=> Display metric names with perturbation __all__

src/helm/proxy/models.py
Together stopped giving us logprobs as default for the largest size of LLaMA and all sizes of Llama-2.
=> Mark Together Llama models as limited functionality

setup.cfg
This allows users to use PyTorch 2.
PyTorch 2 is at the users own risk; this has not been thoroughly tested by HELM maintainers yet.
Addresses #1745
=> Widen PyTorch dependency version to allow PyTorch 2

src/helm/benchmark/metrics/summarization_critique_metrics.py, src/helm/proxy/clients/mechanical_turk_critique_exporter.py, src/helm/proxy/clients/mechanical_turk_critique_importer.py, src/helm/proxy/clients/mechanical_turk_utils.py
Escapes emoji for Mechanical Turk exporting and importing because Mechanical Turk does not support unescaped emoji. (Error message: "Unsupported characters found")
Also updates the layout to improve whitespace formatting.
=> Support emoji for MTurk import / export

src/helm/benchmark/scenarios/scenario.py, src/helm/benchmark/scenarios/test_scenario.py
Fix GitHub source link in scenario.json
If the file system does not have `/src/` in the path, the local file path of the system performing the build will be output in the `definition_path` field of `scenario.json` instead of the GitHub link. This is because there is a regex substitution that relies on the existence of `/src/`
* Update logic to walk back towards the path root until encountering a `helm` directory as opposed to a regex looking for `src`.
_Note:_ Future potential issue could be if a new `helm` directory was created above `/src/helm/`
=> Fix GitHub source link in scenario.json

setup.cfg
This causes a "Invalid URI" error pushing to PyPI.
=> Remove incorrect quotes from setup.cfg

src/helm/benchmark/static/schema.yaml, src/helm/proxy/models.py
- Llama 2 is spelled as such, not as LLaMA-2.
- All new Together models don't provide logprobs (Pythia, LLaMA, Llama 2)
=> Fix metadata for Llama 2 and other Together models

src/helm/proxy/clients/together_client.py
Together sometimes does not return `finish_reason`.
=> Make `finish_reason` optional in TogetherClient responses

src/helm/benchmark/metrics/metric.py, src/helm/benchmark/runner.py
Drop any instance stats that contain `NaN`, because Python's stdlib `json.dumps()` will produce invalid JSON when serializing a `NaN`.
See:
- https://bugs.python.org/issue40633
- https://docs.python.org/3/library/json.html#infinite-and-nan-number-values
Addresses #1765
=> Remove stats with NaN values

scripts/data_overlap/light_scenario.py, src/helm/benchmark/data_overlap/light_scenario.py, src/helm/benchmark/presentation/run_display.py, src/helm/benchmark/presentation/summarize.py
This PR depends on https://github.com/stanford-crfm/helm/pull/1747
Instead of taking num_instances and overlapping_ids as all the instances for a given scenario, we get the subset of scenarios in a helm run via scenario_state, and take the intersection of these and the overlapping scenarios
=> Filter overlap ids based on helm subset

src/helm/benchmark/presentation/summarize.py
Currently, `helm-summarize` produces the following error if the `data_overlap` directory doesn't exist: `FileNotFoundError: [Errno 2] No such file or directory: 'benchmark_output/runs/v1/data_overlap/scenario_spec_instance_ids_1000.json'`. This was introduced by #1747
=> Fix helm-summarize error if data_overlap directory does not exist

src/helm/benchmark/run_specs.py
`boolq`, `raft`, and `civil_comments` are all MCQA or classification scenarios. I removed `ToxicityMetric` because it is highly unlikely for toxic generations to be produced giving a constrained set of expected answers. This is validated by the [zero or near-zero toxic fraction](https://crfm.stanford.edu/helm/v0.2.3/?group=core_scenarios#Toxicity) of all models on these scenarios.
=> Remove ToxicityMetric from boolq, raft, and civil_comments

src/helm/benchmark/metrics/basic_metrics.py
For models without logprobs, we currently treat the probability of each token to be 1.0, which means that the ECE 10-bin is trivially (1 - accuracy). We should skip computing calibration metrics for these models instead.
=> Don't compute calibration metrics for models without logprobs

src/helm/benchmark/adaptation/adapter_spec.py, src/helm/benchmark/adaptation/adapters/in_context_learning_adapter.py, src/helm/benchmark/adaptation/adapters/multiple_choice_joint_adapter.py, src/helm/benchmark/adaptation/adapters/test_generation_adapter.py, src/helm/benchmark/adaptation/adapters/test_multiple_choice_joint_adapter.py, src/helm/benchmark/run_specs.py
If an instance has multiple correct instances, previously the adapter uses all the correct references concatenated together as the output for in context learning examples. 
After this change:
- If `AdapterSpec.multi_label` is true, the adapter uses all the correct references concatenated together as the output for in context learning examples.
- Otherwise, the adapter only uses the first correct reference.
=> Fix adaptation for multiple references

src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/huggingface_tokenizer.py
This removes some unnecessary code that checks that Hugging Face hub names are "known".
This is required but not sufficient to use Hugging Face with `ModelDeploymentRegistry`
=> Allow HuggingFaceClient and HuggingFaceTokenizer to be used on any name

src/helm/benchmark/presentation/run_display.py, src/helm/benchmark/presentation/summarize.py
This should produce a >10x decrease in runtime for `read_scenario_spec_instance_ids()`
=> Read instances.json instead of scenario_state.json in read_scenario_spec_instance_ids()

src/helm/proxy/clients/http_model_client.py
A longer timeout may be needed for requests with thousands of tokens, which take a longer time to process.
Addresses #1790
=> Increase NeurIPS challenge HTTP client timeout to 5 minutes

src/helm/benchmark/metrics/basic_metrics.py
This fixes a bug that skipped computing calibration metrics for all runs due to incorrect metric name matching.
=> Fix missing calibration metrics

src/helm/benchmark/static/schema.yaml, src/helm/proxy/clients/test_together_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/models.py
This implements two workarounds suggested by Together for specific Together models:
- Add the EOS token as an extra stop sequence. This prevents the model from incorrectly returning the EOS token as part of the generation.
- Set the `details` field to `true`. This indicates that Together should return logprobs for models that do not return logprobs by default.
=> Rewrite requests to Together

scripts/compute_request_limits.py
For some reason, mypy is failing to correctly infer these types when I run mypy locally, but GitHub Action's mypy does not have this issue. I spent a while investigating and couldn't figure out what the difference was between the two environments, so I instead added type annotations to make my local mypy happy.
For the record, my local mypy was failing with:
```
scripts/compute_request_limits.py:100: error: Self? has no attribute "update"
scripts/compute_request_limits.py:154: error: Self? has no attribute "update"
```
=> Annotate tqdm type in compute_request_limits

src/helm/benchmark/run.py, src/helm/benchmark/run_expander.py
This can be used to overriding the number of eval instances at the run level e.g. `mmlu:subject=anatomy,model=simple/model1,max_eval_instances=20`
=> Add MaxEvalInstancesRunExpander

src/helm/proxy/clients/http_model_client.py
goal is to support a workflow like `HELM_HTTP_MODEL_BASE_URL=… helm-run …` so we can run multiples processes of helm run concurrently each on different ports
if there's an easier way to do this lmk but iirc for timeout for example we had to update helm source code
=> multiprocess http eval

src/helm/proxy/clients/http_model_client.py
Current default runs will encounter error if user do not indicate the key.
=> prevent error with default localhost setting

.github/workflows/python-publish.yml
Trusted Publishing is the new recommended and more secure way of publishing Python packages to PyPI.
This follows the tutorials on [python.org](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#configuring-trusted-publishing), [pypi.org](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) and [pypi-publish](https://github.com/marketplace/actions/pypi-publish#trusted-publishing).
=> Use Trusted Publishing to publish from GitHub Actions to PyPI

src/helm/benchmark/presentation/summarize.py
Calibration metrics for LLaMA and Llama 2 may be incorret. See #1847 for a longer explanation.
=> Temporarily remove calibration metrics from LLaMA and Llama 2

src/helm/benchmark/augmentations/cleva_perturbation.py, src/helm/common/codec.py
This is required for `helm-summarize` to be able to deserialize CLEVA `PerturbationDescription` subclasses correctly.
=> JSON deserialization for CLEVA perturbation descriptions

scripts/data_overlap/load_documents.py, setup.cfg, src/helm/benchmark/augmentations/contrast_sets_perturbation.py, src/helm/benchmark/augmentations/gender_perturbation.py, src/helm/benchmark/augmentations/person_name_perturbation.py, src/helm/benchmark/run.py, src/helm/benchmark/run_expander.py, src/helm/common/cache.py, src/helm/proxy/clients/ai21_client.py, src/helm/proxy/services/service.py
Also remove `ReplaceRunSpecValueRunExpander`, which is unused (the correct class is `ReplaceValueRunExpander`)
=> Fix typing errors detected by a newer version of mypy

src/helm/benchmark/model_deployment_registry.py, src/helm/benchmark/model_metadata_registry.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/tokenizer_config_registry.py, src/helm/benchmark/window_services/default_window_service.py, src/helm/benchmark/window_services/huggingface_window_service.py, src/helm/benchmark/window_services/llama_window_service.py, src/helm/benchmark/window_services/window_service_factory.py, src/helm/common/object_spec.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/http_model_client.py, src/helm/proxy/services/server_service.py
This supports running a model for NeurIPS Efficiency Challenge with a user-configurable model name, HTTP service URL, window service and tokenizer.
-----
For models that use a built-in `WindowService`:
`prod_env/model_deployments.yaml`:
```
model_deployments:
- name: neurips/my-pythia-model
window_service_spec:
class_name: "helm.benchmark.window_services.gptneox_window_service.GPTNeoXWindowService"
args: {}
client_spec:
class_name: "helm.proxy.clients.http_model_client.HTTPModelClient"
args: {
base_url: "http://localhost:2345"
}
```
The following models are supported, with corresponding `class_name` inside `window_service_spec`:
- LLaMA: `helm.benchmark.window_services.llama_window_service.LlamaWindowService`
- Llama 2: `helm.benchmark.window_services.llama_window_service.Llama2WindowServi …
=> Configurable models for NeurIPS Efficiency Challenge

src/helm/proxy/clients/model_critique_client.py
Quick fix to support Claude in `CritiqueModel`.
I say quick but at the same time I don't think there is a super clean way to handle this for now. We could add the notion of prefix and suffix to the `CritiqueModelClient` but this would still require this logic somewhere. I think this should be handled further down the line by our refactor which would add automatically the correct prefix and suffix for a model.
=> Added special case to support Anthropic Critique

.github/workflows/test.yml, install-dev.sh, setup.cfg, src/helm/proxy/clients/ice_tokenizer_client.py, src/helm/proxy/clients/test_ice_tokenizer_client.py
Previously, we manually installed `pip install --no-binary=protobuf protobuf==3.20.2`. This change allows protobuf to be installed manually and removes the constraint to the specific version. This allows users to use binary protobufs and to use version >=4 of the protobuf package (which was causing version conflicts in downstream projects such as train-test overlap).
Changes:
- Make icetk an optional dependency
- Remove protobuf from direct dependencies because HELM does not use it directly. It is an transitive dependency via icetk.
- Remove manual installation of protobuf
- Re-enable icetk tests
Fixes #1613
=> Clean up icetk and protobuf dependencies

src/helm/proxy/clients/test_huggingface_tokenizer.py
Fixes the test breakage with the following output:
```
E           OSError: google/t5-11b is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
E           If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
```
=> Fix test_huggingface_tokenizer

src/helm/common/optional_dependencies.py
When installing helm[all] it displays the message with wrong name. This PR does a small fix of that.
Fixes issue #1894
=> Fixed typo in optional dependencies message

src/helm/proxy/clients/huggingface_client.py
I use StoppingCriteria instead of eos_token_id when total number of tokens in each stop word is more than 1, which would allow helm to use stop sequences of multiple tokens.
It should fix #1501 and #1782 .
Notice: multiple tokens in stop word may lead to reduced efficiency
=> Fix: Total number of tokens in each stop word should be 1

.pre-commit-config.yaml
Fixes this error when running `pre-commit`:
```
==> At Hook(id='prettier')
==> At key: types_or
==> At index 0
=====> Type tag 'typescript' is not recognized.  Try upgrading identify and pre-commit?
```
=> Fix tsx type name in pre-commit

requirements.txt
SpaCy was upgraded in #1617, so we need to update the pinned dependencies too.
=> Updated pinned transitive dependencies for SpaCy upgrade

src/helm/benchmark/scenarios/ice_scenario.py
It is odd that this is the only get_instance that has debug_cap, and I can't find any usage of it.
=> Remove one-off debug_cap.

src/helm/benchmark/metrics/metric.py
The typing information already tells us what types this dictionary maps.
=> Remove a comment that adds no information.

src/helm/benchmark/augmentations/dialect_perturbation.py, src/helm/benchmark/augmentations/person_name_perturbation.py, src/helm/benchmark/augmentations/synonym_perturbation.py, src/helm/benchmark/metrics/summarization_metrics.py, src/helm/benchmark/scenarios/summarization_scenario.py
This affects `dialect_perburbation`, `synonym_perturbation`, `person_name_perturbation`, `summarization_scenario` and `summarization_metrics`.
Addresses #1930
=> Move some perturbation, scenario and metrics datasets from CodaLab to GCS

src/helm/proxy/clients/http_model_client.py
Some users are reporting timeouts with 70b models, we're capping running times by saying the total runtime of docker image needs to be 2h but people are free to take longer on individual examples if they so choose
```
We are trying to use llama 70b, but occasionally encounter the following request problems during the reasoning process: Request error: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=300), Can the single request time be extended? Or do we have to complete it in 300 seconds? Thank you for your help
```
=> Increase timeout in http_model_client.py

src/helm/benchmark/metrics/statistic.py, src/helm/benchmark/metrics/test_statistic.py
Before, a method called "_update_stddev" called "_update_variance" which called "_update_mean". Beyond being confusingly named (update_stddv doesn't tell you it updates mean), there were no use cases where we'd want to update just one of the three.
While I was here, I added some more test coverage.
=> Simplify call structure when updating Stats member variables.

.github/workflows/test.yml, setup.cfg
This updates `python_requires` of the package. It also runs CI on Python 3.8 through 3.10. This triples the number of GitHub Action minutes used, which should hopefully not be a problem.
Fixes #1511
=> Support Python 3.9 and 3.10

src/helm/benchmark/server.py, src/helm/benchmark/static/benchmarking.js, src/helm/benchmark/static/config.js, src/helm/benchmark/static/index.html, src/helm/benchmark/static/json-urls-root.js, src/helm/benchmark/static/json-urls.js, src/helm/benchmark/static/utils.js
- Fixed an issue where copying the static directory as a static site did not work due to there being no `using_release` file
- Removed fetch of `using_release`
- Only fetch the map of run names to suites if needed
- Moved suite, release and benchmark output path configuration into `config.js`
- Allow `helm-server` to serve a suite or release as given by flags
- Allow `helm-server` to serve using a remote `benchmark_output` URL as given by the flag
=> Simplify the incremental release frontend

src/helm/benchmark/adaptation/adapters/adapter.py, src/helm/benchmark/adaptation/adapters/in_context_learning_adapter.py, src/helm/benchmark/adaptation/adapters/language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/test_generation_adapter.py, src/helm/benchmark/adaptation/adapters/test_language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/test_multiple_choice_joint_adapter.py
Clients of adapter should use "adapt" instead. Furthermore, InContextLearningAdapter actually needs two more arguments to generate requests: training instances and train_trial_index. In a followup PR I'll add those so they aren't passed via "self".
=> Move generate_requests down to InContextLearningAdapter

src/helm/benchmark/presentation/create_plots.py, src/helm/common/optional_dependencies.py
Add suggestions for what `pip install` command to run to get optional dependencies.
Example error message:
```Optional dependency seaborn is not installed. Please run `pip install crfm-helm[plots]` or `pip install crfm-helm[all]` to install it.```
=> Suggestions for optional dependencies

src/helm/benchmark/tokenizer_config_registry.py
You only need global if you assign to a variable you want to be global, and this method wasn't even referencing that variable.
=> Remove unnecessary "global" from register_tokenizer_configs_from_path.

src/helm/proxy/tokenizers/huggingface_tokenizer.py
AutoTokenizer is definitely not want we want, as it doesn't expose any of the methods called in this file on _tokenizer. PreTrainedTokenizerBase does have what we want, and Pylance suggested it was what from_pretrained returned.
=> Switch to better type info: PreTrainedTokenizerBase.

src/helm/benchmark/huggingface_registration.py
`TokenizerSpec` needs to instantiate a tokenizer instead of a client.
=> Change TokenizerSpec in huggingface_registration

src/helm/benchmark/metrics/basic_metrics.py, src/helm/benchmark/metrics/cleva_harms_metrics.py, src/helm/benchmark/metrics/cleva_metrics_helper.py
Previously, basic_metrics imported `cleva_harms_metrics`, which imported the optional dependency `jieba`. This prevented the `helm-run` from working without `crfm-helm[cleva]` installed.
=> Remove basic_metrics dependency on CLEVA optional dependencies

src/helm/benchmark/augmentations/cleva_perturbation.py, src/helm/benchmark/augmentations/contraction_expansion_perturbation.py, src/helm/benchmark/augmentations/contrast_sets_perturbation.py, src/helm/benchmark/augmentations/dialect_perturbation.py, src/helm/benchmark/augmentations/extra_space_perturbation.py, src/helm/benchmark/augmentations/filler_words_perturbation.py, src/helm/benchmark/augmentations/gender_perturbation.py, src/helm/benchmark/augmentations/lowercase_perturbation.py, src/helm/benchmark/augmentations/mild_mix_perturbation.py, src/helm/benchmark/augmentations/misspelling_perturbation.py, src/helm/benchmark/augmentations/person_name_perturbation.py, src/helm/benchmark/augmentations/perturbation.py, src/helm/benchmark/augmentations/space_perturbation.py, src/helm/benchmark/augmentations/synonym_perturbation.py, src/helm/benchmark/augmentations/typos_perturbation.py
Previously the `perturb` method needed to be overwritten even if the derived class had no use for it. By introducing an intermediate abstract class (TextPerturbation), implementations can choose between the simple `perturb` interface and taking ownership of `apply` directly.
=> Introduce TextPerturbation to allow Perturbation to stay fully generic.

src/helm/benchmark/runner.py, src/helm/benchmark/slurm_runner.py
Minor code health improvement. Has some trivial other improvements:
1. Before, an empty `scenario_output_path` directory would be created if it was missing.
2. There is now a single place where `run_path` is created, instead of relying on two places using the same strategy.
3. Skip doing string building for instance caching that we don't use.
=> Move early return to the start of run_one.

docs/get_helm_rank.md, docs/quick_start.md, src/helm/benchmark/presentation/run_display.py, src/helm/benchmark/presentation/run_specs_core_scenarios_10.conf, src/helm/benchmark/presentation/run_specs_core_scenarios_100.conf, src/helm/benchmark/presentation/run_specs_core_scenarios_1000.conf, src/helm/benchmark/presentation/run_specs_core_scenarios_20.conf, src/helm/benchmark/presentation/run_specs_core_scenarios_50.conf
This pull request adds:
- A fix to make the benchmark running tutorial work by allowing summarize to run without an instance.json file
- Updated and improved section for running the tutorial
- Removal of perturbation from the bear bones configuration file (to save an extra X3 compute)
=> Update get leaderboard tutorial

src/helm/benchmark/adaptation/adapters/language_modeling_adapter.py, src/helm/benchmark/adaptation/adapters/test_language_modeling_adapter.py
For all run_specs I can find except CLEVA, the language modeling scenario only produces TEST instances. For CLEVA, it appears to depend on if there is a 'train.jsonl' file.
=> Prevent LanguageModelingAdapter from evaling on TRAIN instances.

src/helm/benchmark/adaptation/adapters/test_language_modeling_adapter.py
Fix a test breakage caused by a merge conflict in the logic of #1986 (made `LanguageModelingAdapter` only support eval instances) and #1970 (added a new test for `LanguageModelingAdapter` with non-eval instances)
=> Fix test_language_modeling_adapter

src/helm/benchmark/presentation/run_display.py
This was the intent of #1993 but it instead introduced a bug by checking the wrong file for existence (instances.json) and was partially reverted by #2006.
=> Skip write_run_display_json if per_instance_state.json or scenario_state.json is missing

src/helm/benchmark/metrics/summarization_metrics.py, src/helm/proxy/clients/ai21_client.py, src/helm/proxy/clients/aleph_alpha_client.py, src/helm/proxy/clients/anthropic_client.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/client.py, src/helm/proxy/clients/cohere_client.py, src/helm/proxy/clients/google_client.py, src/helm/proxy/clients/goose_ai_client.py, src/helm/proxy/clients/http_model_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/lit_gpt_client.py, src/helm/proxy/clients/megatron_client.py, src/helm/proxy/clients/microsoft_client.py, src/helm/proxy/clients/openai_client.py, src/helm/proxy/clients/palmyra_client.py, src/helm/proxy/clients/simple_client.py, src/helm/proxy/clients/test_huggingface_client.py, src/helm/proxy/clients/test_together_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/clients/vision_language/idefics_client.py, src/helm/proxy/services/server_service.py, src/helm/proxy/token_counters/auto_token_counter.py, src/helm/proxy/token_counters/openai_token_counter.py, src/helm/proxy/token_counters/test_openai_token_counter.py, src/helm/proxy/tokenizers/auto_tokenizer.py, src/helm/proxy/tokenizers/test_anthropic_tokenizer.py, src/helm/proxy/tokenizers/test_huggingface_tokenizer.py
#1874 introduced a bug in which a few of clients (Megatron, Palmyra, any model created through `ModelDeployment`) were assigned the incorrect tokenizer. This fixes the bug and also makes `tokenizer()` and `decode()` unsupported on `CachingClient`.
=> Fix incorrect tokenizers in clients returned by AutoClient

.github/workflows/test.yml, MANIFEST.in
- Change the "Install" GitHub Action job to install from a Wheel package, rather than using local editable mode
- Change the "Install" GitHub Action job to quickly run the entire pipeline with test data
- Added the `*.yaml` files in `src/helm/config` to the package manifest
- Added `__init__.py` to `src/helm/config` so that the package is importable
=> Make ModelDeployments work when installing from package

src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/legalbench_scenario.py, src/helm/benchmark/static/schema.yaml
Adding 5 LegalBench tasks, which capture representative aspects of the benchmark. The scenarios file was modeled after RAFT.
=> Adding legalbench tasks

src/helm/benchmark/test_model_properties.py, src/helm/benchmark/window_services/wider_openai_window_service.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Tested with MedQA and NarrativeQA with just 10 instances. It seems to generate reasonable completions.
Information about the model: https://help.openai.com/en/articles/8555510-gpt-4-turbo
=> GPT-4 Turbo (preview)

src/helm/proxy/retry.py
Also simplify the `wait()` logic seems it tries to use a captured variable before it is defined, which is incorrect.
=> Fix incorrect duration in request retry logs

src/helm/common/cache.py
Currently the cache keeps retrying for _half an hour_ if the cache is down.
Additionally, this is nested within a outer request retry loop, which also retries for five times, giving a total of _two and half hours_ of retrying time.
This makes `helm-run` run for hours uselessly if the cache is down.
This change shortens it to one minute.
=> Shorten cache retry time

src/helm/benchmark/window_services/huggingface_window_service.py, src/helm/common/concurrency.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/tokenizers/huggingface_tokenizer.py, src/helm/proxy/tokenizers/test_huggingface_tokenizer.py
Hugging Face `PreTrainedTokenizerBase` is thread-hostile and using it from multiple threads simultaneously can result in an "Already borrowed" error (#1421). This adds `ThreadSafeWrapper`, which ensures that a lock is held when using the `PreTrainedTokenizerBase`.
Fixes #1421
=> Hold a lock when using thread-hostile Hugging Face tokenizers

src/helm/benchmark/server.py
Adds a shim for running helm-server for old suites from old version of helm-summarize that do not contain schema.json.
Backwards compatibility change for #2075.
=> Default helm-server to using schema_classic.yaml

src/helm/benchmark/run.py, src/helm/benchmark/run_specs.py, src/helm/benchmark/runner.py, src/helm/benchmark/scenarios/cleva_scenario.py, src/helm/benchmark/scenarios/dialogue_scenarios.py, src/helm/benchmark/scenarios/legalbench_scenario.py, src/helm/benchmark/scenarios/raft_scenario.py, src/helm/benchmark/scenarios/scenario.py
This fixes two problems:
- RAFT and LegalBench sometimes both use the same cache folder, as noted in #2075
- RAFT, LegalBench, CLEVA and BIG-Bench run spec functions and scenarios don't respect the `--output-path` flag
=> Fix incorrect cache directory used by run specs

src/helm/proxy/tokenizers/anthropic_tokenizer.py, src/helm/proxy/tokenizers/test_anthropic_tokenizer.py
Add a global lock for the Anthropic tokenizer.
The Anthropic tokenizer is a wrapper around a single global Hugging Face tokenizer, which is thread-hostile.
Fixes #1421
=> Add lock to AnthropicTokenizer

src/helm/benchmark/run_specs.py, src/helm/benchmark/scenarios/commonsense_scenario.py
In most cases, each Scenario represents a single source of data. For example, in almost all cases each Scenario has just one line using `ensure_file_downloaded`, often in a loop tweaking minor parts of the URL. However, each of `CommonSenseScenario`'s 5 datasets get data from different hosts. Two are zipped, and two appear to store labels in separate files. All 5 have different json structures.
I think we can simplify the code and make Scenario more uniform by breaking up `CommonSenseScenario`. This PR demonstrates pulling out HellaSwag and OpenBookQA. If we generally like where this is going, I can do the rest. If there is a strong reason to keep them as a single Scenario, please let me know so I can better understand the usecase.
For now I'm maintaining the ability to access all the …
=> Start to break CommonSenseScenario into smaller chunks.

src/helm-frontend/src/components/LeaderboardTables.tsx, src/helm-frontend/src/components/MiniLeaderboard.tsx
A hacky way to automatically filter down models for leaderboards.
Tested & working on my fork at https://farzaank.github.io/helm/
I'll follow up with a PR for the style changes.
At some point, we will want to do this and some other leaderboard related functionality differently in the future, but that will require a larger leaderboard refactor (probably next quarter).
=> Auto filtering functionality for leaderboards

scripts/cache/fix_anthropic_cache.py, src/helm/common/tokenization_request.py, src/helm/proxy/clients/anthropic_client.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/lit_gpt_client.py, src/helm/proxy/clients/megatron_client.py, src/helm/proxy/clients/openai_client.py, src/helm/proxy/clients/palmyra_client.py, src/helm/proxy/clients/vertexai_client.py, src/helm/proxy/clients/vision_language/idefics_client.py, src/helm/proxy/token_counters/openai_token_counter.py, src/helm/proxy/tokenizers/test_anthropic_tokenizer.py
Previously, `tokenizer` was set incorrectly in some `TokenizationRequest` / `DecodingRequest` objects.
=> Set name in tokenizer requests correctly

src/helm/benchmark/scenarios/math_scenario.py, src/helm/benchmark/scenarios/test_math_scenario.py
The Hugging Face implementation of MATH is non-deterministic, so we have to sort to ensure a fixed order.
=> Fix instance order for MATH scenario

src/helm/proxy/clients/aleph_alpha_client.py
The `completion_tokens` field may be omitted when the response is empty.
=> Handle responses with no completion_tokens field in AlephAlphaClient

src/helm-frontend/src/services/getSchema.ts
`schema.json` is produced by `helm-summarize`. We should use this instead of `schema.yaml` to allow switching between different schemas for different suites.
=> Use schema.json instead of schema.yaml in frontend

src/helm-frontend/src/components/Hero.tsx, src/helm-frontend/src/components/LeaderboardTables.tsx, src/helm-frontend/src/components/NavBar/NavBar.test.tsx, src/helm-frontend/src/components/NavDropdown.tsx, src/helm-frontend/src/types/global.d.ts
- Reads in whether to show classic/lite from config.js
- Style fixes
- Bolding lite/classic
- Fix mobile leaderboard on landing page 
- Updated copy of nav dropdown from Percy's suggestion
Live at https://farzaank.github.io/helm/
Still finishing up raw runs linking, I'll follow this up with that PR tomorrow
@yifanmai could you share the code or schema for HELM lite so I can see why the scenario list isn't showing up properly?
And sorry for late PR adjusting to a different timezone (New Zealand)
=> Front-end updates for HELM lite

src/helm-frontend/src/components/MetricsList.tsx
Previously the frontend's metric count was the total number of metrics in the schema. This pull request changes it to the number of actually rendered metric names.
Also removes the dead link from the metric group header.
=> Compute number of metrics correctly

src/helm/benchmark/config_registry.py, src/helm/benchmark/huggingface_registration.py, src/helm/benchmark/model_deployment_registry.py, src/helm/benchmark/model_metadata_registry.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/run.py, src/helm/benchmark/test_model_deployment_definition.py, src/helm/benchmark/test_model_properties.py, src/helm/benchmark/tokenizer_config_registry.py, src/helm/proxy/clients/cohere_client.py, src/helm/proxy/server.py, src/helm/proxy/services/server_service.py
- Ensure that config registration is only performed at entry points
- Ensure that custom config registration does not get overwritten by default model registration
- Removed some unused / unnecessary helper methods
- Cleaned up comments and documentation
=> Simplify config registration

src/helm-frontend/src/components/NavDropdown.tsx
- Switch from using `<Link>` to `<a>` because the React router seems to be rewriting these links incorrectly.
- Update HELM Lite link.
- Drop tailing "?" from HEIM link.
=> Fix NavDropdown links

src/helm/config/model_deployments.yaml
`ObjectSpec.args` default to the empty dictionary, so empty `args` are not needed in `model_deployments.yaml`
=> Remove empty args from specs in model_deployments.yaml

src/helm/benchmark/metrics/metric.py, src/helm/benchmark/runner.py
I think there are likely at least 3 distinct kinds of Metric:
* evaluate_generation
* evaluate_references
* evaluate_instances
This is the first step segmenting those out.
=> Introduce an interface for Metric.

src/helm/benchmark/metrics/bbq_metrics.py, src/helm/benchmark/metrics/bias_metrics.py, src/helm/benchmark/metrics/classification_metrics.py, src/helm/benchmark/metrics/cleva_accuracy_metrics.py, src/helm/benchmark/metrics/evaluate_instances_metric.py, src/helm/benchmark/metrics/metric.py, src/helm/benchmark/metrics/paraphrase_generation_metrics.py, src/helm/benchmark/runner.py
Since these classes don't override evaluate_generation or evaluate_references, they don't produce any Stats in Processor.process. That means they don't produce any per_instance_stats or compute_worst_case_metrics.
=> Split out evaluate_instances out of Metric.

src/helm/benchmark/metrics/dry_run_metrics.py, src/helm/benchmark/metrics/image_generation/denoised_runtime_metric.py, src/helm/benchmark/metrics/image_generation/fidelity_metrics.py, src/helm/benchmark/metrics/image_generation/image_critique_metrics.py, src/helm/benchmark/metrics/image_generation/photorealism_critique_metrics.py
All of these classes define their own evaluation method and don't call any other methods defined in Metric from that.
=> Stop inheriting from Metric in classes that don't use its implementation

.pre-commit-config.yaml
- Only run Python pre-commit when Python files are changed
- Fixed a bug where a commit with a large changed file list can cause concurrent instances of `pre-commit.sh` to be spawned, which can lead to errors due to concurrent runs of `mypy`.
=> Improve Python pre-commit

docs/mkdocs_hooks.py, docs/mkdocs_macros.py, docs/models.md, mkdocs.yml
This fixes the mkdocs build.
This also puts the text and code models back on the documentation page, because we now only list _evaluated_ models on the [HELM website](https://crfm.stanford.edu/helm/lite/latest/#/models), rather than _available_ models.
=> Fix models documentation

src/helm/common/cache.py, src/helm/common/key_value_store.py, src/helm/common/mongo_key_value_store.py, src/helm/proxy/clients/client.py, src/helm/proxy/clients/google_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/image_generation/adobe_vision_client.py, src/helm/proxy/clients/image_generation/aleph_alpha_image_generation_client.py, src/helm/proxy/clients/image_generation/cogview2_client.py, src/helm/proxy/clients/image_generation/dalle_mini_client.py, src/helm/proxy/clients/image_generation/deep_floyd_client.py, src/helm/proxy/clients/image_generation/huggingface_diffusers_client.py, src/helm/proxy/clients/image_generation/lexica_client.py, src/helm/proxy/clients/image_generation/together_image_generation_client.py, src/helm/proxy/clients/together_client.py
`Mapping` is the immutable base class of `dict`. By using `Mapping` we gain two benefits:
1. Type checking ensures we aren't trying to mutate the arguments within caching.
2. Caching will accept dict-like objects like TypedDict.
=> Switch caching over to using Mapping instead of Dict.

docs/adding_new_models.md, docs/quick_start.md, docs/tutorial.md, src/helm/proxy/clients/simple_client.py
Fix #2022.
- Rewrote from scratch "Adding new models".
- Added a variant of `simple/model1` for the tutorial.
- Added a paragraph explaining the use of `model` and `model_deployment` keywords in `tutorial.md`.
- Ported a `model=huggingface/gpt2` to `model=openai/gpt2`.
=> Update tutorial to reflect changes on model deployments

.gitignore, .pre-commit-config.yaml, helm-frontend/index.html, helm-frontend/public/config.js, helm-frontend/src/services/getDisplayPredictionsByName.ts, helm-frontend/src/services/getDisplayRequestsByName.ts, helm-frontend/src/services/getInstances.ts, helm-frontend/src/services/getRunSpecByName.ts, helm-frontend/src/services/getRunsToRunSuites.ts, helm-frontend/src/services/getScenarioByName.ts, helm-frontend/src/services/getScenarioStateByName.ts, helm-frontend/src/services/getStatsByName.ts, helm-frontend/src/utils/getVersionBaseUrl.ts, helm-frontend/vite.config.ts, src/helm/benchmark/server.py
This allows using the React frontend with `helm-server` with a local `benchmark_output` folder:
1. In `helm_frontend/`, run `yarn build`
2. Run `helm-server --react`
This is preparation for replacing the old frontend with the React frontend entirely.
=> Add a flag to serve the React frontend on helm-server

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/presentation/table.py
Add a `run_spec_names` field to each table cell, which contains names of the runs that this cell's value was aggregated from. This allows the frontend to link from tables to runs.
For scenario tables, `run_spec_names` will be added to the model cells, whereas for non-scenario tables, `run_spec_names` will be added to the metrics cells.
=> Add run_spec_names to table cells

src/helm/benchmark/config_registry.py, src/helm/benchmark/multi_gpu_runner.py, src/helm/benchmark/runner_config_registry.py, src/helm/benchmark/slurm_runner.py
Basic multi gpu support by adapting `SlurmRunner` 
Note: `start_thread_to_terminate_when_parent_process_dies` is included due to https://github.com/stanford-crfm/helm/blob/9fbb212ceb1dd6f075214385c5dc81f5c60fee04/src/helm/proxy/retry.py#L56
=> feat: add task-parallel support on multi gpus

src/helm/proxy/clients/openai_client.py
Previously there were three distinct paths through make_requests, that only shared a few lines. This PR is just moving code and deleting unused variables.
=> Unnest openai_client.make_request into three separate functions.

src/helm/benchmark/window_services/test_gptj_window_service.py, src/helm/benchmark/window_services/test_gptneox_window_service.py, src/helm/config/model_deployments.yaml, src/helm/proxy/clients/test_together_client.py, src/helm/proxy/clients/together_client.py
This removes the hardcoded constant mapping of HELM model names to Together model names from `together_client.py`.
This allows a HELM user to run _any_ Together model on HELM without pulling the HELM repository or modifying any HELM code. The user can simply add the Together model to their local `prod_env/model_deployments.yaml`.
This also removes the need for HELM maintainers to keep `together_client.py` in sync with the current Together model list, which frequently changes.
=> Remove hardcoded Together model aliases

.github/workflows/test.yml
HELM CI tests now take 25 minutes, compared to 10 minutes a couple months ago. This determines the slowest tests so that they can be marked and run in a separate parallel test run.
=> Find the slowest pytest tests in GitHub Actions

helm-frontend/src/components/LeaderboardTables.tsx, helm-frontend/src/components/MiniLeaderboard.tsx, helm-frontend/src/components/NavBar/NavBar.tsx, helm-frontend/src/components/PageTitle/PageTitle.tsx, helm-frontend/src/layouts/Main.tsx, helm-frontend/src/routes/Leaderboard.tsx
- Moves the vertical scroll bar from the page viewport to the table wrapper div.
- Set the table height using the viewport height to avoid page scrolling in most situations.
- Sets cell background to opaque, so that the sticky cells are readable when overlapping other cells.
- Removes `className` prop from `PageTitle`, which was causing HTML elements to have the string "undefined" as a class name.
- Removes a lot of unnecessary whitespace, which leaves more room for the table.
=> Sticky cells for leaderboard table

.github/workflows/update-requirements.yml, install-dev.sh, install-heim-extras.sh, requirements.txt, setup.cfg, src/helm/benchmark/metrics/summarization_metrics.py
Now that we have CUDA 12 on our internal machines, we should use PyTorch 2.1.2 everywhere to take advantage of CUDA 12. This aligns with VLM, which _already_ [uses PyTorch 2.1.2](https://github.com/stanford-crfm/helm/blob/76e168e5cff3558ea652537698ddf8ea6753f355/setup.cfg#L138).
Also bump the minimum supported version of PyTorch to 1.13.1 to address the security vulnerability reported in [CVE-2022-45907](https://nvd.nist.gov/vuln/detail/CVE-2022-45907).
=> Bump PyTorch version to 2.1.2

conftest.py, src/helm/benchmark/adaptation/adapters/test_adapter.py, src/helm/benchmark/test_model_deployment_definition.py, src/helm/benchmark/window_services/image_generation/test_clip_window_service.py, src/helm/benchmark/window_services/image_generation/test_openai_dalle_window_service.py, src/helm/benchmark/window_services/test_anthropic_window_service.py, src/helm/benchmark/window_services/test_bloom_window_service.py, src/helm/benchmark/window_services/test_cohere_window_service.py, src/helm/benchmark/window_services/test_flan_t5_window_service.py, src/helm/benchmark/window_services/test_gpt2_window_service.py, src/helm/benchmark/window_services/test_gpt4_window_service.py, src/helm/benchmark/window_services/test_gptj_window_service.py, src/helm/benchmark/window_services/test_gptneox_window_service.py, src/helm/benchmark/window_services/test_ice_window_service.py, src/helm/benchmark/window_services/test_mt_nlg_window_service.py, src/helm/benchmark/window_services/test_openai_window_service.py, src/helm/benchmark/window_services/test_opt_window_service.py, src/helm/benchmark/window_services/test_palmyra_window_service.py, src/helm/benchmark/window_services/test_t0pp_window_service.py, src/helm/benchmark/window_services/test_t511b_window_service.py, src/helm/benchmark/window_services/test_ul2_window_service.py
Put `register_builtin_configs_from_helm_package()` in conftest.py ([doc](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files)). This eliminates the need to call `register_builtin_configs_from_helm_package()` from within tests, and ensures that `register_builtin_configs_from_helm_package()` is not called multiple times unnecessarily during testing.
=> Register configs at the start of test session

src/helm/benchmark/metrics/machine_translation_metrics.py
This was deleted by #2009 but is still needed by the CLEVA translation run specs.
=> Restore machine_translation_metrics.py

setup.cfg
This will allow pip to install more recent versions when performing dependency resolution. This is particularly important for `datasets` and `transformers`, which have recent bugfixes and new features.
=> Loosen version specifiers for core dependencies

helm-frontend/src/components/NavBar/NavBar.tsx, helm-frontend/src/components/Preview.tsx, helm-frontend/src/routes/Leaderboard.tsx, helm-frontend/src/routes/Run.tsx
- Remove columns for instances so that the entire text can be displayed without scrolling.
- Switch from `pre` to `whitespace: pre-wrap` which is more appropriate, and what the jQuery UI uses.
- Clean up the model view
Fixes #2258
=> Various fixes to run predictions frontend

helm-frontend/src/components/GroupsTables.tsx
Same as #2273 but for group tables.
Fixes #2255.
=> Sticky cells to group tables

.github/workflows/build-frontend.yml, .github/workflows/update-requirements.yml
The "Build Frontend" and "Update requirements.txt" workflows should trigger themselves when their workflow definition files are modified, because changes to the workflow definitions would also change the workflow output.
=> Trigger GitHub Actions workflows when workflow files are modified

helm-frontend/src/components/GroupsTables.tsx, helm-frontend/src/components/LeaderboardTables.tsx, helm-frontend/src/components/NavBar/NavBar.tsx
This removes scrollbars on tables. This means that the header row and column on table is sticky relative to the browser viewport. This also makes the navbar un-sticky, because it would otherwise cover the table header row.
=> Remove scrollbars on tables

src/helm/benchmark/presentation/test_run_entry.py
Temporarily disable `test_read_all_specs()` for CLEVA because CLEVA scenarios are broken due to a missing data file.
Addresses #2303
=> Remove CLEVA from test_read_all_run_specs()

helm-frontend/src/components/LeaderboardTables.tsx, helm-frontend/src/components/RowValue.tsx
Should address all feedback for the leaderboard in https://github.com/stanford-crfm/helm/issues/2291
-  When mousing over a model name, should show more information about the model, either as a tooltip (preferred) or via a link to the models page (need a href anchor). 
- Fully addressed
-  We still write ‘Model/adapter’ - should just be ‘Model’ for simplicity 
- Could not find where this still appears in the leaderboard upon a quick visual inspection, let me know if i missed something 
-  When mouseover heading (e.g., F1), should tooltip show the description based on the schema
- Fully addressed
-  We still show ⚠; would just drop all the train-test contamination stuff from the frontend since we’re not consistently updating this
- Mostly addressed, this won't appear in the front end …
=> Fixing leaderboard feedback

src/helm/benchmark/run.py, src/helm/proxy/clients/auto_client.py
After this and #2309 are merged, we will be able to remove Hugging Face libraries to optional dependencies. This will greatly reduce the number of transitive dependencies required to install core HELM.
=> Make core HELM not depend on Hugging Face libraries

src/helm/proxy/server.py
Clients with version <= 0.3.0 do not set `model_deployment`, but this is now required by `Request`. To maintain backwards compatibility, we set `model_deployment` to `model` when not set by the client.
Fixes #2270.
=> Support clients with version <= 0.3.0 in crfm-models

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/presentation/table.py
The contamination data is no longer maintained, so we should remove this from `helm-summarize` to stop putting outdated contamination data in the summary tables.
=> Remove contamination level output from helm-summarize

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/proxy/example_queries.py
- Change sample requests to send the `model_deployment` field.
- Add `davinci-002` and `babbage-002` as replacements for deprecated text completion models, as all other text completion models have been deprecated.
- Switch sample requests to use `davinci-002` or `gpt-3.5-turbo-*`.
=> Fix sample requests in proxy server

src/helm/proxy/services/server_service.py
On the crfm-models playground server, we have existing users with quota under legacy group names such as `codex`, `dall_e`, `gpt3`, `gpt4` and `jurassic` which do not correspond to the model host organization name. This change allows existing users to continue using quota in under these legacy group names.
Fixes #2293
=> Use legacy group names for quota accounting

src/helm/proxy/accounts.py, src/helm/proxy/services/test_remote_service.py, src/helm/proxy/test_accounts.py
Previously, users who were never allocated quota actually have infinite quota, because we currently treat quotas of `None` as infinite quota.
Also grants admins unlimited quota.
Fixes #1495
=> Prevent accounts with no quota from using the crfm-models server

src/helm/proxy/clients/aleph_alpha_client.py, src/helm/proxy/clients/goose_ai_client.py, src/helm/proxy/clients/huggingface_client.py, src/helm/proxy/clients/microsoft_client.py, src/helm/proxy/clients/openai_client.py, src/helm/proxy/clients/together_client.py, src/helm/proxy/services/test_service.py
This PR removes every identifier containing "top_logprobs" and the code associated, as none of it does anything anymore.
=> Remove top_logprobs: all remaining references.

src/helm/benchmark/server.py
- Makes `helm-server` use the React frontend by default
- Removes the `--react` flag
- Adds the `--jquery` flag for falling back to the legacy frontend
=> Use the React frontend in helm-server by default

setup.cfg
Upgrade `datasets` to fix a failure in MathScenario. Sample stack trace:
```
File "/u/scr/maiyifan/miniconda3/envs/crfm-helm-main/lib/python3.8/site-packages/helm/benchmark/scenarios/math_scenario.py", line 357, in get_instances
data = typing.cast(DatasetDict, load_dataset("competition_math")).sort("problem").shuffle(seed=42)
File "/u/scr/maiyifan/miniconda3/envs/crfm-helm-main/lib/python3.8/site-packages/datasets/load.py", line 1705, in load_dataset
ds = builder_instance.as_dataset(split=split, ignore_verifications=ignore_verifications, in_memory=keep_in_memory)
File "/u/scr/maiyifan/miniconda3/envs/crfm-helm-main/lib/python3.8/site-packages/datasets/builder.py", line 992, in as_dataset
raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not …
```
=> Upgrade datasets

src/helm/common/general.py
Currently, `ensure_file_downloaded()` silently does the wrong thing if a shell command fails. For instance, `ensure_file_downloaded()` writes an empty file if the source URL is not found.
Fixes #1932.
=> Raise an exception if shell commands exit with non-zero exit code

setup.cfg
Qwen1.5 uses a `QwenTokenizer2`, which requires `transformers>=4.37`.
=> Upgrade transformers for Qwen1.5

src/helm/proxy/tokenizers/huggingface_tokenizer.py
Some tokenizers (e.g. Qwen/Qwen-7B) return the tokens as bytes, so we have to decode them to strings.
=> Handle Hugging Face Tokenizers that return bytes instead of str

src/helm/proxy/clients/test_together_client.py, src/helm/proxy/clients/together_client.py
Together no longer supports the `logprobs` parameter:
```
{"error":{"message":"5 is greater than the maximum of 1 - 'logprobs'","type":"invalid_request_error","param":"logprobs","code":null}}
```
=> Remove logprobs from TogetherClient

src/helm/config/model_deployments.yaml, src/helm/proxy/clients/mistral_client.py
- Use a `MistralAIRequest` `TypedDict` for the MistralAIClient raw request
- Use Pydantic's `model_dump()` instead of `dict()` because `dict()` is deprecated
- Pass the model name as part of the `MistralAIRequest` to `_make_request()`, rather than having it be a separate parameter
- Delete `_model_aliases` and move the the model name to `model_deployments.yaml`
- Set `random_seed` properly for multiple completions
- Remove `completion_index` from the cache key since it is never sent to the API
=> Various MistralAIClient fixes

src/helm/proxy/clients/mistral_client.py
In Pydantic's `model_dump()` inside MistralAIClient, set `mode="json"` to ensure that the output will only contain JSON serializable types, because the output will be serialized for storage in the cache.
When `mode="json"` is unset, the output will contain a `FinishReason` enum, which will result in the error `Object of type FinishReason is not JSON serializable`.
When `mode="json"` is set, the output will contain the string value of the `FinishReason` rather than the `FinishReason` itself.
=> Use JSON mode in Pydantic model_dump in MistralAIClient

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
Adds Phi2 and Qwen1.5 (along with Qwen) to config yamls.
Myself and Yifan have tested separately and are filling out the model checklist.
=> Adding Phi2 and Qwen1.5

helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/components/Predictions.tsx, helm-frontend/src/components/References.tsx, helm-frontend/src/types/DisplayPrediction.ts, helm-frontend/src/types/Instance.ts, helm-frontend/src/types/Reference.ts
The references and mapped output are useful for MCQA tasks.
Screenshot:
=> Add references and mapped output to frontend

src/helm/proxy/server.py
This is required to send the intermediate certificate as [recommended by Stanford University IT](https://uit.stanford.edu/service/ssl/chain).
Failing to do so will result in the following error when attempting to connect to the proxy using our Python library: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`
I have already patched this on the server, and would like to merge it into main.
=> Send intermediate certificate in crfm-models proxy server

src/helm/common/tokenization_request.py, src/helm/proxy/clients/client.py, src/helm/proxy/clients/mistral_client.py, src/helm/proxy/clients/test_client.py
Currently, `mistralai/mistral-medium` text completions looks like this:
```
▁1936<0x0A><0x0A>Question:▁When▁was▁the▁last▁time▁the▁toronto▁maple▁leafs▁won▁the▁stanley▁cup?<0x0A>
```
This is because:
1. The Mistral AI API does not support stop sequences and max tokens, so we rely on `truncate_sequence()` to truncate based on the stop sequences and max tokens.
2. The Mistral model uses a `HuggingFaceTokenizer` that substitutes spaces with `▁`
3. When `truncate_sequence()` truncates based on max tokens, it does so by replacing the response's text with the concatenation of the tokens.
Rather than trying to modify `HuggingFaceTokenizer` or `truncate_sequence()`, which may have far-reaching effects on other models, we instead define a new method `truncate_and_tokenize_response_text()` that is …
=> Fix bad characters in mistralai/mistral-medium model's output text

helm-frontend/src/components/Predictions.tsx, helm-frontend/src/components/Request/Request.test.tsx, helm-frontend/src/components/Request/Request.tsx, helm-frontend/src/routes/Run.tsx
From https://github.com/stanford-crfm/helm/issues/2291 addresses: 
- Renamed to "Prompt Details" to avoid redundancy
- Combined into "Prompt Details" view
- Replaced with accordion for "Prompt Details" as discussed in show and tell
- Replaced pop-up with accordion
- Partially supported (we don't have a model page yet so that remains undone)
=> Update predictions page front end

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/static/schema_instruction_following.yaml
- HELM-Instruct runs have no `num_instances` metric, therefore the check for `num_instances` in `helm-summarize` must be removed to allow it to work at all.
- `perturbations` is a required field in `Schema`, so it must be set to an empty list even if there are no perturbations.
- The `category` field doesn't seem to do anything in `Schema`, so it is deleted.
=> Get helm-summarize to work on HELM-Instruct

helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/components/Predictions.tsx, helm-frontend/src/components/References.tsx, helm-frontend/src/types/DisplayPrediction.ts
Provides basic image support such that HEIM can use the new front-end. Existing HELM frontends should be unchanged as a result of this.
There could be a better logic switch/thing to check before triggering the image display versus the normal text display. We can discuss that here.
Try it [here](https://farzaank.github.io/heim/#/runs/common_syntactic_processes:phenomenon=ambiguity,model=AlephAlpha_m-vader,max_eval_instances=100)
Compare it to the existing [frontend](https://crfm.stanford.edu/heim/latest/?runs=1&runSpec=common_syntactic_processes%3Aphenomenon%3Dambiguity%2Cmodel%3DAlephAlpha_m-vader%2Cmax_eval_instances%3D100)
I will follow-up with some other changes that makes HEIM work generally.
=> Provide basic image support

setup.cfg, src/helm/benchmark/test_model_deployment_definition.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/proxy/clients/bedrock_client.py, src/helm/proxy/clients/bedrock_utils.py, src/helm/proxy/clients/client.py
Also adds `BedrockClient` which can be specialized to run other models on Amazon Bedrock.
=> Add Amazon Titan

helm-frontend/public/config.js, helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/components/Predictions.tsx, helm-frontend/src/components/References.tsx, helm-frontend/src/components/ReleaseDropdown.tsx, helm-frontend/src/services/getSchema.ts, helm-frontend/src/types/DisplayPrediction.ts
Implemented the following fixes for HEIM to start working. This allows you to run HEIM on the front-end on the same codebase by updating the expected 2 fields in config.js
Changes are live at https://farzaank.github.io/heim/
This only leaves us needing to design a new landing page for HEIM, like we did for HELM-instruct.
- Rearrange config.js such that benchmark_output is last
- Intuitively it would seem we shouldn't have benchmark_output be dependent on suite or release, but this is the case for HEIM. And since this is at least theoretically possible to be replicated in other HELMlets, it's probably best to just build in support for this.
- You can now do 
`window.BENCHMARK_OUTPUT_BASE_URL ="https://nlp.stanford.edu/helm/${window.SUITE}/benchmark_output/"`
- Add suite fallback for …
=> Frontend patches for HEIM

setup.cfg, src/helm/benchmark/test_model_deployment_definition.py, src/helm/proxy/clients/auto_client.py, src/helm/proxy/clients/image_generation/dalle2_client.py, src/helm/proxy/clients/image_generation/dalle3_client.py, src/helm/proxy/clients/moderation_api_client.py, src/helm/proxy/clients/openai_client.py, src/helm/proxy/services/server_service.py
Migrate to OpenAI SDK v1.0.0, using the guide and CLI tool [here](https://github.com/openai/openai-python/discussions/742).
I manually tested this by sending requests and checking that the `RequestResult` looked acceptable for the following models: `gpt-3.5-turbo-instruct` (completion), `gpt-3.5-turbo-0613` (chat), `text-embedding-ada-002` (embedding), and `dall-e-2` (image).
The only behavior change is that we now use "model" instead of "engine" in the request to completion and embedding models, because "engine" is deprecated. This means that new requests will not match existing cache keys for completion and embedding models. Chat models were already using "model" and are unaffected.
Also fixes an existing issue where `ModerationAPIClient` is instantiated eagerly instead of lazily in …
=> Upgrade OpenAI SDK

src/helm/benchmark/adaptation/adapters/test_generation_adapter.py, src/helm/benchmark/heim_run_specs.py, src/helm/benchmark/presentation/test_run_entry.py, src/helm/benchmark/run.py, src/helm/benchmark/run_specs/classic_run_specs.py, src/helm/benchmark/scenarios/test_scenario.py, src/helm/benchmark/test_data_preprocessor.py, src/helm/benchmark/vlm_run_specs.py, src/helm/proxy/critique/model_critique_client.py
This is a precursor to #2321 and must be landed first.
For some reason, git does not recognize the refactor in #2321 as a file rename of `run_specs.py`. Therefore, we should do the file rename in this isolated pull request, so that file history and blame history is preserved in git for debugging purposes.
=> Rename run_specs.py to classic_run_specs.py

helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/components/MetricsList.tsx, helm-frontend/src/components/Predictions.tsx, helm-frontend/src/components/Preview.tsx, helm-frontend/src/components/StatNameDisplay.tsx, helm-frontend/src/routes/Run.tsx, helm-frontend/src/types/Adapter.ts, helm-frontend/src/types/AdapterField.ts, helm-frontend/src/types/AdapterFieldMap.ts, helm-frontend/src/types/Metric.ts, helm-frontend/src/types/MetricField.ts, helm-frontend/src/types/MetricFieldMap.ts, helm-frontend/src/types/Schema.ts, helm-frontend/src/utils/underscoreToTitle.ts
Addresses #2291
Fixes #2383
- When mouseover any key in adapter or metrics (e.g., num_train_trials), show a tooltip with the description of that key.
- In general, strong dislike for scrollbars, and I think the input box should be a lot bigger (scroll when we hit nearly a screen full of content).
- Make accordion more "accordion-like"
=> Improve frontend display of adapters, stats, requests and predictions

src/helm/proxy/clients/clip_score_client.py
By importing `ClipScorer` only if needed, the duration of running `helm-run --help` is reduced from 3 seconds to 0.5 seconds.
=> Import ClipScorer lazily

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Also update the name for Mistral Medium.
=> Add Mistral Small and Mistral Large

src/helm/proxy/clients/openai_client.py, src/helm/proxy/clients/vllm_client.py
`VLLMClient` is a lightly customized version of `OpenAIClient` that allows sending requests to a vLLM server using the [OpenAI-compatible API](https://docs.vllm.ai/en/latest/getting_started/quickstart.html#openai-compatible-serve).
This closes a request from Shah Lab.
Fixes #1997
=> Add vLLM client

src/helm/proxy/server.py
This maintains reverse compatibility with clients with version <= 1.0.0. Clients with version <= 1.0.0 expect each token to contain a `top_logprobs` field of type dict, which was removed by #2323.
Requested by @q-hwang
=> Return token top_logprobs in crfm-models server

.github/workflows/manage-python-cache.yml
Add GitHub Actions Workflows for manually managing the Python cache.
HELM's dependencies (e.g. PyTorch, transformers) can be very large, and the cache may contain multiple versions of these dependencies, so we may have to purge the cache from time to time.
=> Add GitHub Actions workflow for viewing and purging the Python cache

helm-frontend/src/components/NavBar/NavBar.test.tsx, helm-frontend/src/components/NavBar/NavBar.tsx, helm-frontend/src/components/NavDropdown.tsx, helm-frontend/src/components/ReleaseDropdown.tsx, helm-frontend/src/types/ReleaseSummary.ts
- Switched to using DaisyUI's dropdown menu
- Improved accessibility by enabling keyboard tab navigation of dropdown menus
- Added closing of the menu by clicking outside the menu
- Moved HELM logo out of the dropdown component
- Used HELM logo in asset bundle rather than an external logo
- Fixed schema for `summary.json`
- Added HELM Instruct to dropdown
- Made version dropdown reflect versions of the current HELMet, rather than always displaying the Lite versions
- Only a render a dropdown menu if there are at least two versions i.e. don't render the menu for HELM Instruct
- Added previously missing HELM Classic versions
- Added new versions for HEIM and Lite
Fixes #2136
=> Frontend dropdown menu improvements

MANIFEST.in
This is required for `helm-server` to serve the new React frontend when the `crfm-helm` package is installed from PyPI.
=> Add src/helm/benchmark/static_build/ to manifest

helm-frontend/src/services/getReleaseSummary.ts
Fix a type error caused by #2410: `getReleaseSummary()` needs to follow the new `ReleaseSummary` schema.
=> Fix frontend breakage

helm-frontend/vite.config.ts
#2372 added the yaml library to the Vite build. This caused the build frontend diffs to go up from 8 lines in #2367 to 141 lines in #2398. Moving the yaml library to its own Vite bundle will reduce the diffs back to 8 lines.
=> Move yaml to its own Vite bundle

.github/workflows/test.yml, .github/workflows/update-requirements.yml, docs/adding_new_models.md, docs/huggingface_models.md, src/helm/benchmark/run.py, src/helm/benchmark/slurm_runner.py
We should clarify that run entry is not a `RunSpec` - a run entry can produce multiple `RunSpec`s. This flag specifies run entries, not `RunSpec`s..
For now, we mark the `--run-specs` flag as deprecated, but we do not remove it yet to avoid breaking users.
=> Rename --run-specs to --run-entries

src/helm/clients/anthropic_client.py, src/helm/common/media_object.py, src/helm/config/model_metadata.yaml
Documentation:
- https://docs.anthropic.com/claude/reference/messages_post
- https://docs.anthropic.com/claude/docs/vision
=> Add VLM support to Claude 3

src/helm/benchmark/static/schema_classic.yaml, src/helm/benchmark/static/schema_instruction_following.yaml, src/helm/benchmark/static/schema_lite.yaml, src/helm/benchmark/static/schema_vlm.yaml
The `model` field is not deprecated, and is semantically distinct from `model_deployments`.
=> Un-deprecate model field in schema

helm-frontend/package.json, helm-frontend/vite.config.ts, helm-frontend/yarn.lock
This causes `yarn dev` to serve the `benchmark_output` folder relative to the root of the repository 
(i.e. `../benchmark_output` relative to `helm-frontend`)at `http://localhost:5173/benchmark_output`
=> Add benchmark_output serving to the vite config

helm-frontend/public/config.js, helm-frontend/src/components/NavBar/NavBar.test.tsx, helm-frontend/src/components/NavDropdown.tsx, helm-frontend/src/components/ReleaseDropdown.tsx, helm-frontend/src/utils/getReleaseUrl.ts
- Fix links in the project dropdown. Previously the URLs were incorrect because they contained the project name twice (e.g. https://crfm.stanford.edu/helm/lite/lite/ )
- Prevent the dropdown from briefly flashing "Lite" and "Version unknown" respectively before `summary.json` is loaded.
- Prevent dropdown arrow from wrapping to a newline
=> Fix dropdown bugs

helm-frontend/package.json, helm-frontend/src/services/getSchema.ts, helm-frontend/yarn.lock
Everyone using the new frontend should be using `schema.json` instead.
=> Remove support for schema.yaml in the React frontend

src/helm/benchmark/adaptation/adapter_spec.py
#2473 introduced a bug that makes `AdapterSpec` unhashable, because `eval_splits` is of type `List`, which is unhashable. Running `helm-summarize` with an `AdapterSpec` with a non-empty `eval_splits` will result in:
```
File "/home/yifanmai/oss/helm/src/helm/benchmark/presentation/summarize.py", line 417, in group_runs
self.group_adapter_to_runs[group_name][adapter_spec].append(run)
File "<string>", line 3, in __hash__
TypeError: unhashable type: 'list'
```
We simply ignore this field for hashing (like we did for `stop_sequences`).
=> Fix AdapterSpec unhashable bug

helm-frontend/src/components/MediaObjectDisplay.tsx
Renders MediaObject in front end and removes extra labels for the object, like that text is of text type and images are of image type (I can add them back if desired).
Notably, the examples in VHELM seem to not work even after handling the deduplication of "benchmark_output/" but I may have missed something. The URLs look reasonable afterwards but don't seem to work. 
Here are some examples for reference (are these expected to be accessible?):
https://nlp.stanford.edu/helm/vhelm/benchmark_output/scenarios/a_okvqa/images/DPtUMrxDbLP2nQ9yUdmvkT.jpg
https://nlp.stanford.edu/helm/vhelm/benchmark_output/scenarios/a_okvqa/images/XkEu3gmYW23qTivgmHP3fN.jpg
=> Render media object in front end

helm-frontend/vite.config.ts, src/helm/benchmark/server.py
Annotations contain paths of the form `prod_env/cache/output/latexcompiler/847f21a0dc444766a591d64ee00a6f13.png` but `prod_env` is not served by any web server.
This change makes `prod_env/cache/output/` accessible at `http://localhost:8000/cache/output/` for `helm-server` or `http://localhost:5173/cache/output/` for the Vite server so that these files are accessible. The frontend will need to translate the URLS e.g. `prod_env/cache/output/latexcompiler/847f21a0dc444766a591d64ee00a6f13.png` becomes `/cache/output/latexcompiler/847f21a0dc444766a591d64ee00a6f13.png`
=> Serve prod_env/cache/output on development servers

src/helm/benchmark/server.py
Missed what appears to be a typo in https://github.com/stanford-crfm/helm/pull/2493/files
This fixes that typo
=> Fix typo in server.py

src/helm/benchmark/adaptation/adapters/test_generation_adapter.py, src/helm/benchmark/run_specs/classic_run_specs.py, src/helm/benchmark/run_specs/simple_run_specs.py, src/helm/benchmark/scenarios/simple_scenarios.py, src/helm/benchmark/scenarios/test_simple_scenarios.py, src/helm/benchmark/test_data_preprocessor.py
The existing `Simple1Scenario` is not actually that simple, and it is hard to use it in a tutorial.
This adds even simpler scenarios, one for each common NLP task: multiple-choice QA, short answer QA, and classification. These scenarios are more appropriate for tutorials. Additionally, these scenarios are accompanied by scenario tests, which will be required for all future scenarios added to HELM.
=> Add simple scenarios for tutorials

src/helm/clients/vertexai_client.py, src/helm/config/model_deployments.yaml
Gemini is currently not working because it uses the Vertex AI API tokenize API for tokenization, and this API is currently returning errors with this stack trace:
```
File "/.../src/helm/tokenizers/vertexai_tokenizer.py", line 43, in __init__
creds.refresh(auth_req)
File "/.../lib/python3.8/site-packages/google/oauth2/service_account.py", line 441, in refresh
access_token, expiry, _ = _client.jwt_grant(
File "/.../lib/python3.8/site-packages/google/oauth2/_client.py", line 308, in jwt_grant
response_data = _token_endpoint_request(
File "/.../lib/python3.8/site-packages/google/oauth2/_client.py", line 279, in _token_endpoint_request
_handle_error_response(response_data, retryable_error)
File "/.../lib/python3.8/site-packages/google/oauth2/_client.py", line 72, in _handle_error_response …
```
=> Remove Gemini's dependency on Vertex AI tokenize API

src/helm/clients/simple_client.py, src/helm/config/model_deployments.yaml, src/helm/config/tokenizer_configs.yaml, src/helm/proxy/services/test_remote_service.py, src/helm/tokenizers/simple_tokenizer.py, src/helm/tokenizers/test_simple_tokenizer.py
This fixes `SimpleTokenizer` so that it is in a state that can be used for tutorials.
Previously, `SimpleTokenizer` was missing encoding and decoding, which means that it could not be used for various window services. This pull request adds encoding and decoding.
This also adds a unit test, which will be required for future tokenizers submitted to HELM.
=> Fix SimpleTokenizer

src/helm/clients/anthropic_client.py, src/helm/config/model_metadata.yaml
#2471 introduces a bug where `AnthropicClient` traverses into the key "error" in the response without first checking if it exists, resulting in the error:
```
File "/.../helm/clients/anthropic_client.py", line 210, in _is_content_moderation_failure
if response["error"]["message"] == "Output blocked by content filtering policy":
KeyError: 'error'
```
=> Fix KeyError bug in AnthropicClient

src/helm/benchmark/presentation/run_display.py
Frontend support for linked images will be added in #2507, so we don't need to base64 encode those images.
Currently `instances.json` is extremely large (>50MB) which slows download time. This pull request greatly reduces the size of `instances.json`.
=> Remove base64 encoded input from instances

helm-frontend/vite.config.ts
Currently the yaml bundle is an empty file, so we can delete it.
=> Remove yaml bundle from Vite build

helm-frontend/src/utils/getReleaseUrl.ts
Bugfix: currently every version in the version dropdown goes to the latest version.
=> Fix version dropdown links

src/helm/config/model_deployments.yaml
- Use the default window service rather than `NoDecodingWindowService` (since the tokenizer supports encoding and decoding)
- Fix the class name (caused by a bad merge between #2413 and #2368)
=> Fix model deployment configuration for Gemini

src/helm/benchmark/static/schema_vlm.yaml
It seems like having `robustness` and `bias` present for some scenarios but no other cause scenarios that do not have it (like i2s) to fail on summarization. This was introduced by #2456 but seems to be a bug in `summarize` more than something caused by #2456. @yifanmai what do you think?
=> Remove bias and robustness metrics in VLM schema

src/helm/benchmark/annotation/image2structure/image_compiler_annotator.py, src/helm/benchmark/annotation/image2structure/webpage_compiler_annotator.py, src/helm/benchmark/metrics/vision_language/emd_utils.py, src/helm/benchmark/metrics/vision_language/image_metrics.py, src/helm/common/media_object.py
This PR fixes/introduces the following changes:
* `WebpageCompiler`: the error `directory not empty` on the cluster is fixed.
* `unknown_error` after compilation is no longer cached.
* `error` in image metrics is no longer cached
* Change caching of `MediaObject` (introduced by #2525 but not merged yet)
* Conversion to grayscale now uses weights instead of a mean
* Handle `PermissionError` when trying to load `transformers` model from the cache.
=> Fixes for image2structure

src/helm/benchmark/run_specs/vlm_run_specs.py, src/helm/benchmark/scenarios/vision_language/multipanelvqa_scenario.py, src/helm/benchmark/scenarios/vision_language/pope_scenario.py, src/helm/benchmark/static/schema_vlm.yaml
Hello, this PR is to add two vision-language scenarios to VHELM --- MultipanelVQA from https://arxiv.org/abs/2401.15847 and the POPE benchmark from https://aclanthology.org/2023.emnlp-main.20/.
There are two `subjects` (synthetic or real-world) and two `question_type` (multiple-choice or open) for MultipanelVQA, I use `get_short_answer_generation_adapter_spec` for open-ended generation and `get_multiple_choice_joint_adapter_spec` for multiple-choice type questions. For both scenarios, I use `get_exact_match_metric_specs` for evaluation.
Here's a screenshot after running `./pre-commit.sh`
Here're several screenshots and the `scenario_state.json` of toy runs on two scenarios (Qwen-VL-Chat on 25 instances):
`POPE`
[pope_scenario_state.json](https://github.com/stanford-crfm/helm/files/14785447 …
=> Add MultipanelVQA and POPE vision-language scenarios

setup.cfg, src/helm/benchmark/run_expander.py, src/helm/clients/vertexai_client.py
- Don't cache responses blocked by the content filter, because the filter may be lifted in the future
- Detect some kinds of content filtering that were not detected before by checking the finish reason
- Fix a bug due to a misplaced brace that caused there to be a single completion even if there were multiple `candidates` in the raw response
=> Fix caching and content block handling for Gemini

src/helm/config/model_deployments.yaml
The model had 2 `max_sequence_length`'s
=> Fix openai/gpt-3.5-turbo-instruct typo

src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/static/schema_mmlu.yaml
- Add `hide_win_rates` which hides win rates for a metric group.
- Hide win rates from the main MMLU leaderboard
- Add macro average column to the main MMLU leaderboard
- Change some display strings
=> Replace win rate with macro average for MMLU leaderboard

helm-frontend/src/components/Landing/MMLULanding.tsx, helm-frontend/src/components/MiniLeaderboard.tsx
New landing page:
Also changes the `MiniLeaderboard` to use the first table, rather than using `core_scenarios`. This is the same change as in #2366.
=> Improve MMLU landing page

src/helm/benchmark/run_specs/classic_run_specs.py, src/helm/benchmark/scenarios/thai_exam_scenario.py, src/helm/benchmark/static/schema_classic.yaml
This PR is to add ThaiExam scenario, 
**ThaiExam** is a benchmark comprising Thai multiple-choice examinations as follows:
**ONET:** The Ordinary National Educational Test (ONET) is an examination for students in Thailand. We select the grade-12 ONET exam, which comprises 5 subjects and each question has 5 choices. These subjects are Thai, English, Mathematics, Social Studies, and Science. We extracted these questions from the official 2021 ONET example, amounting to a total of 170 questions and options.
**IC:** The Investment Consultant (IC) examination, a licensing test for investment professionals in Thailand developed by the Stock Exchange of Thailand (SET), features 4 choices per question. We extracted questions for levels 1, 2, and 3 from the official SET website, resulting in a …
=> Add ThaiExam scenario

src/helm/benchmark/run_expander.py
This fixes an issue when running a command that doesn't use an Anthropic model still requires installing the `anthropic` library. e.g. 
```
helm-run -c src/helm/benchmark/presentation/run_specs_dec2023.conf -m 5 --suite debug --models-to-run openai/gpt-3.5-turbo-0613
```
results in:
```
helm.common.optional_dependencies.OptionalDependencyNotInstalled: Optional dependency anthropic is not installed. Please run `pip install crfm-helm[anthropic]` or `pip install crfm-helm[all]` to install it.
```
even though the command does not use any Anthropic models. This is because `AnthropicClaude2RunExpander` runs _before_ the `--models-to-run` filer is applied.
=> Remove Anthropic import from AnthropicClaude2RunExpander

src/helm/clients/vertexai_client.py
Detecting a `ValueError` no longer works because this [Google library change](https://github.com/googleapis/python-aiplatform/commit/b91edf52e2b993c3301a419ad89b473c31c60cc3) changes it from `ValueError` to `AttributeError`. In any case, relying on internal implementation details is brittle. 
Instead, we just check that `content.parts` is non-empty.
This also fixed a couple of bugs:
- Other `ValueErrors` are silently swallowed
- There was a nested double loop through `candidates` where only only a single loop was required
=> Better handling for VertexAI response content with no parts

src/helm/clients/huggingface_client.py, src/helm/clients/test_huggingface_client.py, src/helm/config/model_deployments.yaml, src/helm/config/tokenizer_configs.yaml, src/helm/tokenizers/huggingface_tokenizer.py
Currently `HuggingFaceClient` doesn't work for all models where the model deployment name and model names are different, and `pretrained_model_name_or_path` is unset. This fixes the bug.
This also does some cleanup by deleting `resolve_alias()`, which has been replaced by `pretrained_model_name_or_path`.
=> Fix bug that caused incorrect Hugging Face model ID to be used

setup.cfg
OpenAI only requires `pydantic>=1.9.0`, but we call `model_dump(mode="json")` in `OpenAIClient`, which requires Pydantic 2. Therefore we need to add `pydantic~=2.0` to our own requirements. If Pydantic <2 is installed and an OpenAI model is used, this results in the error:
```
ValueError: mode is only supported in Pydantic v2
```
=> Require Pydantic 2

src/helm/benchmark/run_specs/vlm_run_specs.py, src/helm/benchmark/scenarios/vision_language/mme_scenario.py, src/helm/benchmark/scenarios/vision_language/pope_scenario.py, src/helm/benchmark/scenarios/vision_language/seed_bench_scenario.py, src/helm/benchmark/static/schema_vlm.yaml
Hello, this PR is to add two vision-language scenarios to VHELM --- Seed-Bench from https://arxiv.org/abs/2307.16125 and the MME benchmark from https://arxiv.org/abs/2306.13394.
For both benchmarks, I reformulated both of them as MCQA tasks. For Seed-Bench, I excluded the video reasoning task because VHELM doesn't currently support it.
Here are successful execution screenshots, conf files, and scenario_state files for two benchmarks.
Seed-Bench
`screenshot`
`conf file`
```
entries: [
{description: "seed_bench:subject=scene-understanding,model=qwen/qwen-vl-chat", priority: 1}
{description: "seed_bench:subject=spatial-relation,model=qwen/qwen-vl-chat", priority: 1}
]
```
`scenario state`
[seedbench_scenario_state.json](https://github.com/stanford-crfm/helm/files/14920361/seedbench_scenario_s …
=> Add Seed-Bench and MME scenarios

src/helm/benchmark/run_spec_factory.py
Multiple users have ran into issues with running various scenarios (verifiability, unitxt) due to the custom prompts. We should revert this for the v0.5.0 release until we figure out a better way to do custom prompts without breaking lots of scenarios.
The Claude 1 and 2 prompts can stay because they include the special Anthropic strings that are required for passing API validation.
=> Remove custom prompts from Google, Claude 3, OpenAI and Mistral models

src/helm/benchmark/run_expander.py
For some reason, OLMo terminates its answers to WMT14 with a single newline rather than a double newline, so we need to add single newline to the stop sequences for OLMo on WMT14 specifically.
=> Add newline as a special value for AddToStopRunExpander

docs/reproducing_leaderboards.md
Also fix some incorrect filenames.
=> Add MMLU leaderboard reproduction instructions to documentation

src/helm/benchmark/scenarios/legalbench_scenario.py, src/helm/benchmark/scenarios/math_scenario.py
This is required to avoid a breakage in the future:
```
FutureWarning: The repository for nguha/legalbench contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/nguha/legalbench
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
```
=> Add trust_remote_code=True to load_datasets() for math and legalbench

src/helm/config/model_metadata.yaml
- Rename Claude because our convention excludes model creator organization names from the model name 
- Rename DeepSeek to DeepSeek LLM becauase that is the official name
=> Rename some model names for consistency

helm-frontend/project_metadata.json, helm-frontend/public/config.js, helm-frontend/src/components/CardGrid.tsx, helm-frontend/src/components/Landing/HomeLanding.tsx, helm-frontend/src/components/NavDropdown.tsx, helm-frontend/src/components/ProjectCard.tsx, helm-frontend/src/components/ReleaseDropdown.tsx, helm-frontend/src/components/SimpleHero.tsx, helm-frontend/src/routes/Home.tsx
- Updates naming for global landing page -> home
- Updates global landing page to work on md and sm devices (tablet & mobile)
- Updates project metadata to be read from GH instead of GCP
- Updates naming for "projects" -> "leaderboards"
- Shows users which HELM subsite they are on in the dropdown
- Adds new copy (SEE BELOW)
Hero/landing: 
A reproducible and transparent framework for evaluating foundation models
Subtitle:
Find leaderboards with many scenarios, metrics, and models with support for multimodality and model-graded evaluation.
Leaderboard description: 
HELM leaderboards leverage the HELM framework and target particular domains and/or capabilities. Examples range from real-world applications or specific use cases to leaderboards focused on multimodal capabilities and …
=> Update global landing page

src/helm/clients/vertexai_client.py
This fixes three problems:
- Content blocking detection relies on string matching, which is brittle and likely to break when the Vertex AI library is upgraded
- Content blocking is handled differently for text and multimodal requests
- The logged errors for content blocking contain insufficient information
=> Improve handling of Gemini content blocking

src/helm/benchmark/metrics/vision_language/image_metrics.py
The EMD using the median color doesn't work. The next best choice is to use the constant color image that is furthest away from the reference image's modal color.
Some example:
Consider a grayscale image that has a value of 100. The color that is the furthest away would be 255.
Consider a grayscale image that has a value of 220. The color that is the furthest away would be 0.
So, we rule we have is that if the reference image (in grayscale) has a color of <127, we use a completely black colored image as the worst case scenario, and white colored image otherwise.
Hopefully, this will ensure that the EMD metric we are using will always produce positive numbers
=> Change EMD

helm-frontend/public/config.js, helm-frontend/src/components/Landing/HomeLanding.tsx, helm-frontend/src/components/SimpleHero.tsx
- remove redundant leaderboard copy
- remove whitespace so leaderboard header peaks into top (can make it higher/have the text fully visible if that's preferred)
=> Refactor home page slightly

helm-frontend/src/components/Landing/MMLULanding.tsx, helm-frontend/src/components/VHELMLanding.tsx
Layout is two column on large screens and one column on mobile. Also drive-by fix to MMLU make the column formatting identical between MMLU and VHELM.
=> Add mini-leaderboard to VHELM

setup.cfg
On `google-cloud-aiplatform` versions 1.47 and below, VertexAIClient fails with the following error:
```
File "/.../helm/src/helm/clients/vertexai_client.py", line 200, in do_it
if response.prompt_feedback and response.prompt_feedback.block_reason:
AttributeError: 'GenerationResponse' object has no attribute 'prompt_feedback'
```
=> Require google-cloud-aiplatform~=1.48

src/helm/config/tokenizer_configs.yaml
According to the [Hugging Face Hub page](https://huggingface.co/Snowflake/snowflake-arctic-instruct):
> Arctic is currently supported with `transformers` by leveraging the [custom code feature](https://huggingface.co/docs/transformers/en/custom_models#using-a-model-with-custom-code), to use this you simply need to add `trust_remote_code=True` to your `AutoTokenizer` and `AutoModelForCausalLM` calls.
=> Add trust_remote_code to Snowflake Arctic tokenizer

docs/get_helm_rank.md
Model huggingface/gpt2 got renamed as openai/gpt2. get_helm_rank.md didn't reflect this.
References #2190
=> Update get_helm_rank.md to reflect the renaming from huggingface/gpt2 to openai/gpt2

src/helm/benchmark/presentation/run_entries_multimed_qa.conf, src/helm/benchmark/run_specs/classic_run_specs.py
- Use only the test split for evaluation (rather than both the test and validation splits)
- Use open ended generation metrics for open ended QA (rather than summarization metrics)
=> Update HELM Medical run specs and run entries

src/helm/benchmark/run_specs/decodingtrust_run_specs.py
This is required for computing toxic_fraction.
=> Enable include_generative_harms_metrics for decodingtrust_toxicity_prompts

src/helm/clients/test_together_client.py, src/helm/clients/together_client.py
`TogetherCompletionClient` uses the official Together Python library. This future-proofs us by ensuring we are on the official path, since Together has previously made API changes that break our raw HTTP `TogetherClient`. We will switch to this for future Together models.
=> Add TogetherCompletionClient

src/helm/benchmark/metrics/vision_language/emd_utils.py, src/helm/benchmark/metrics/vision_language/image_metrics.py, src/helm/benchmark/run_specs/vlm_run_specs.py, src/helm/benchmark/static/schema_image2structure.yaml
1. Rename to EMS and EMS (white) instead of Block EMS (median) and block EMS (white)
2. Use predicted image as an additional identifier for cache
3. Clam EMS white to above 0
=> Bug fix for Image2Struct

helm-frontend/src/components/LeaderboardTables.tsx, helm-frontend/src/components/NavDropdown.tsx, helm-frontend/src/components/RowValue.tsx
TLDR: opacity or any filters in tailwind break the z-index.
=> Fix z-index additional bugs

src/helm/clients/client.py, src/helm/clients/openai_client.py
Currently any `OpenAIClient` model that has `VISION_LANGUAGE_MODEL_TAG` cannot accept text prompts only. This is because `OpenAIClient` previously assumed that every model was _either_ a text model _or_ a VLM, but not both. This is no longer true: `gpt-4-turbo-2024-04-09` and `gpt-4o-2024-05-13` support both image and text inputs.
Example failure:
```
File "/.../helm/src/helm/clients/openai_client.py", line 299, in make_request
return self._make_chat_request(request)
File "/.../helm/src/helm/clients/openai_client.py", line 170, in _make_chat_request
cache_key = self._get_cache_key(raw_request, request)
File "/.../helm/src/helm/clients/openai_client.py", line 64, in _get_cache_key
assert request.multimodal_prompt is not None
```
=> Support text prompts for GPT-4o

src/helm/config/model_deployments.yaml, src/helm/config/tokenizer_configs.yaml, src/helm/tokenizers/cohere_tokenizer.py, src/helm/tokenizers/test_cohere_tokenizer.py
Add `CohereLocalTokenizer`, which uses the Cohere Python library to perform tokenization locally.
This will eventually allow us to delete `CohereWindowService`, which was intended to work around token limits on the Cohere remote tokenization API.
=> Add CohereLocalTokenizer

src/helm/benchmark/metrics/prometheus_vision_critique_metrics.py, src/helm/benchmark/presentation/run_entries_vhelm.conf, src/helm/benchmark/presentation/run_entries_vhelm_debug.conf, src/helm/benchmark/run_specs/vlm_run_specs.py, src/helm/benchmark/scenarios/vision_language/bingo_scenario.py, src/helm/benchmark/scenarios/vision_language/mementos_scenario.py, src/helm/benchmark/scenarios/vision_language/unicorn_scenario.py, src/helm/clients/vision_language/huggingface_vlm_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/proxy/critique/model_critique_client.py
1. I corrected the `max_tokens` in the Unicorn scenario to 1, the results look fine now.
2. I modified the input prompt for three open-eneded VLM generation tasks --- `Crossmodal_3600, Bingo, Flickr30k`, to make VLMs generate more aligned answers with the reference, I have tested 50 instances on these three scenarios (`model=model=openai/gpt-4-vision-preview` with `_get_vibe_eval_critique_metric_specs()`), and the results look good.
4. I changed the metrics of these 3 scenarios to `_get_vibe_eval_critique_metric_specs()`, which can also be easily changed to `_get_prometheus_vision_critique_metric_specs()` as they do almost the same job.
@teetone would you take a look? And please let me know how I can improve it. Thanks!
=> Fix Open-ended VLM Generation Metrics

helm-frontend/src/components/AnnotationsDisplay.tsx
The current annotations display assumes that there is an enclosing list around the dict, but this may not be the case generally. For now, we hack in support for a dict without an enclosing list to support AIRBench 2024.
Addresses #2697
=> Allow dicts to be displayed in AnnotationsDisplay without a enclosing list

src/helm/config/model_deployments.yaml
This ensures that the correct chat template and stop sequences are used.
=> Switch most Together chat models to use the chat client

src/helm/clients/vertexai_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
This adds models such as `google/gemini-1.5-pro-001-safety-default` and `google/gemini-1.5-pro-001-safety-block-none`, which are variants of the base model with different safety settings.
=> Add Gemini variants with differing safety settings

src/helm/benchmark/annotation/air_bench_annotator.py
If the generated output is empty, then when calling the GPT-4o with the prompt template inside the template, GPT-4o often hallucinates a fictional model output. This can result in false positives or incorrect formatting.
Instead, if the generated output is empty, we set `prompt_text` to the empty string, `reasoning` to `BLOCKED_REQUEST_OR_EMPTY_RESPONSE` and score to 0.0.
=> Skip AIRBench annotator if generated output is empty

src/helm/config/model_deployments.yaml
This updates the `class_name` for the clients to reflect the new package after the move in #2413.
=> Fix incorrect client class names for PaLM-2 models

src/helm/clients/auto_client.py, src/helm/clients/client.py, src/helm/clients/huggingface_client.py
Many Hugging Face `AutoModelForCausalLM` implementations return the end of text token in the generated text, therefore we have to strip it in `truncate_sequence()`.
Fixes #2637
=> Truncate end of text token in HuggingFaceClient

src/helm/benchmark/run_expander.py, src/helm/benchmark/run_spec_factory.py, src/helm/benchmark/scenarios/test_air_bench_scenario.py
MedLM-large does not support stop sequences, even though MedLM-medium supports stop sequences. We need to remove all stop sequences for this model.
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Unable to submit request because the model does not support the stopSequences parameter. Remove it and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview"
debug_error_string = "UNKNOWN:Error received from peer ipv4:xxx.xxx.xxx.xxx:443 {grpc_message:"Unable to submit request because the model does not support the stopSequences parameter. Remove it and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview", …
```
=> Set stop sequences to empty for MedLM-large

src/helm/config/model_metadata.yaml
Update Gemini descriptions to clarify that we use Vertex AI and to specify the safety settings used.
=> Update descriptions of Gemini

helm-frontend/src/components/LeaderboardTables.tsx
Updates the headers to have a list of strings that can be ignored (instead of just one). This includes the AIR Bench header.
=> Hacky fix for air bench headers

src/helm/config/model_metadata.yaml
By convention, we save space by not putting the organization name in the model name. The command models did not follow this convention before, so we fix it to follow the convention.
=> Change Command model names to match convention

src/helm/benchmark/annotation/live_qa_annotator.py, src/helm/benchmark/annotation/medication_qa_annotator.py, src/helm/benchmark/metrics/instruction_following_critique_metrics.py, src/helm/benchmark/metrics/live_qa_metrics.py, src/helm/benchmark/metrics/medication_qa_metrics.py, src/helm/benchmark/run_specs/classic_run_specs.py, src/helm/benchmark/static/schema_medical.yaml
This updates these open ended medical scenarios (liveQA and medicationQA) to use model as judge.
This implementation uses 4 buckets as human judges did in the LiveQA paper, and then 3 for MedicationQA (no recommended approach).
=> Add Model as Judge for medical scenarios

src/helm/benchmark/run_expander.py
The `output_format_instructions` run expander adds extra instructions to about output formatting to HELM Lite scenarios.
Many instruction-following models and chat models are tuned to expect conversational prompts and respond in a conversational way. These models occasionally produce outputs that are not in the expected format. This run expander instructs these models to provide the output in the format expected by the scenario.
=> Add output_format_instructions run expander

src/helm/benchmark/run_expander.py
Some instruction-tuned models will try to answer the first question (i.e. the in-context learning question) instead of the last one. This change adds a way for the `output_format_instructions` run expander to tell the models to answer the last question.
=> Add "Answer only the last question" instruction using run expander

src/helm/benchmark/scenarios/entity_data_imputation_scenario.py
The source file has been moved from the original URL https://dbs.uni-leipzig.de/file/Abt-Buy.zip so we mirror it on GCS instead.
=> Move source dataset files for entity_data_imputation to GCS

.github/workflows/test_scenarios.yml, setup.cfg, src/helm/benchmark/scenarios/test_commonsense_scenario.py, src/helm/benchmark/scenarios/test_gsm_scenario.py, src/helm/benchmark/scenarios/test_legalbench_scenario.py, src/helm/benchmark/scenarios/test_math_scenario.py, src/helm/benchmark/scenarios/test_med_qa_scenario.py, src/helm/benchmark/scenarios/test_mmlu_scenario.py, src/helm/benchmark/scenarios/test_narrativeqa_scenario.py
Changes:
- Added a new pytest mark for scenario tests
- Excluded scenario tests from the default test workflow
- Add new scenario test workflow to run scenario tests when a scenario test is added or modified
- Added scenario tests for most HELM Lite scenarios
- Upgrade gdown to fix MedQA scenario breakage
Proposed new policy: Any new text-completion-only scenario _must_ be accompanied with a unit test.
=> Add workflow for scenario tests

src/helm/benchmark/scenarios/decodingtrust_stereotype_bias_scenario.py
Set `split=TEST_SPLIT` during evaluation instance generation so that all prompts will be retained during filtering.
=> Fix the zero instance problem in DecodingTrust 

setup.cfg, src/helm/clients/huggingface_client.py, src/helm/config/model_deployments.yaml, src/helm/tokenizers/huggingface_tokenizer.py
Add multi-GPU support to HuggingFaceClient via Hugging Face Accelerate. To use multi-GPU support, set `device_map` to `auto` in the model deployment.
Also enable multi-GPU support for some large Hugging Face models.
=> Add multi-GPU support to HuggingFaceClient

src/helm/common/mongo_key_value_store.py
Previously, this method would not delete anything (and potentially stall for a long time on a large MongoDB collection) because the query was incorrect.
=> Fix MongoKeyValueStore.remove()

.github/workflows/test.yml, .github/workflows/update-requirements.yml, requirements.txt
Fix error on Python 3.10 by removing `backports.zoneinfo` from `requirements.txt`:
```
Failed to build backports.zoneinfo
ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects
```
Also fix this error by switching `test.yml` to not use `virtualenv`:
```
________________ TestQ16.test_is_appropriate_single_appropriate ________________
self = <helm.benchmark.metrics.image_generation.q16.test_q16.TestQ16 object at 0x7f68f0bd6320>
def test_is_appropriate_single_appropriate(self):
image_path: str = os.path.join(self._base_path, "sample_appropriate.jpg")
>       assert not self._q16_detector.is_inappropriate(image_path)
src/helm/benchmark/metrics/image_generation/q16/test_q16.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Fix backports.zoneinfo and pkg_resources breakages in main

src/helm/benchmark/scenarios/bhasa_scenario.py
Doing `dataset[split][file] = []` is not permitted because `dataset` is of type `Dict[str, pd.DataFrame]`.
=> Fix typing error in UITVSFCScenario

src/helm/benchmark/scenarios/thai_exam_scenario.py
Switch data storage of ThaiExam to HF. 
It's now linked to ThaiExam v1 (e.g., all splits have 5 examples for in-context learning & fixed broken examples).
=> Switch data storage to HF with revision

src/helm/benchmark/run_expander.py
Addresses a failure mode of MATH on Claude 3.5 Sonnet - it does not wrap the final answer in LaTeX box formatting, leading to a very low accuracy score. This pull request changes the `output_format_instructions` run expander to add instructions to do so.
=> Add output_format_instructions run expander for MATH

scripts/compute_request_limits.py
- Register model deployments before looking up the model deployments
- Use hyphens instead of underscores in flag names
- Make `--model-deployment` a required parameter
- Get the model name and tokenizer name from the model deployment, rather than the command line
- Use the correct credential parsing function from the HELM library
- Change the path flags to use `--local-path` to follow the same convention as `helm-run`
=> Fix bugs in compute_request_limits.py

src/helm/benchmark/adaptation/adapters/multiple_choice_joint_adapter.py, src/helm/benchmark/adaptation/adapters/test_multiple_choice_joint_adapter.py
Previously, the reference prefix in `MultipleChoiceJointAdapter` expected options to be "A", "B", "C". This supports other single character options, such as "1", "2", "3" or "a", "b", "c".
=> Support other reference prefixes in MultipleChoiceJointAdapter

helm-frontend/src/components/ReleaseDropdown.tsx
This fixes the error `Warning: Each child in a list should have a unique "key" prop.` in `ReleaseDropdown`.
=> Add React keys for ReleaseDropdown

src/helm/config/model_deployments.yaml
Llama 3 Instruct uses the chat template, which takes up a few tokens.
=> Shorten Llama 3 Instruct context length

helm-frontend/src/components/CardGrid.tsx
=> Use two columns for card grid on small screens for home

setup.cfg
Allow newer versions of `open-clip-torch` and `torch` to be used. This is needed to upgrade PyTorch to >=2.2, which is needed to address security issues.
=> Widen VLM dependencies

setup.cfg
`scikit-images` needs to pinned to 0.21.0, which is the only version, that provides wheels for all of HELM's supported Python versions i.e. Python 3.8, 3.9, 3.10. Otherwise, pip will attempt download and build incompatible versions during dependency resolution, which leads to this error if numpy is not installed: https://github.com/scikit-image/scikit-image/pull/4920
=> Pin version of scikit-images

.github/workflows/upgrade-requirements.yml
Upgrading requirements using Python 3.10 results in a number of Python 3.8-incompatible dependencies being selected.
=> Upgrade requirements using Python 3.8

src/helm/benchmark/presentation/test_run_entry.py
Tests are slow and download lots of external dependencies.
=> Skip run entry tests

requirements.txt
This is not supported by Python >=3.9.
=> Remove backports.zoneinfo from requirements.txt

.github/workflows/update-requirements.yml, install-dev.sh, install-heim-extras.sh
- Install `torch==2.2.2` and `torchvision==0.17.2` in manual installation scripts
- Bump requested versions of `gunicorn`, `onnx` and `urllib3` to resolve Dependabot alerts
=> Update dependencies in manual install scripts

helm-frontend/src/services/getDisplayPredictionsByName.ts, helm-frontend/src/services/getDisplayRequestsByName.ts, helm-frontend/src/services/getGroupTablesByName.ts, helm-frontend/src/services/getGroupsMetadata.ts, helm-frontend/src/services/getGroupsTables.ts, helm-frontend/src/services/getInstances.ts, helm-frontend/src/services/getRunSpecByName.ts, helm-frontend/src/services/getRunSpecs.ts, helm-frontend/src/services/getRunsToRunSuites.ts, helm-frontend/src/services/getScenarioByName.ts, helm-frontend/src/services/getSchema.ts, helm-frontend/src/services/getStatsByName.ts
In strict model (i.e. development mode), components will be double-rendered, which will lead to data-fetching calls being aborted. Previously, this caused many `DOMException: signal is aborted without reason` error messages to be printed to the console. Since it is expected for the calls to be aborted, we suppress logging these errors instead.
=> Suppress logging AbortError when data fetching calls are aborted

.github/workflows/test-daily-integration.yml, .github/workflows/test.yml
OpenVINO on Optimum Intel test is flaky and slow, so we move it from continuous tests to daily integration tests.
=> Move OpenVINO on Optimum Intel test to daily integration tests

src/helm/config/model_deployments.yaml
Together has increased the sequence lengths for the 8B and 70B models.
=> Update Llama 3.1 Instruct Turbo sequence lengths

helm-frontend/project_metadata.json, helm-frontend/src/components/ProjectCard.tsx
- Shorten the menu entry description for Image2Struct
- Only add "HELM" prefix to Lite, Classic and Instruct in project card titles
=> Update project titles and descriptions

src/helm/benchmark/presentation/run_entries_ewok.conf, src/helm/benchmark/scenarios/ewok_scenario.py
Fix a bug in which the same instance ID was used for both instances (each of two possible targets) generated from the same row in the source dataset.
=> Fix instance IDs for EWoK

src/helm/benchmark/run_expander.py
Add instructions to only translate the last sentence. This addresses problems with Llama 3.1 (8B) which will otherwise output the translations for every sentence.
=> Add more WMT-14 instructions to output_format_instructions run expander

src/helm/proxy/example_queries.py
- Remove `model_deployment`, which is now auto-inferred
- Removed `max_tokens: 0` example, which no longer works
=> Update examples for crfm-models API server

src/helm/benchmark/run_expander.py
Fixes an issue with Nemotron-4 Instruct - on MMLU, for only certain subjects (High School US History, High School World History, High School Mathematics), the model responds with the reasoning for the answer instead of a single letter.
This can be fixed by appending "Answer with only a single letter." to the prompt as a suffix. Prepending this instruction to the prompt as a prefix, which we've done with other instruction-tuned models, does not work.
=> Add MMLU instructions suffix run expander

README.md
Don't need this - it should be in the developer docs rather than the README.md.
=> Remove directory structure from README.md

setup.cfg, src/helm/benchmark/metrics/code_metrics_helper.py
`pyext` is not supported in Python >=3.11, and its only usage is in APPS.
=> Remove pyext from dependencies

.github/workflows/frontend.yml
Run `yarn build` in the GitHub Action that runs frontend tests on pull requests. This detects errors such as type checking errors and missing imports.
This fixes a problem where pull requests would pass the checks, but merging the pull request would cause the main branch to fail checks. Example: pull request #2929, commit ad8873425d29b711c03237d173b739ce37676d1e.
=> Run yarn build in frontend CI

scripts/redact_scenario_states.py
This script modifies all scenario_state.json files in place within a suite to removing all prompts, instance input text, and instance reference output text from the `ScenarioState`s.
This is used when the scenario contains prompts that should not be displayed, in order to reduce the chance of data leakage or to comply with data privacy requirements.
=> Add script for redacting scenario states

src/helm/benchmark/run_specs/finance_run_specs.py, src/helm/benchmark/scenarios/banking77_scenario.py, src/helm/benchmark/static/schema_finance.yaml
BANKING77 is a benchmark for intent classification of customer service queries in the banking domain.
While BANKING77 was already included in the RAFT meta-benchmark, the RAFT version does not contain all the examples from the original dataset. This version uses the original dataset so that we can use all ~3k labeled rows in the test split.
=> Add BANKING77 scenario

src/helm/benchmark/run_expander.py
`nvidia/nemotron-4-340b-instruct` always translates the first in context learning example rather than the evaluation example. It can be instructed to translate the evaluation example, but the instruction seems to work more reliably if provided at the end of the prompt, rather than the start of the prompt.
=> Add WMT instructions suffix to output_format_instructions run expander

src/helm/benchmark/annotation/xstest_annotator.py
The annotator prompt incorrectly asks for a "short_reasoning" key in the returned JSON object, but the code requires this key to be "reasoning".
=> Fix keys for XSTestAnnotator

helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/components/Predictions.tsx, helm-frontend/src/routes/Home.tsx, helm-frontend/src/routes/Run.tsx, helm-frontend/src/types/DisplayPrediction.ts, helm-frontend/src/types/DisplayPredictionsMap.ts, helm-frontend/src/types/DisplayRequest.ts, helm-frontend/src/types/DisplayRequestsMap.ts, helm-frontend/src/types/Instance.ts
Fixes #2940
Frontend now displays perturbations like so:
=> Handle perturbations in run predictions frontend

helm-frontend/src/components/Landing/ThaiExamLanding.tsx
SCBX should be spelled as SCBX rather than SCB X.
=> Fix spelling of SCBX

src/helm/benchmark/run_expander.py
Some models such as Nemotron-4-Instruct require the instructions to be a suffix rather than a prefix.
=> Allow output_format_instructions to add instructions as suffix

src/helm/benchmark/run_expander.py
The labels are 'Yes' and 'No' rather than 'yes' and 'no', so the instructions should use the correct casing.
=> Fix casing in LegalBench instructions run expander

src/helm/benchmark/run_expander.py, src/helm/clients/openai_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/proxy/services/server_service.py
- Add `openai/o1-preview-2024-09-12` and `openai/o1-mini-2024-09-12`
- Update OpenAIClient to handle API changes for o1
- Add temperature and max token run expanders, because o1 needs a temperature of 1.0 and many more max tokens for reasoning
- Add a new crfm-models proxy API quota group `o1`
=> Add o1 models

src/helm/benchmark/metrics/unitxt_metrics.py, src/helm/benchmark/presentation/run_entries_tables.conf, src/helm/benchmark/static/schema_tables.yaml
LLM as judge in Unitxt can produce metrics that are strings rather than numbers, so we have to handle them correctly in `UnitxtMetric` in HELM.
=> Add LLM as judge metrics to HELM Tables

src/helm/benchmark/annotation/anthropic_red_team_annotator.py, src/helm/benchmark/annotation/harm_bench_annotator.py, src/helm/benchmark/annotation/model_as_judge.py, src/helm/benchmark/annotation/simple_safety_tests_annotator.py, src/helm/benchmark/annotation/xstest_annotator.py, src/helm/benchmark/metrics/safety_metrics.py
Previously, we failed a run if any annotator failed. After this PR, we only fail the run if every annotator failed. Otherwise, we recover by setting the safety score to the mean of the successful annotator scores.
=> Change how safety annotator scores are aggregated

src/helm/benchmark/static/schema_safety.yaml
Display the fraction of annotator requests to each annotator model that succeeded.
=> Add annotator success to HELM Safety schema

src/helm/common/key_value_store.py
Apparently this was causing an error for some users: 
```
File "/path/to/helm/common/key_value_store.py", line 14, in <module>
class KeyValueStore(contextlib.AbstractContextManager["KeyValueStore"]):
TypeError: 'ABCMeta' object is not subscriptable
```
=> Remove type parameter from AbstractContextManager for KeyValueStore

.pre-commit-config.yaml
Run the checks when pushing rather than when committing. This should make the developer workflow much faster.
=> Move pre-commit to pre-push

install-dev.sh
We temporarily downgrade pip in CI due to #2855, but we shouldn't do this on the developer's environment because it could be too disruptive.
=> Don't downgrade pip in install-dev.sh

docs/developer_setup.md
Changes:
- Recommend `pip install -e .[dev]` over `pip install -e .[all]` or `pip install -r requirements.txt`, because this takes way too long and requires too much disk space.
- Add `--force-reinstall` to replace any previous PyPI install with a local editable install.
- Recommend Python 3.10 over 3.9, because 3.10 is the version provided by Ubuntu 22.04 LTS and is more recent.
- Add instructions for using `pyenv`
- Clarified how the linter, type-checker, and git hooks work
=> Update developer setup instructions

src/helm/benchmark/presentation/run_entries_legal.conf, src/helm/benchmark/static/schema_legal.yaml
Adds run_entries and schema for evaluations on legal reasoning.
I am not sure, I need all metrics, perturbations, etc. in schema.yaml. Please let me know which I can remove.
This is a quick PR, so we can evaluate on legal tasks in Marin. I will make a later PR where I add more LegalBench tasks. To do that, we need to change the the [helm_prompt_settings](https://github.com/HazyResearch/legalbench/blob/main/helm_prompt_settings.jsonl) in the LegalBench repo or link move these prompt settings to HELM. Please let me know what you prefer there.
=> Added configuration for running legal evaluations

.github/workflows/frontend.yml, .pre-commit-config.yaml, helm-frontend/package.json, pre-commit-frontend.sh, pre-commit.sh
This unifies the local pre-commit for the frontend with what GitHub Actions actually runs. Previously, the local pre-commit used a pre-commit version of prettier, and GitHub actions used the yarn-installed versions of prettier and eslint. Now, the local pre-commit also uses the yarn-installed versions of prettier and eslint.
=> Improve local frontend pre-commit

src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/static/schema_safety.yaml
Adds the option for users to do mean metric aggregation as opposed to mean win rate within helm summarize.
In addition it allows for mutliple types of aggregation in parallel (as opposed to just one).
=> Add mean row aggregation to HELM summarize

docs/adding_models.md, docs/custom_models.md
This will eventually replace [Adding new models](https://crfm-helm.readthedocs.io/en/latest/adding_new_models/) because it documents the new way of adding models that does not require forking HELM.
Fixes #2379
=> Documentation: Custom models

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
Also adds a new tokenizer `meta/llama-3-8b-instruct` and switches `together/llama-3-8b-chat` to use this new tokenizer. This tokenizer uses a different end of string token compared to the `meta/llama-3-8b` tokenizer.
=> Add Palmyra-Med and Palmyra-Fin models

src/helm/benchmark/presentation/create_plots.py, src/helm/benchmark/presentation/summarize.py
#2997 broke reverse compatibility by defaulting to no win-rate or mean columns, rather than defaulting to a win-rate column. This restores the original behavior by defaulting to a win-rate column.
=> Default to win rate column if no aggregation strategies are specified

src/helm/config/model_deployments.yaml
The original model name in the config file for LLaMA 3 8B was `meta-llama/Meta-Llama-3-8B`, which is not in the Together API documentation [https://docs.together.ai/docs/inference-models](https://docs.together.ai/docs/inference-models).
Instead, the language model version of LLaMA 3 8B has the name `meta-llama/Llama-3-8b-hf` on Together. 
Note that LLaMA 3 **70B** has the correct name `meta-llama/Meta-Llama-3-70B`, and thus does not need changes. There seems to be some inconsistency in the naming convention of Together.
=> LLaMA-3 8B Together model name

README.md, docs/heim.md, docs/index.md, docs/installation.md, docs/vhelm.md
Previous, references to HEIM were scattered throughout multiple documentation pages. This centralizes them to the HEIM page.
=> Clean up HEIM docs

src/helm/benchmark/scenarios/gpqa_scenario.py, src/helm/benchmark/scenarios/test_gpqa_scenario.py
Switched to using TRAIN_SPLIT for the excluded train examples instead of not including them in the dataset
=> Adding train examples to GPQA

docs/downloading_raw_results.md
`gsutil rsync` is deprecated and users should use `gcloud storage rsync` instead, as recommended by the [gsutil documentation](https://cloud.google.com/storage/docs/gsutil).
Fixes #2676
=> Change GCS download docs to use gcloud storage instead of gsutil

src/helm/config/model_deployments.yaml
This makes the behavior consistent with the other Gemini models in HELM.
=> Use BLOCK_NONE by default for gemini-1.5-flash-002

src/helm/benchmark/run_specs/lite_run_specs.py, src/helm/benchmark/scenarios/gpqa_scenario.py, src/helm/benchmark/scenarios/test_gpqa_scenario.py
Added the basic few-shot run_specs for GPQA (using the excluded train examples). 
Due to the need for train examples, this PR is depending on the previous #3078.
=> Few-shot run_specs for GPQA, CoT not included yet

docs/installation.md
These links were removed in #3050, but the resulting docs were confusing for users. This pull request adds the links back.
=> Link to VHELM and HEIM from the installation doc

src/helm/benchmark/static/schema_lite_v2.yaml
Schema file for GPQA and MMLU-Pro.
Usage: download the file and then run:
```sh
helm-summarize --suite my-suite --schema-path path/to/schema_lite_v2.yaml
```
=> Schema file for GPQA and MMLU-Pro.

docs/adding_new_models.md, src/helm/clients/huggingface_client.py
Allow setting `device` inside `args` for `HuggingFaceClient` to override the device of the Hugging Face model.
Fixes #1683.
=> Allow setting device for Hugging Face models

helm-frontend/src/components/Hero.tsx
=> Fix padding around mini leaderboard for Classic and Lite

src/helm/benchmark/run_specs/lite_run_specs.py, src/helm/benchmark/scenarios/mmlu_pro.py, src/helm/benchmark/scenarios/test_mmlu_pro_scenario.py, src/helm/benchmark/scenarios/test_mmlu_scenario.py, src/helm/common/images_utils.py
Added the mmlu_pro.py (scenario), lite_run_spec.py, and test_mmlu_pro_scenario.py
This is the implementation for MMLU Pro without Chain of Thought.
=> Changed MMLU Pro for Non-COT Version

helm-frontend/src/components/InstanceData.tsx, helm-frontend/src/routes/Run.tsx
Basic functionality for linking to specific instances from Predictions page(s)
See demo below (note added button for link after demo GIF)
=> Add functionality for linking directly to instances in Predictions page

src/helm/benchmark/adaptation/adapter_spec.py, src/helm/benchmark/adaptation/adapters/adapter_factory.py, src/helm/benchmark/adaptation/adapters/multiple_choice_joint_adapter.py, src/helm/benchmark/adaptation/adapters/multiple_choice_joint_chain_of_thought_adapter.py, src/helm/benchmark/adaptation/common_adapter_specs.py, src/helm/benchmark/run_specs/lite_run_specs.py
Added adaptation enum for CoT, updated run spec function with `use_chain_of_thought` parameter.
=> GPQA Few-shot CoT, spec part

src/helm/benchmark/presentation/summarize.py
Fixes an error when trying to use `aggregation_strategies: ["mean"]` in `schema.yaml` with `helm-summarize`:
```
Traceback (most recent call last):
File "/path/to/crfm-helm/bin/helm-summarize", line 8, in <module>
sys.exit(main())
File "/path/to/crfm-helm/lib/python3.10/site-packages/helm/common/hierarchical_logger.py", line 104, in wrapper
return fn(*args, **kwargs)
File "/path/to/crfm-helm/lib/python3.10/site-packages/helm/benchmark/presentation/summarize.py", line 1315, in main
summarizer.run_pipeline(skip_completed=args.skip_completed_run_display_json)
File "/path/to/crfm-helm/lib/python3.10/site-packages/helm/benchmark/presentation/summarize.py", line 1223, in run_pipeline
self.write_groups()
File "/path/to/crfm-helm/lib/python3.10/site-packages/helm/benchmark/presentation/summarize.p …
```
=> Skip models column when summarizing mean

src/helm/benchmark/adaptation/adapter_spec.py, src/helm/benchmark/adaptation/adapters/adapter_factory.py, src/helm/benchmark/adaptation/adapters/multiple_choice_joint_adapter.py, src/helm/benchmark/adaptation/adapters/multiple_choice_joint_chain_of_thought_adapter.py, src/helm/benchmark/adaptation/common_adapter_specs.py, src/helm/benchmark/run_specs/lite_run_specs.py, src/helm/benchmark/scenarios/gpqa_scenario.py
Used the extra_data field to store the chains of thought in the train instances of GPQA.
=> GPQA Few shot CoT

src/helm/benchmark/scenarios/audio_language/audio_mnist_scenario.py, src/helm/clients/openai_client.py, src/helm/common/audio_utils.py, src/helm/common/multimodal_request_utils.py
- Rename `ensure_audio_file_exists` to `ensure_wav_file_exists_from_array` to more accurately reflect its purpose.
- Changed `ensure_wav_file_exists_from_array` to avoid race conditions.
- Changed `get_contents_as_bytes` and `get_contents_as_base64` to support both local paths and URLs
- Deleted `encode_base64` as it is a duplicate of `get_contents_as_base64`
=> Improvements to audio utilities

src/helm/benchmark/run_expander.py
Adds an extra instruction to not include the 'English:' prefix in the answer, because Claude 3.5 Sonnet likes to do this.
=> Add wmt_14_no_prefix to output_format_instructions run expander

src/helm/benchmark/presentation/run_entries_speech.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/audiocaps_senario.py, src/helm/benchmark/static/schema_speech.yaml
[scenario_state.json](https://github.com/user-attachments/files/17654468/scenario_state.json)
Add AudioCaps scenario.
=> Add AudioCaps scenario

src/helm/clients/nvidia_nim_client.py, src/helm/clients/openai_client.py, src/helm/clients/palmyra_client.py, src/helm/clients/vllm_client.py, src/helm/clients/yi_client.py, src/helm/config/model_deployments.yaml
- Make `OpenAIClient` use the chat completion API by default
- Require users of the legacy completions API to use the new `OpenAILegacyCompletionsClient` class instead
- Move known users of the legacy completions API to `OpenAILegacyCompletionsClient` i.e. `babbage-002`, `davinci-002`, `gpt-3.5-turbo-instruct` and `VLLMClient`
=> Deprecate OpenAI legacy completions API

src/helm/benchmark/augmentations/cleva_perturbation.py, src/helm/benchmark/augmentations/dialect_perturbation.py, src/helm/benchmark/augmentations/person_name_perturbation.py, src/helm/benchmark/augmentations/synonym_perturbation.py, src/helm/benchmark/metrics/cleva_harms_metrics.py, src/helm/benchmark/scenarios/code_scenario.py, src/helm/benchmark/scenarios/dialogue_scenarios.py, src/helm/benchmark/scenarios/ice_scenario.py
Replace hardcoded "benchmark_output" In 
- `person_name_perturbation`, `cleva_perturbation`, `synonym_perturbation`, `cleva_harms_metrics`, `dialogue_scenarios`, `dialect_perturbation` 
- as well as comments in `ice_scenario` and `code_scenario`
Related (#493 )(#1918)
Found hardcoded "benchmark_output" by
```shell
find ./src/helm -type f -name "*.py" -exec grep -n "benchmark_output" {} + | grep -v "benchmark_output_path"
```
There could be a similar issue in `./benchmark/server.py`, but haven't investigated further about it.
```shell
./benchmark/server.py:138:        # Output path is a location on disk, so set the output path base URL to /benchmark_output
./benchmark/server.py:142:        app.config["helm.outputurl"] = "benchmark_output"
```
=> Replace hardcoded "benchmark_output"

src/helm/benchmark/metrics/image_generation/skin_tone_metrics.py
Blue and Red channels were switched, img_rgba is in rgb order but blue is being pulled from channel 0, red from channel 2. This PR swaps them to the correct channels.
=> fix R/B channel switch in skin tone calculation

src/helm/benchmark/presentation/run_entries_speech.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/air_bench_chat_scenario.py, src/helm/benchmark/static/schema_speech.yaml
Add Air-Bench chat (https://arxiv.org/abs/2402.07729). This benchmark consists of four different aspects for evaluation: sound, speech, music and mixed, which was employed by the Qwen2-audio paper for eval.
=> Add Air-Bench chat audio scenario

src/helm/benchmark/run_specs/unitxt_run_specs.py
Unitxt run spec names can be so long that they cause "File name too long" errors (since the output subdirectory is named after the run spec name). To work around this, if the `HELM_UNITXT_SHORTEN_RUN_SPEC_NAMES` environment variable is set, we drop some unneeded key-value pairs from the run spec name.
=> Shorten run spec names for Unitxt runs

docs/reproducing_leaderboards.md, src/helm/benchmark/presentation/run_entries_lite_20240424_output_format_instructions.conf
This adds a modified version of the Lite run entries that has been used for recent Lite leaderboard runs for instruction following models. These run entries add an additional instruction describing the task's output format, which prevents situations where instruction-following models would get extremely low scores due to incorrect output formatting.
=> Add run entries for Lite with instructions

setup.cfg
Workaround to avoid breaking API changes in version of 0.39.0 `anthropic`.
Addresses #3212
=> Limit anthropic to <0.39

MANIFEST.in, src/helm/benchmark/annotation/wildbench_annotator.py
Add the template to the manifest so it gets packaged, and import it using `importlib.resources`.
=> Fix template import in WildBenchAnnotator

src/helm/benchmark/presentation/run_entries_lite_20240424_nova.conf, src/helm/benchmark/run_expander.py
- Allow appending "Do not include 'Noun:' in your answer." to instructions
- Allow changing `natural_qa` instructions to '"Answer with a short answer."' instead of '"Answer with a short answer or a boolean 'yes' or 'no' answer."'
=> Add more instructions customization to output_format_instructions run expander

src/helm/clients/bedrock_client.py, src/helm/clients/bedrock_utils.py
HELM should not fetch the region from the OS environment variables, since overrides other configuration sources that should have precedence (e.g. config files set by `aws configure`), and boto3 already falls back to the OS environment variables internally.
=> Simplify credential management for Bedrock client

src/helm/benchmark/run_specs/mmlu_clinical_afr_run_specs.py, src/helm/benchmark/run_specs/winogrande_afr_run_specs.py, src/helm/benchmark/scenarios/mmlu_clinical_afr_scenario.py, src/helm/benchmark/scenarios/test_mmlu_clinical_afr_scenario.py, src/helm/benchmark/scenarios/test_winogrande_afr_scenario.py, src/helm/benchmark/scenarios/winogrande_afr_scenario.py
Description
This pull request introduces the first low-resource language translation of 3 medical subjects of Massive Multitask Language Understanding (MMLU) and Winograde Small dataset to be added to the HELM benchmark. This project focuses on bridging the gap for low-resource African languages, providing a valuable resource for researchers and developers working in this area.
Repository
https://github.com/InstituteforDiseaseModeling/Bridging-the-Gap-Low-Resource-African-Languages
Dataset
https://huggingface.co/datasets/Institute-Disease-Modeling/mmlu-winogrande-afr
Paper
https://arxiv.org/pdf/2412.12417
Highlights
- First low-resource language human translation of MMLU and Winogrande to be added to HELM.  
- Aims to enhance the HELM benchmark with more diverse language data.
- Provides …
=> Adding MMLU and Winogrande human-translated into 11 African languages

src/helm/clients/bedrock_client.py
Currently Amazon Nova models are reporting inference time in ms unit, which is not consistent with other models, changing it to report in seconds instead.
=>     Updating request time (inference time) to report in seconds instead of ms

src/helm/benchmark/run_specs/lite_run_specs.py
Increased the output max token number to 2000 for scenarios
=> increase the max token number to 2000

src/helm/benchmark/metrics/unitxt_metrics.py, src/helm/benchmark/run_specs/unitxt_run_specs.py, src/helm/benchmark/scenarios/unitxt_scenario.py
This allows using Unitxt recipes in run entries such as `unitxt:recipe=recipes.tables_benchmark.tab_fact.concat.insert_empty_rows_augmentation_5_demos,model=text`
=> Allow running recipes from the Unitxt catalog

src/helm/benchmark/annotation/wildbench_annotator.py, src/helm/benchmark/metrics/wildbench_metrics.py, src/helm/benchmark/presentation/run_entries_capabilities.conf, src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/run_specs/capabilities_run_specs.py, src/helm/benchmark/run_specs/lite_run_specs.py, src/helm/benchmark/scenarios/bigcodebench_scenario.py, src/helm/benchmark/scenarios/ifeval_scenario.py, src/helm/benchmark/scenarios/mmlu_pro_scenario.py, src/helm/benchmark/scenarios/wildbench_scenario.py, src/helm/benchmark/static/schema_lite_v2.yaml
- Switch aggregation to mean
- Use rescaled rather than raw wildbench score
- Move MMLU-Pro from `lite_run_specs.py` to `capabilities_run_specs.py`
- Clean up run spec names
- Change some default arguments
- Add revisions for Hugging Face datasets
- Remove unused parameter in wildbench
- Switch BigCodeBench version from v0.1.2 to v0.1.3
=> Misc cleanup for HELM Capabilities

src/helm/clients/auto_client.py, src/helm/clients/azure_openai_client.py, src/helm/clients/stanfordhealthcare_llama_client.py, src/helm/clients/stanfordhealthcare_openai_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Also adds support for OpenAI on Azure
Fixes #1415
=> Add GPT-4o-mini and Llama 3.3 70B on Stanford Health Care API

src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/asr/asr_scenario.py, src/helm/benchmark/scenarios/audio_language/asr/common_voice_15_scenario.py, src/helm/benchmark/scenarios/audio_language/asr/fleurs_scenario.py
Refactor the FLEURS ASRScenario
=> refactor fleurs asrscenario

src/helm/benchmark/metrics/classification_metrics.py, src/helm/benchmark/metrics/common_metric_specs.py, src/helm/benchmark/metrics/test_classification_metrics.py
- Breaking change: Do not strip articles when normalizing text (previously, this would be bad for a class named "a")
- Allow using different averaging methods for computing classification metrics
- Allow computing precision and recall
- Allow computing per-class classification metrics by using `None` as an averaging method
- Encourage users to explicitly set the labels
=> Improve classification metrics

src/helm/benchmark/annotation/wildbench_annotator.py, src/helm/benchmark/metrics/wildbench_metrics.py
Using GPT, LLaMA, and Claude to annotate the output in WildBench, and take an average for the scoring.
=> Include multiple annotators for WildBench

src/helm/benchmark/metrics/classification_metrics.py
This normalizes the provided labels before providing it to the `MultiLabelBinarizer`. Also, it warns users about missing labels only if the labels are actually missing.
=> Fix incorrect handling of labels in ClassificationMetric

src/helm/benchmark/metrics/evaluate_reference_metrics.py, src/helm/benchmark/presentation/run_entries_speech.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/static/schema_speech.yaml
1. Changed WA and MA to WER and MER for ASR tasks
2. Deleted some subjects in`run_entries_speech.conf` that requires other tokenizers
=> Fix ASR WER and MER metrics

scripts/redact_scenario_states.py
As part of MedHELM, we need the ability to redact not only the requests, but also the generated responses. This is to prevent PIH data from real patients.
=> Add support to redact model outputs

src/helm/benchmark/run_specs/imdb_ptbr_run_specs.py, src/helm/benchmark/scenarios/imdb_ptbr_scenario.py, src/helm/benchmark/scenarios/test_imdb_ptbr_scenario.py
The IMDB dataset is a widely-used benchmark dataset for natural language processing (NLP) particularly for text classification and sentiment analysis. This is a translated version that is meant to evaluate PT-BR models. It consists of movie reviews from the Internet Movie Database (IMDB) and includes both positive and negative sentiments labeled for supervised learning.
=> Adding IMDB_PTBR Scenario

src/helm/benchmark/annotation/annotator_factory.py, src/helm/benchmark/annotation/bigcodebench_annotator.py, src/helm/benchmark/scenarios/bigcodebench_scenario.py
- Allow using a cloned evaluator instance
- Allow using the `selective_evaluate` parameter for downsampling instances
- Remove `extra_data` from instances
- Misc style fixes
=> Fixes for BigCodeBench Evaluator

src/helm/clients/openai_client.py
Azure has additional content filter policies where the filter message doesn't match with supported content filters.
This PR aims to catch the content filter error thrown by Azure and treat the response like an empty response.
Example error:
```
OpenAI error: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400}}
```
=> Fix Azure content filter error

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
This Pull Request adds support for the DeepSeek R1 Distill Llama 8B and DeepSeek Code Instruct 6.7B models, which are open-source and available on the Hugging Face platform. These additions expand the available options for various NLP and code generation tasks.
- Added DeepSeek R1 Distill Llama 8B and DeepSeek Code Instruct 6.7B to the list of supported models.
- Updated configuration files to accommodate the specific parameters of these new models.
The DeepSeek R1 Distill Llama 8B model was evaluated on NLP tasks such as ENEM Challenge and TweetSent, while the DeepSeek Code Instruct 6.7B model was tested on HumanEval and APPS for code generation. These models demonstrated competitive performance within their respective domains.
By adding these models, we enhance flexibility in choosing …
=>  Add Support for DeepSeek R1 Distill Llama 8B and DeepSeek Code Instruct 6.7B

src/helm/benchmark/metrics/output_processing_metric.py, src/helm/benchmark/metrics/output_processors.py, src/helm/benchmark/metrics/test_output_postprocessors.py, src/helm/benchmark/run_expander.py
This adds a `process_output` run expander that will run a string function on all output text before it is passed to the metrics.
This allows evaluating DeepSeek R1 on scenarios that expect a specific output format e.g. MMLU can be run using ` mmlu:subject=anatomy,output_format_instructions=mcqa_only_last_question,increase_max_tokens=8192,process_output=helm.benchmark.metrics.output_processors.remove_deepseek_r1_thinking,model=deepseek-ai/deepseek-r1`
=> Allow processing output before metrics

src/helm/clients/together_client.py, src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
This adds a model `deepseek-ai/deepseek-r1-hide-reasoning` which is identical to `deepseek-ai/deepseek-r1` except that the thinking tokens are removed from the final output text. This emulates the behavior of OpenAI's o1 / o1-mini / o3-mini so that the two can be fairly compared.
=> Add a version of DeepSeek R1 that hides thinking tokens from output

src/helm/benchmark/scenarios/test_bigcodebench_scenario.py, src/helm/benchmark/scenarios/test_math_scenario.py, src/helm/benchmark/scenarios/test_wildbench_scenario.py
[competition_math](https://huggingface.co/datasets/hendrycks/competition_math) has been disabled on Hugging Face Hub due to a DMCA takedown
Also fix the BigCodeBench test.
=> Disable test_math_scenario due to DMCA takedown

src/helm/benchmark/presentation/run_entries_audio.conf, src/helm/benchmark/run_specs/audio_run_specs.py, src/helm/benchmark/scenarios/audio_language/ami_scenario.py, src/helm/benchmark/scenarios/audio_language/librispeech_scenario.py, src/helm/benchmark/scenarios/audio_language/speech_robust_bench_scenario.py, src/helm/benchmark/static/schema_audio.yaml
1. Add AMI, LibriSpeech audio scenarios and make sure that each example corresponds to their perturbed ones in Speech Robust Bench (SRB) scenario.
2. Add `in-the-wild-ami` subset to SRB and delete two subjects that cannot find correspondence with clean audios.
The mappings between LibriSpeech and SRB are:
`librispeech:model=audiolm`: `speech_robust_bench:subject=librispeech_gnoise,level=1,model=audiolm` (LibriSpeech audio files with different 'gnoise' perturbation)
`librispeech:model=audiolm`: `speech_robust_bench:subject=librispeech_env_noise,level=1,model=audiolm` (LibriSpeech audio files with different environment noise perturbation)
There are 30 different perturbation examples for every LibriSpeech ID in SRB, I added the `level` argument for assigning different samples for different …
=> Add AMI, LibriSpeech audio scenarios and fix Speech Robust Bench audio scenario

helm-frontend/src/components/Landing/SEAHELMLanding.tsx
Unfortunately logos are no longer permitted on the HELM website due to the [Stanford name use guidelines](https://trademarks.stanford.edu/name-use-guidelines).
=> Remove logo from SEA-HELM landing

src/helm/benchmark/metrics/gpt4_audio_critique_metrics.py, src/helm/benchmark/run_specs/audio_run_specs.py
I added GPT-4 as the evaluator for AirBench-Chat and AudioCaps, checked 10 examples each, and they look fine to me. 
I'll collect some samples for human evaluation later.
I used `openai/gpt-4-1106-preview` as the evaluator, so the `credentials.conf` looks like this:
```bash
openaiApiKey: openai-key
critiqueModelName: openai/gpt-4-1106-preview
critiqueType: model
```
=> Add GPT4 evaluator for open-ended audio scenarios

src/helm/clients/azure_openai_client.py
This allows setting `azure_openai_deployment_name` in `args` in `model_deployments.yaml`.
=> Make Azure OpenAI deployment name configurable

helm-frontend/vite.config.ts
Change the name to namespace it to the HELM frontend.
=> Rename Vite config environment variable to VITE_HELM_FRONTEND_BASE

.github/workflows/update-requirements.yml
Rename steps and use `pip freeze` instead of `uv pip freeze`.
=> Minor changes to Update requirements GitHub Action

setup.cfg
GitHub Actions can't install pytrec_eval for some reason, so we remove it.
```
Run uv pip compile setup.cfg --extra all --extra dev --universal --no-annotate --constraints constraints.txt -o requirements.txt
× Failed to build `pytrec-eval==0.5`
├─▶ The build backend returned an error
╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit
status: 1)
[stdout]
Fetching trec_eval from
https://github.com/usnistgov/trec_eval/archive/v9.0.8.tar.gz.
[stderr]
Traceback (most recent call last):
File "<string>", line 14, in <module>
File
"/home/runner/.cache/uv/builds-v0/.tmpnEgVyF/lib/python3.9/site-packages/setuptools/build_meta.py",
line 334, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=[])
File …
```
=> Move pytrec_eval to its own optional dependencies section

src/helm/benchmark/presentation/run_entries_medhelm.conf, src/helm/benchmark/run_specs/medhelm_run_specs.py, src/helm/benchmark/scenarios/mimic_bhc_scenario.py, src/helm/benchmark/static/schema_medhelm.yaml
@MiguelAFH @aunell @suhana13 
Added the MIMIC-IV-BHC benchmark to MedHelm scenarios.
MIMIC-IV-BHC is a curated collection of preprocessed clinical discharge notes from MIMIC-IV paired with their corresponding brief hospital course (BHC) summaries [(Aali et al., 2024)](https://doi.org/10.1093/jamia/ocae312).
=> Added the MIMIC-IV-BHC benchmark to MedHelm scenarios

src/helm/benchmark/metrics/conv_fin_qa_calc_metrics.py, src/helm/benchmark/metrics/evaluate_reference_metrics.py, src/helm/benchmark/run_specs/enterprise_run_specs.py, src/helm/benchmark/scenarios/conv_fin_qa_calc_scenario.py, src/helm/benchmark/static/schema_enterprise.yaml
This is a mathematical calculation benchmark based on ConvFinQA: Exploring the Chain of Numerical Reasoning in Conversational Finance Question Answering [(Chen ey al., 2022)](https://arxiv.org/pdf/2210.03849.pdf) from the IBM Enterprise benchmark.
=> Add ConvFinQACalc

src/helm/clients/openai_client.py, src/helm/clients/stanfordhealthcare_deepseek_client.py, src/helm/config/model_deployments.yaml
The initial addition of the deepseek model with the Stanford HealthCare client didn't remove the thinking tokens from the model response. This PR fixes that problem.
FYI @suhana13 @HennyJie @aunell
=> Remove deepseek thinking tokens

src/helm/benchmark/annotation/annotator_factory.py, src/helm/benchmark/annotation/image2struct/image_compiler_annotator.py, src/helm/benchmark/annotation_executor.py, src/helm/benchmark/run_specs/air_bench_run_specs.py
- Remove the `AnnotatorFactory` cache
- Remove unnecessary duplicate instantiations of the annotator
- Make all Image2Struct annotators single-threaded
=> Allow arguments to be passed into annotators

src/helm/benchmark/run_specs/air_bench_run_specs.py
This fixes a bug in #3468 in which the arguments were not actually passed into the annotator. This also requires the change in #3487 to allow annotators to receive arguments.
=> Actually make AIR-Bench 2024 annotator configurable

src/helm/clients/openai_client.py
Specifying any level of "reasoning effort" for o1 / o3-mini models resulted in an error:
```
helm.proxy.services.remote_service.RemoteServiceError: Failed to make request to openai/o1-2024-12-17-low-reasoning-effort after retrying 5 times. Error: OpenAI error: Error code: 400 - {'error': {'message': "Invalid value: 'self.reasoning_effort'. Supported values are: 'low', 'medium', and 'high'."...
```
After some investigation, we suspect the cause is [this line in the OpenAI Client](https://github.com/stanford-crfm/helm/blob/main/src/helm/clients/openai_client.py#L245), where a hardcoded string is set as reasoning_effort.
This PR aims to fix the issue.
=> Fix the `reasoning_effort` parameter in Openai Client

src/helm/benchmark/run_specs/medhelm_run_specs.py
Reasoning models were using new line token as first output for MedCalc-Bench and MedHallu. Since these scenarios have new line as the stop sequence, all model responses were empty.
This change removes all stop sequences except for max tokens. Since the exact match metric uses strip(), there is no disadvantage when removing this \n stop sequence.
FYI @raulista1997 @HennyJie
=> Change stop sequence for MedCalc and MedHallu

setup.cfg
Medhelm had missing dependencies not listed on the setup.cfg file. This PR adds fix this issue.
=> Added missing dependencies for medhelm

helm-frontend/src/components/NavBar/NavBar.tsx
Previously, the leaderboard first column incorrectly covered the dropdown menu for small screens.
Before:
After:
=> Fix mobile menu z-index

scripts/medhelm/redact_annotations.py
This PR adds a redaction process for annotations that may leak information about private datasets. After redaction, annotations will look like:
```json
{
"annotations": {
"starr_patient_instructions": {
"prompt_text": "[redacted]",
"gpt": {
"accuracy": {
"score": 4,
"explanation": "[redacted]"
},
"completeness": {
"score": 3,
"explanation": "[redacted]"
},
"clarity": {
"score": 4,
"explanation": "[redacted]"
}
},
"llama": {
"accuracy": {
"score": 4,
"explanation": "[redacted]"
},
"completeness": {
"score": 4,
"explanation": "[redacted]"
},
"clarity": {
"score": 5,
"explanation": "[redacted]"
}
},
"claude": {
"accuracy": {
"score": 4,
"explanation": "[redacted]"
},
"completeness": {
"score": 2,
"explanation": "[redacted]"
},
"clarity": {
"score": 4,
"explanation": "[redacted]"
}
}
}
}
} …
```
=> Added annotation redaction for MedHELM

src/helm/benchmark/annotation/air_bench_annotator.py
Previously empty responses was scored as 0, but since the AIR-Bench score was swapped from 0 is better to 1 is better, they should be scored as 1.
=> Fix bug with AIR-Bench handling of empty responses

src/helm/benchmark/presentation/run_entries_capabilities_reasoning_v2.conf, src/helm/benchmark/run_expander.py
The new instructions are intended to deal with cases where the model responds "The answer is..." followed by the full answer instead of a single letter.
=> Add run entries with additional tokens and instructions for reasoning models

src/helm/benchmark/scenarios/mmlu_pro_scenario.py
The subject "computer science" has a space in it, so we have to replace underscores with space so that a run entry like `mmlu_pro:subset=computer_science` will work correctly.
=> Allow running the MMLU-Pro computer science subject

src/helm/clients/anthropic_client.py
See #3546 for discussions.
Increase `MAX_OUTPUT_TOKENS` for `AnthropicMessagesClient` to 64k according to https://docs.anthropic.com/claude/docs/models-overview
=> Adjust `max_tokens` restriction for Anthropic models

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml, src/helm/config/tokenizer_configs.yaml
In this PR, I added configuration of 21 Vietnamese LLMs into HELM, including:
- URA-LLaMa 2.1 7B
- URA-LLaMa 2 7B
- URA-LLaMa 7B
- URA-LLaMa 14B
- URA-LLaMa 70B
- GemSUra 7B
- GemSUra 2B
- MixSUra
- VinaLLaMa 7B
- VinaLLaMa 2.7B
- Vietcuna 7B v3
- Vietcuna 3b v2
- Quyen v0.1
- Quyen Plus v0.1
- Quyen Pro v0.1
- Quyen Pro Max v0.1
- Quyen Mini v0.1
- Quyen SE v0.1
- Vistral 7B
- PhoGPT 7.5B
- PhoGPT 4B
=> Adding 21 Vietnamese LLMs

src/helm/benchmark/adaptation/adapters/test_adapter.py, src/helm/benchmark/executor.py, src/helm/benchmark/metrics/metric_service.py, src/helm/benchmark/metrics/tokens/test_openai_token_cost_estimator.py, src/helm/benchmark/runner.py, src/helm/benchmark/scenarios/numeracy_scenario.py, src/helm/benchmark/window_services/test_utils.py, src/helm/benchmark/window_services/tokenizer_service.py, src/helm/common/context.py, src/helm/common/local_context.py, src/helm/common/remote_context.py, src/helm/proxy/services/server_service.py
Creates a new `Context` object that doesn't access the SQLite accounts file, and use in the executor in the helm-run code path.
Fixes #1914
=> Avoid accessing SQLite accounts file in helm-run

src/helm/benchmark/presentation/run_entries_safety_palmyra_x5.conf, src/helm/benchmark/run_expander.py
Palmyra X5 responds to MCQA questions with a trailing period e.g. "A." so it needs to be specifically told not to do that.
=> Run expander for Palmyra X5

src/helm/benchmark/server.py
We discovered a small issue in the HELM server where /config.js does not set a proper MIME type, meaning browsers will refuse to execute it if the `X-Content-Type-Options: nosniff` is ever injected (e.g. if HELM is behind a proxy).
This PR fixes that issue.
=> fix: set MIME type for config.js in server

src/helm/benchmark/run.py
Annoyingly I missed keeping `validate_args()` in the run function for `helm-run` in #3598; this PR adds it back in as it seems important.
=> fix: issue where validate_args() was missed in helm-run

src/helm/benchmark/scenarios/audio_language/corebench_scenario.py, src/helm/benchmark/static/schema_audio.yaml
1. We want to be more precise with the prompts so that the ALM will produce `unanswerable` when the question is not relevant to the conversation, but is answerable.
2. Changed the tag from `bias` to `reasoning`
=> Changed prompts for COREBench

src/helm/common/hierarchical_logger.py
- Use default color instead of black for the timestamp so that it is visible on terminals with black backgrounds
- Use ISO 8601 datetime format without timezone or microseconds (e.g. `2025-05-22T10:45:32`) to save four space and to improve machine readability
Addresses #3595
cc @Gum-Joe
=> Minor tweaks to log format

src/helm/clients/openai_client.py
Quick fix to the special casing in the OpenAI client to remove `top_p`, `frequency_penalty` and `presence_penalty` from requests to the o-series models, as these params are unsupported.
=> fix: remove top_p, frequency_penalty and presence_penalty from o series models as unsupported

src/helm/clients/anthropic_client.py, src/helm/config/model_deployments.yaml
This avoids a `ValueError` with the following message raised by the Anthropic client when non-streaming requests are used with too many tokens:
> Streaming is strongly recommended for operations that may take longer than 10 minutes. See https://github.com/anthropics/anthropic-sdk-python#long-requests for more details
=> Support streaming in Anthropic client

src/helm/clients/openai_client.py
vLLM has a optional `reasoning_content` field in the message that is not in the standard OpenAI API. This field is also used by some model providers such as Grok. This PR puts the contents of this field into the `thinking` field of `RequestResponse`.
=> Support reasoning_content from vLLM model responses

src/helm/clients/together_client.py
Previously, if the response from Together was truncated before the thinking closing tag, only the first line of the thinking would be preserved due to an incorrect regex.
=> Fix incorrect thinking parsing in TogetherClient

src/helm/benchmark/metrics/openai_mrcr_metrics.py, src/helm/benchmark/presentation/run_entries_long_context.conf, src/helm/benchmark/run_specs/long_context_run_specs.py, src/helm/benchmark/scenarios/infinite_bench_en_qa_scenario.py, src/helm/benchmark/scenarios/infinite_bench_sum_scenario.py, src/helm/benchmark/scenarios/ruler_qa_scenario_helper.py, src/helm/benchmark/scenarios/ruler_qa_scenarios.py, src/helm/benchmark/scenarios/test_infinite_bench_en_qa_scenario.py, src/helm/benchmark/scenarios/test_infinite_bench_sum_scenario.py, src/helm/benchmark/static/schema_long_context.yaml
- Unify the parameters for all scenarios (`max_num_words` only)
- Change OpenAI-MRCR to OpenAI MRCR
- Set up run entries file
- Reorder infinite_bench_en_qa before infinite_bench_sum
- Update scenario descriptions in code and schema
- Increase max number of words from 65536 to 131072
=> Long context leaderboard cleanup

src/helm/common/hierarchical_logger.py
This addresses the double logging issue due to absl logging installing a root handler when it is imported. See #3595 for more explanation.
Fixes #3595
=> Disable logging propagation

src/helm/config/model_deployments.yaml, src/helm/config/model_metadata.yaml
Also add production versions of Gemini 2.5 Pro and Gemini 2.5 Flash, and fix the ordering of models.
=> Add Gemini 2.5 Flash-Lite

src/helm/clients/openai_client.py, src/helm/clients/openai_responses_client.py, src/helm/config/model_deployments.yaml
Noticed that a HELM Client that supports the OpenAI Responses API was added in 6ef825ed894b91822c65f99611155d239018d928 in #3523, but then was missing when the PR was merged.
Newer models like `o3-pro` only support the responses API, so this PR adds the client back in, updates it a little to e.g. insert reasoning into the HELM response & bring in some logic from the main client as well.
NOTE: My ability to test this against all the benchmarks is limited, I have validated it at least works with some text only benchmarks, where "works" here means "I can see results on the web ui".
=> Add back in OpenAI Responses Client

src/helm/benchmark/presentation/create_plots.py, src/helm/benchmark/presentation/test_create_plots.py
Ignores the following type checking errors after upgrading dependencies:
```
src/helm/benchmark/presentation/create_plots.py:117: error: "Axis" has no attribute "scatter"  [attr-defined]
src/helm/benchmark/presentation/create_plots.py:118: error: "Axis" has no attribute "boxplot"  [attr-defined]
src/helm/benchmark/presentation/create_plots.py:120: error: "Axis" has no attribute "set_xticklabels"; maybe "set_ticklabels" or "get_ticklabels"?  [attr-defined]
src/helm/benchmark/presentation/create_plots.py:122: error: "Axis" has no attribute "set_xticklabels"; maybe "set_ticklabels" or "get_ticklabels"?  [attr-defined]
src/helm/benchmark/presentation/create_plots.py:318: error: "Artist" has no attribute "get_data"  [attr-defined]
```
This probably means that this script no longer works, …
=> Disable linting for create_plots

src/helm/benchmark/run_specs/healthqa_br_run_specs.py, src/helm/benchmark/scenarios/healthqa_br_scenario.py, src/helm/benchmark/scenarios/test_healtha_br_scenario.py
This PR aims to add the HealthQA-BR benchmark, composed of 5,632 multiple-choice questions from official Brazilian medical residency and professional licensing exams. The questions are in Brazilian Portuguese and span various healthcare fields such as medicine, nursing, dentistry, psychology, social work, pharmacy, physiotherapy, among others. Unlike benchmarks focused on international contexts, this dataset was specifically designed to evaluate language models on challenges relevant to the Brazilian Unified Health System (SUS). This addition enables the assessment of models' ability to understand and answer clinical and interprofessional questions grounded in the Brazilian healthcare context.
=> Add new benchmark in Brazilian Portuguese: HEALTHQA-BR

src/helm/benchmark/run_specs/bluex_run_specs.py, src/helm/benchmark/scenarios/bluex_scenario.py, src/helm/benchmark/scenarios/test_bluex_scenario.py
This PR aims to add the BLUEX benchmark, composed of 1,260 Brazilian university entrance exam questions in Brazilian Portuguese, of which 723 were selected for not containing images. The benchmark includes multiple-choice questions taken from the official exams of Unicamp (Convest) and USP (Fuvest), covering a wide range of high school subjects. While the original questions include both textual prompts and visual elements, this version includes only those without images. This addition is important for evaluating the models' ability to understand and answer more complex questions in Brazilian Portuguese.
=> Add new benchmark in Brazilian Portuguese: BLUEX

src/helm/benchmark/presentation/summarize.py, src/helm/benchmark/slurm_jobs.py, src/helm/clients/together_client.py, src/helm/common/critique_request.py
See #3693 for a discussion about why `StrEnum` introduces a number of gotchas.
=> Remove TODOs for StrEnums

docs/adding_new_models.md, src/helm/clients/vllm_client.py, src/helm/clients/vllm_granite_thinking_client.py
- Add `VLLMChatClient` for chat models on VLLM
- Change `VLLMGraniteThinkingClient` to inherit from `VLLMChatClient`
- Simplify logic for overriding the model name in vLLM clients
=> Support using chat models on vLLM

src/helm/clients/openai_responses_client.py
Realised there was a bug (when benchmarking a web search enabled OpenAI model) with the responses API code that assumes the only valid response types were "message" and "reasoning". Turns out this is incorrect, and the type field of outputs can contains tool calls it seems.
This PR fixes that bug to prevent crashes trying to access keys that don't exist, and also inserts web search tool calls into the reasoning info.
=> fix: there are other output types the responses API can return, so don't assume everything is a message

src/helm/benchmark/metrics/image_generation/clip_score_metrics.py, src/helm/benchmark/window_services/image_generation/clip_window_service.py
Addresses #3741
Manually instantiate `CLIPWindowService` using the parameters taken from the initial version of `CLIPWindowService` [here](https://github.com/stanford-crfm/helm/blob/346f765d9f03b866cb7454bbedc5aa7ed7199749/src/helm/benchmark/window_services/image_generation/clip_window_service.py).
=> Fix CLIPScoreMetric

install-dev.sh, requirements.txt, setup.cfg, src/helm/benchmark/scenarios/math_scenario.py, src/helm/clients/audio_language/qwen_omni/configuration_qwen2_5_omni.py, src/helm/common/object_spec.py
I'm a big fan of doctests. Not only do they provide great documentation examples, they give developers a quick and easy way to get an entrypoint into a function, and you can run them to enhance your test suite and ensure examples continue to work.
In this PR I noticed something that was almost a doctest, and I turned it into a fully fledged one. It adds a little bit of boilerplate, but I think the ability to copy / paste the snippet into IPython and play with it is invaluable.
I also added a doctest to `parse_object_spec`, that I wrote when I was playing with it to understand it. 
In addition to adding these doctests here I added `--doctest-modules` to the default pytest config in `setup.cfg` (which should probably be ported to fully use `pyproject.toml`, but that will be a different PR). …
=> Add doctests and enable them

helm-frontend/src/routes/Run.tsx
Previously on the run page, we displayed the scenario name and description from `scenario.json`, which is baked into the file based on class variables in the `Scenario` Python class at `helm-run` time. Now, we instead display the run group name and description from the schema if available, which can be updated before running `helm-summarize`, and is more likely to have information that is more human-friendly.
=> Show run group name and description from schema on run page

helm-frontend/src/routes/Scenarios.tsx, helm-frontend/src/types/RunGroup.ts, src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py
`short_description` is an optional short description of the run group. This description is used in some space-constrained places in frontend tables. If unset, the description field will be used instead.
This supports use cases in which the regular `description` can be very long.
Addresses #3757
=> Add short_description to RunGroup in schema

src/helm/proxy/retry.py
While I've been debugging HEIM, having to wait for 5 retries before getting a failure was making me wish there was a way to configure them.
Ideally this setting would be exposed in a CLI arg or config file somewhere (both in the most ideal situation), but because the number 5 seems to be hardcoded at the module level at import time that makes this approach difficult. So in the meantime, I just added two environment variables: `HELM_RETRIES` and `HELM_TOKENIZER_RETRIES` that provide some mechanism. 
In the future I would like to have a unified config system such that every aspect of the application can be configured in a similar way by either CLI args, a config file, or environment variables similar to how [cibuildwheel does it](https://cibuildwheel.pypa.io/en/latest/configuration/#configur …
=> Configurable number of retries 

docs/heim.md, requirements.txt, setup.cfg, src/helm/benchmark/metrics/image_generation/fractal_dimension/fractal_dimension_util.py, src/helm/benchmark/run_specs/heim_run_specs.py
Related to https://github.com/stanford-crfm/helm/issues/3741
I'm working on fixes to allow the HEIM benchmarks to be run with the latest version of HELM. I've been able to at least compute them, although visualizations seemed bugged. ~This PR is a draft because I have not verified that the example in the docs runs in a clean environment yet.~
I think this PR is now in a reasonable state. Changes are:
* Modify requirements in requirements.txt and setup.cfg to allow HEIM benchmarks to run on 3.9 and 3.10 with the latest code.
* Disable the `helm.benchmark.metrics.image_generation.nsfw_metrics.NSFWMetric` metric, which I have not been able to get working, and add a note in the code and docs about why it is disabled.
=> [DRAFT] HEIM fixes.

src/helm/benchmark/annotation/air_bench_annotator.py, src/helm/benchmark/annotation/live_qa_annotator.py, src/helm/benchmark/metrics/comet_metric.py, src/helm/benchmark/metrics/decodingtrust_stereotype_bias_metrics.py, src/helm/benchmark/scenarios/audio_language/casual_conversations2_scenario.py, src/helm/benchmark/scenarios/audio_language/mustard_scenario.py, src/helm/benchmark/scenarios/cleva_scenario.py, src/helm/benchmark/scenarios/melt_scenarios.py, src/helm/benchmark/scenarios/mimic_bhc_scenario.py, src/helm/benchmark/scenarios/seahelm_scenario.py, src/helm/benchmark/slurm_jobs.py, src/helm/proxy/cli.py
This should be a fairly simple PR where I fix invalid escape sequence warnings.
When I was working on doctests I noticed a lot of warning messages about incorrectly escaped strings. This was usually due to a bare backslash being used in a plain string, which currently is interpreted as a plain backslash, but that can't be guaranteed in future versions of Python, so many linters will flag it as a warning.
When possible, I just added the "r" prefix to make it a raw string. There were some cases where this didn't make sense (e.g. the newline `\n` or proper backslash `\\` character was used), so those cases I escaped the naked backslashes.
This does not fix the errors in math_scenario.py as I fixed those in [the doctest PR](https://github.com/stanford-crfm/helm/pull/3745).
=> Fix invalid escape sequences in strings

src/helm/clients/openrouter_client.py, src/helm/clients/test_openrouter_client.py, src/helm/config/model_deployments.yaml
This pull request introduces support for the OpenRouter API by adding a new client implementation, corresponding configuration, and tests to ensure correct behavior. The most important changes are grouped below:
**OpenRouter Client Implementation**
* Added new `OpenRouterClient` class in `src/helm/clients/openrouter_client.py`, inheriting from `OpenAIClient`, with logic to select the appropriate model and handle API key configuration via argument or environment variable.
**Configuration Updates**
* Added a new model deployment entry for `openrouter/mistral-medium-3.1` in `src/helm/config/model_deployments.yaml`, specifying the new client and its parameters.
**Testing**
* Added `src/helm/clients/test_openrouter_client.py` with tests for model selection logic and API key handling in …
=> Add OpenRouterClient implementation and tests

src/helm/benchmark/metrics/basic_metrics.py, src/helm/benchmark/metrics/gpqa_chain_of_thought_metric.py, src/helm/benchmark/metrics/ifeval_metrics.py, src/helm/benchmark/metrics/metric.py, src/helm/benchmark/metrics/omni_math_metrics.py, src/helm/benchmark/metrics/wildbench_metrics.py, src/helm/benchmark/presentation/schema.py, src/helm/benchmark/presentation/summarize.py
- Works similarly to #3814 but for metric groups
- Adds a `group` field in the `MetricMetadata`  which is used to auto-generate the metric groups
=> Auto-generate metric groups in helm-summarize

src/helm/benchmark/presentation/summarize.py
Also move `write_run_display_json()` to after schema auto-generation so that metrics are correctly displayed in the run predictions view.
=> Calculate win rates for auto-generated main metric group

src/helm/benchmark/static/schema_slp.yaml
Follow up on https://github.com/stanford-crfm/helm/pull/3778
As discussed offline, adding a schema YAML for the SLP leaderboard.
=> Add SLP Helm Leaderboard Schema

pyproject.toml, requirements.txt
Fix breakages by reverting numpy from 2.2.6 to 1.26.4:
```
FAILED src/helm/benchmark/metrics/image_generation/fractal_dimension/test_fractal_dimension_util.py::test_compute_fractal_dimension_cloud - ImportError: numpy.core.multiarray failed to import
FAILED src/helm/benchmark/metrics/image_generation/fractal_dimension/test_fractal_dimension_util.py::test_compute_fractal_dimension_sea_anemone - ImportError: numpy.core.multiarray failed to import
FAILED src/helm/benchmark/metrics/image_generation/fractal_dimension/test_fractal_dimension_util.py::test_compute_fractal_dimension_snowflake - ImportError: numpy.core.multiarray failed to import
FAILED src/helm/benchmark/metrics/image_generation/fractal_dimension/test_fractal_dimension_util.py::test_compute_fractal_dimension_convergence - …
```
=> Fix numpy version issue

src/helm/common/test_general.py
Skipping download tests because these downloads use files that are not hosted by us. The download paths are not reliable and may be throttled.
=> Skip download tests
